// AUTO-GENERATED by scripts/generate-website-themes.ts. Do not edit by hand.
// Run `bun run generate:website-themes` (or `bun run generate`) to refresh.
import ashleySeoTheme from '@avatune/ashley-seo-theme/vanilla'
import ashleyyTheme from '@avatune/ashleyy-theme/vanilla'
import cyberpunkTheme from '@avatune/cyberpunk-theme/vanilla'
import fatinVerseTheme from '@avatune/fatin-verse-theme/vanilla'
import kyuteTheme from '@avatune/kyute-theme/vanilla'
import micahTheme from '@avatune/micah-theme/vanilla'
import miniavsTheme from '@avatune/miniavs-theme/vanilla'
import nevmstasTheme from '@avatune/nevmstas-theme/vanilla'
import orksTheme from '@avatune/orks-theme/vanilla'
import pacovqzzTheme from '@avatune/pacovqzz-theme/vanilla'
import pawelOlekManTheme from '@avatune/pawel-olek-man-theme/vanilla'
import pawelOlekWomanTheme from '@avatune/pawel-olek-woman-theme/vanilla'
import retroCartoonTheme from '@avatune/retro-cartoon-theme/vanilla'
import toonFlatTheme from '@avatune/toon-flat-theme/vanilla'
import type { VanillaTheme } from '@avatune/types'
import yanliuTheme from '@avatune/yanliu-theme/vanilla'

export const avatarApiThemes = {
  'ashley-seo': ashleySeoTheme,
  ashleyy: ashleyyTheme,
  cyberpunk: cyberpunkTheme,
  'fatin-verse': fatinVerseTheme,
  kyute: kyuteTheme,
  micah: micahTheme,
  miniavs: miniavsTheme,
  nevmstas: nevmstasTheme,
  orks: orksTheme,
  pacovqzz: pacovqzzTheme,
  'pawel-olek-man': pawelOlekManTheme,
  'pawel-olek-woman': pawelOlekWomanTheme,
  'retro-cartoon': retroCartoonTheme,
  'toon-flat': toonFlatTheme,
  yanliu: yanliuTheme,
} satisfies Record<string, VanillaTheme>

export type AvatarApiThemeName = keyof typeof avatarApiThemes

export const avatarApiThemeNames = Object.keys(
  avatarApiThemes,
) as AvatarApiThemeName[]
