// AUTO-GENERATED by scripts/generate-website-themes.ts. Do not edit by hand.
// Run `bun run generate:website-themes` (or `bun run generate`) to refresh.
import ashleySeoTheme from '@avatune/ashley-seo-theme/react'
import ashleyyTheme from '@avatune/ashleyy-theme/react'
import cyberpunkTheme from '@avatune/cyberpunk-theme/react'
import fatinVerseTheme from '@avatune/fatin-verse-theme/react'
import kyuteTheme from '@avatune/kyute-theme/react'
import micahTheme from '@avatune/micah-theme/react'
import miniavsTheme from '@avatune/miniavs-theme/react'
import nevmstasTheme from '@avatune/nevmstas-theme/react'
import orksTheme from '@avatune/orks-theme/react'
import pacovqzzTheme from '@avatune/pacovqzz-theme/react'
import pawelOlekManTheme from '@avatune/pawel-olek-man-theme/react'
import pawelOlekWomanTheme from '@avatune/pawel-olek-woman-theme/react'
import retroCartoonTheme from '@avatune/retro-cartoon-theme/react'
import toonFlatTheme from '@avatune/toon-flat-theme/react'
import type { ReactTheme } from '@avatune/types'
import yanliuTheme from '@avatune/yanliu-theme/react'

export type ThemeId =
  | 'ashleySeo'
  | 'ashleyy'
  | 'cyberpunk'
  | 'fatinVerse'
  | 'kyute'
  | 'micah'
  | 'miniavs'
  | 'nevmstas'
  | 'orks'
  | 'pacovqzz'
  | 'pawelOlekMan'
  | 'pawelOlekWoman'
  | 'retroCartoon'
  | 'toonFlat'
  | 'yanliu'

export interface ThemeInfo {
  id: ThemeId
  label: string
  packageName: string
}

export const themeMap: Record<string, ReactTheme> = {
  ashleySeo: ashleySeoTheme,
  ashleyy: ashleyyTheme,
  cyberpunk: cyberpunkTheme,
  fatinVerse: fatinVerseTheme,
  kyute: kyuteTheme,
  micah: micahTheme,
  miniavs: miniavsTheme,
  nevmstas: nevmstasTheme,
  orks: orksTheme,
  pacovqzz: pacovqzzTheme,
  pawelOlekMan: pawelOlekManTheme,
  pawelOlekWoman: pawelOlekWomanTheme,
  retroCartoon: retroCartoonTheme,
  toonFlat: toonFlatTheme,
  yanliu: yanliuTheme,
}

/** Keyed by the theme's doc slug (kebab-case, e.g. `retro-cartoon`). */
export const themeMapBySlug: Record<string, ReactTheme> = {
  'ashley-seo': ashleySeoTheme,
  ashleyy: ashleyyTheme,
  cyberpunk: cyberpunkTheme,
  'fatin-verse': fatinVerseTheme,
  kyute: kyuteTheme,
  micah: micahTheme,
  miniavs: miniavsTheme,
  nevmstas: nevmstasTheme,
  orks: orksTheme,
  pacovqzz: pacovqzzTheme,
  'pawel-olek-man': pawelOlekManTheme,
  'pawel-olek-woman': pawelOlekWomanTheme,
  'retro-cartoon': retroCartoonTheme,
  'toon-flat': toonFlatTheme,
  yanliu: yanliuTheme,
}

export const themeInfos: ThemeInfo[] = [
  {
    id: 'ashleySeo',
    label: 'Ashley Seo',
    packageName: '@avatune/ashley-seo-theme',
  },
  { id: 'ashleyy', label: 'Ashleyy', packageName: '@avatune/ashleyy-theme' },
  {
    id: 'cyberpunk',
    label: 'Cyberpunk',
    packageName: '@avatune/cyberpunk-theme',
  },
  {
    id: 'fatinVerse',
    label: 'Fatin Verse',
    packageName: '@avatune/fatin-verse-theme',
  },
  { id: 'kyute', label: 'Kyute', packageName: '@avatune/kyute-theme' },
  { id: 'micah', label: 'Micah', packageName: '@avatune/micah-theme' },
  { id: 'miniavs', label: 'Miniavs', packageName: '@avatune/miniavs-theme' },
  { id: 'nevmstas', label: 'Nevmstas', packageName: '@avatune/nevmstas-theme' },
  { id: 'orks', label: 'Orks', packageName: '@avatune/orks-theme' },
  { id: 'pacovqzz', label: 'Pacovqzz', packageName: '@avatune/pacovqzz-theme' },
  {
    id: 'pawelOlekMan',
    label: 'Pawel Olek Man',
    packageName: '@avatune/pawel-olek-man-theme',
  },
  {
    id: 'pawelOlekWoman',
    label: 'Pawel Olek Woman',
    packageName: '@avatune/pawel-olek-woman-theme',
  },
  {
    id: 'retroCartoon',
    label: 'Retro Cartoon',
    packageName: '@avatune/retro-cartoon-theme',
  },
  {
    id: 'toonFlat',
    label: 'Toon Flat',
    packageName: '@avatune/toon-flat-theme',
  },
  { id: 'yanliu', label: 'Yanliu', packageName: '@avatune/yanliu-theme' },
]
