// AUTO-GENERATED by scripts/generate-website-themes.ts. Do not edit by hand.
// Run `bun run generate:website-themes` (or `bun run generate`) to refresh.

export interface ThemeDocItem {
  label: string
  previewId: string
  slugs: string[]
}

export const themeDocItems: ThemeDocItem[] = [
  {
    label: 'Ashley Seo',
    previewId: 'ashley-seo',
    slugs: ['packages', 'ashley-seo-theme'],
  },
  {
    label: 'Ashleyy',
    previewId: 'ashleyy',
    slugs: ['packages', 'ashleyy-theme'],
  },
  {
    label: 'Cyberpunk',
    previewId: 'cyberpunk',
    slugs: ['packages', 'cyberpunk-theme'],
  },
  {
    label: 'Fatin Verse',
    previewId: 'fatin-verse',
    slugs: ['packages', 'fatin-verse-theme'],
  },
  { label: 'Kyute', previewId: 'kyute', slugs: ['packages', 'kyute-theme'] },
  { label: 'Micah', previewId: 'micah', slugs: ['packages', 'micah-theme'] },
  {
    label: 'Miniavs',
    previewId: 'miniavs',
    slugs: ['packages', 'miniavs-theme'],
  },
  {
    label: 'Nevmstas',
    previewId: 'nevmstas',
    slugs: ['packages', 'nevmstas-theme'],
  },
  { label: 'Orks', previewId: 'orks', slugs: ['packages', 'orks-theme'] },
  {
    label: 'Pacovqzz',
    previewId: 'pacovqzz',
    slugs: ['packages', 'pacovqzz-theme'],
  },
  {
    label: 'Pawel Olek Man',
    previewId: 'pawel-olek-man',
    slugs: ['packages', 'pawel-olek-man-theme'],
  },
  {
    label: 'Pawel Olek Woman',
    previewId: 'pawel-olek-woman',
    slugs: ['packages', 'pawel-olek-woman-theme'],
  },
  {
    label: 'Retro Cartoon',
    previewId: 'retro-cartoon',
    slugs: ['packages', 'retro-cartoon-theme'],
  },
  {
    label: 'Toon Flat',
    previewId: 'toon-flat',
    slugs: ['packages', 'toon-flat-theme'],
  },
  { label: 'Yanliu', previewId: 'yanliu', slugs: ['packages', 'yanliu-theme'] },
]
