// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

/// Namespace for the cyberpunk theme's generated data.
public enum CyberpunkTheme {}

extension AvatuneTheme {
  /// The cyberpunk theme, generated from @avatune/cyberpunk-theme@1.0.0.
  public static let cyberpunk: AvatuneTheme = AvatuneTheme(
    name: "cyberpunk",
    style: AvatuneTheme.Style(size: 560, borderRadius: .percent(50)),
    backgroundPalette: [.hex(0xFFEDEF)],
    categories: [
      AvatuneTheme.Category(
        category: .body,
        palette: [.hex(0x000000)],
        items: CyberpunkTheme.bodyItems
      ),
      AvatuneTheme.Category(
        category: .eyes,
        palette: [.hex(0x000000)],
        items: CyberpunkTheme.eyesItems
      ),
      AvatuneTheme.Category(
        category: .hair,
        palette: [.hex(0x071538), .hex(0xC229A1), .hex(0x10687A)],
        items: CyberpunkTheme.hairItems
      ),
      AvatuneTheme.Category(
        category: .head,
        palette: [.hex(0xFCBE93), .hex(0xC78A5C), .hex(0x80502E), .hex(0xFDCDAC)],
        items: CyberpunkTheme.headItems
      ),
      AvatuneTheme.Category(
        category: .mouth,
        palette: [.hex(0x000000)],
        items: CyberpunkTheme.mouthItems
      ),
      AvatuneTheme.Category(
        category: .nose,
        palette: [.hex(0x000000)],
        items: CyberpunkTheme.noseItems
      )
    ],
    connectedColors: [],
    predictorMappings: nil
  )
}
