// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

/// Item identifiers for the cyberpunk theme.
public enum Cyberpunk {
  public enum Body: String, CaseIterable, Sendable {
    case hoodie
    case poncho1
    case jacket1
    case jacket2
    case jacket3
    case poncho
    case jacket4
  }

  public enum Eyes: String, CaseIterable, Sendable {
    case brave
    case sharp
    case round
    case husky
    case focused
    case curious
    case anxious
  }

  public enum Hair: String, CaseIterable, Sendable {
    case short
    case stylish
    case bob
    case braids
    case medium
    case forehead
  }

  public enum Head: String, CaseIterable, Sendable {
    case oval
    case robot
    case rhombus
    case squaredOval
  }

  public enum Mouth: String, CaseIterable, Sendable {
    case `open`
    case lips
    case smiling
    case nervous
    case hooky
  }

  public enum Nose: String, CaseIterable, Sendable {
    case standard
    case metal
    case wide1
    case clothespin
    case narrow
    case wide2
  }
}
