// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

/// Item identifiers for the kyute theme.
public enum Kyute {
  public enum Hair: String, CaseIterable, Sendable {
    case bob
    case curly
    case curlyMedium
    case elvis
    case long
    case longThick
    case longWavy
    case ponyTail
    case rapunzel
    case short
    case stylish
    case thick
    case topKnot
  }

  public enum Head: String, CaseIterable, Sendable {
    case standard
  }

  public enum Eyes: String, CaseIterable, Sendable {
    case big
    case huge
    case medium
    case oval
    case standard
  }

  public enum Body: String, CaseIterable, Sendable {
    case casual
    case shirt
    case tshirt
    case turtleneck
  }

  public enum Ears: String, CaseIterable, Sendable {
    case standard
  }

  public enum Eyebrows: String, CaseIterable, Sendable {
    case thick1
    case thick2
    case thickSad
    case thin
    case thinCurly
    case thinWide
  }

  public enum Mouth: String, CaseIterable, Sendable {
    case lips1
    case lips2
    case lipsSmile
    case `open`
    case openDimples
    case smile1
    case smile2
    case smileOpen
    case smirk
    case wideOpen
  }

  public enum FaceDetails: String, CaseIterable, Sendable {
    case blushes
    case freckles
    case `none`
  }

  public enum FaceHair: String, CaseIterable, Sendable {
    case beard
    case bigBeard
    case mustache
    case `none`
  }

  public enum Glasses: String, CaseIterable, Sendable {
    case aviator
    case harry
    case round
    case standard
    case `none`
  }
}
