// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

/// Namespace for the kyute theme's generated data.
public enum KyuteTheme {}

extension AvatuneTheme {
  /// The kyute theme, generated from @avatune/kyute-theme@2.1.1.
  public static let kyute: AvatuneTheme = AvatuneTheme(
    name: "kyute",
    style: AvatuneTheme.Style(size: 500, borderRadius: .percent(100)),
    backgroundPalette: [.hex(0xEFADC5), .hex(0xA7C7E7), .hex(0xFFF3B0), .hex(0xB8E3A5), .hex(0xC8A2C8), .hex(0xFFD2B7)],
    categories: [
      AvatuneTheme.Category(
        category: .hair,
        palette: [.hex(0x150C0C), .hex(0x865028), .hex(0xFCAC15), .hex(0xF7C870), .hex(0xE3E0D9), .hex(0xCE7230)],
        items: KyuteTheme.hairItems
      ),
      AvatuneTheme.Category(
        category: .head,
        palette: [.hex(0xFADCD1), .hex(0xF8D9CE), .hex(0xF6D7CB), .hex(0xEDC9BC), .hex(0xDEB3A3), .hex(0xC89583), .hex(0xD9A392), .hex(0xB78276), .hex(0x9C6458), .hex(0x753D39), .hex(0x5F2828), .hex(0x501F1F)],
        items: KyuteTheme.headItems
      ),
      AvatuneTheme.Category(
        category: .eyes,
        palette: [.hex(0x150C0C)],
        items: KyuteTheme.eyesItems
      ),
      AvatuneTheme.Category(
        category: .body,
        palette: [.hex(0x901A3E), .hex(0x4D8FAB), .hex(0x334B71), .hex(0x537C1E)],
        items: KyuteTheme.bodyItems
      ),
      AvatuneTheme.Category(
        category: .ears,
        palette: [.hex(0xFADCD1), .hex(0xF8D9CE), .hex(0xF6D7CB), .hex(0xEDC9BC), .hex(0xDEB3A3), .hex(0xC89583), .hex(0xD9A392), .hex(0xB78276), .hex(0x9C6458), .hex(0x753D39), .hex(0x5F2828), .hex(0x501F1F)],
        items: KyuteTheme.earsItems
      ),
      AvatuneTheme.Category(
        category: .eyebrows,
        palette: [.hex(0x150C0C)],
        items: KyuteTheme.eyebrowsItems
      ),
      AvatuneTheme.Category(
        category: .mouth,
        palette: [.hex(0x501F1F)],
        items: KyuteTheme.mouthItems
      ),
      AvatuneTheme.Category(
        category: .faceDetails,
        palette: [.hex(0xFC9D80)],
        items: KyuteTheme.faceDetailsItems
      ),
      AvatuneTheme.Category(
        category: .faceHair,
        palette: [.hex(0x150C0C)],
        items: KyuteTheme.faceHairItems
      ),
      AvatuneTheme.Category(
        category: .glasses,
        palette: [.hex(0xFF5ACD), .hex(0x29B6F6), .hex(0xFFEB3B), .hex(0x00E676), .hex(0xB388FF)],
        items: KyuteTheme.glassesItems
      )
    ],
    connectedColors: [ConnectedColor(dependent: .ears, source: .head), ConnectedColor(dependent: .faceHair, source: .hair), ConnectedColor(dependent: .eyebrows, source: .hair)],
    predictorMappings: AvatuneTheme.PredictorMappings(
      hair: ["long": ["topKnot", "thick", "bob", "long", "longThick", "longWavy", "ponyTail", "rapunzel"], "medium": ["curlyMedium", "elvis"], "short": ["short", "curly", "stylish"]],
      faceHair: ["facial_hair": ["bigBeard", "chevronMustache", "mustache"], "none": ["none"]],
      hairColor: ["black": [.hex(0x150C0C)], "blond": [.hex(0xFCAC15)], "brown": [.hex(0x865028)], "gray": [.hex(0xF7C870)]],
      skinTone: ["dark": [.hex(0x753D39), .hex(0x5F2828), .hex(0x501F1F)], "light": [.hex(0xF6D7CB), .hex(0xF8D9CE), .hex(0xFADCD1), .hex(0xEDC9BC)], "medium": [.hex(0xDEB3A3), .hex(0xC89583), .hex(0xD9A392), .hex(0xB78276), .hex(0x9C6458)]]
    )
  )
}
