// AUTO-GENERATED by scripts/generate-website-themes.ts. Do not edit by hand.
// Run `bun run generate:website-themes` (or `bun run generate`) to refresh.

export const themeNames = [
  'ashley-seo',
  'ashleyy',
  'cyberpunk',
  'fatin-verse',
  'kyute',
  'micah',
  'miniavs',
  'nevmstas',
  'orks',
  'pacovqzz',
  'pawel-olek-man',
  'pawel-olek-woman',
  'retro-cartoon',
  'toon-flat',
  'yanliu',
] as const

export type ThemeName = (typeof themeNames)[number]
