// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

extension PawelOlekWomanTheme {
  static let glassesItems: [ItemDescriptor] = [
    ItemDescriptor(
      key: "patch",
      layer: 60,
      position: ItemPosition(xAbs: 0, xRatio: 0.26, yAbs: 0, yRatio: 0.43),
      width: 202,
      height: 57,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="202" height="57" fill="none" viewBox="0 0 202 57"><path stroke="#2b2b2b" stroke-width="6" d="M7 2.936c33.343 6.981 71.5 5.5 107.5 13.5m85.5-.5-29.5-1"/><path fill="#2b2b2b" stroke="#2b2b2b" stroke-width="6" d="M173 29.936v-8.583c0-5.904-3.97-11.142-9.751-12.337-14.984-3.097-25.784-2.78-39.583 1.255C118.412 11.807 115 16.776 115 22.25v7.686c0 13.255 10.745 24 24 24h10c13.255 0 24-10.745 24-24Z"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "round",
      layer: 60,
      position: ItemPosition(xAbs: 0, xRatio: 0.2475, yAbs: 0, yRatio: 0.43),
      width: 205,
      height: 63,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="205" height="63" fill="none" viewBox="0 0 205 63"><circle cx="62.809" cy="31.5" r="28.5" stroke="#2b2b2b" stroke-width="6"/><circle cx="142.809" cy="31.5" r="28.5" stroke="#2b2b2b" stroke-width="6"/><path stroke="#2b2b2b" stroke-width="6" d="M89.309 31c11.268-4.238 17.097-3.755 27 0M171.309 27l32-16M34.309 27l-33-16"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "square",
      layer: 60,
      position: ItemPosition(xAbs: 0, xRatio: 0.2475, yAbs: 0, yRatio: 0.43),
      width: 204,
      height: 63,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="204" height="63" fill="none" viewBox="0 0 204 63"><path stroke="#2b2b2b" stroke-width="6" d="M.67 13c10.737-2.463 20.186-4.28 29-5.445m61 2.884c7.446 1.559 15.159 1.835 22.63.407l.371-.071m89 2.225c-10.736-2.463-20.186-4.28-29-5.445"/><path stroke="#2b2b2b" stroke-width="6" d="m28.876 38.431-3.488-20.168c-.972-5.618 2.506-11.095 8.076-12.318 20.043-4.403 33.764-3.939 52.262 1.862 4.725 1.483 7.668 6.125 7.27 11.061l-1.393 17.226C90.51 49.598 79.235 60 65.687 60H54.496c-12.65 0-23.464-9.104-25.62-21.569ZM174.465 38.431l3.488-20.168c.972-5.618-2.506-11.095-8.075-12.318-20.043-4.403-33.765-3.939-52.262 1.862-4.726 1.483-7.669 6.125-7.27 11.061l1.393 17.226C112.83 49.598 124.107 60 137.654 60h11.191c12.65 0 23.464-9.104 25.62-21.569Z"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "stylish",
      layer: 60,
      position: ItemPosition(xAbs: 0, xRatio: 0.2475, yAbs: 0, yRatio: 0.43),
      width: 204,
      height: 61,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="204" height="61" fill="none" viewBox="0 0 204 61"><path stroke="#2b2b2b" stroke-width="6" d="M.67 10C33.464 2.478 54.256.976 81.596 5.698c13.487 2.33 27.261 2.533 40.771.343 28.38-4.598 48.865-3.346 80.305 3.959"/><path stroke="#2b2b2b" stroke-width="6" d="m19.67 5 8.635 29.653a26 26 0 0 0 19.321 18.111l14.403 3.202c16.237 3.61 31.642-8.746 31.642-25.38V7.442M184.671 5l-8.614 30.403a26 26 0 0 1-19.865 18.398l-14.371 2.904c-16.103 3.254-31.15-9.056-31.15-25.485V7.442"/></svg>"##,
          ],
          slots: [],
        )
      ]
    )
  ]
}
