// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

extension PawelOlekWomanTheme {
  static let eyesItems: [ItemDescriptor] = [
    ItemDescriptor(
      key: "big",
      layer: 40,
      position: ItemPosition(xAbs: 0, xRatio: 0.35, yAbs: 0, yRatio: 0.45),
      width: 121,
      height: 40,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="121" height="40" fill="none" viewBox="0 0 121 40"><rect width="9" height="22" x="17.711" y="17.82" fill="#2b2b2b" rx="4.5"/><rect width="9" height="22" x="94.711" y="16.82" fill="#2b2b2b" rx="4.5"/><path stroke="#2b2b2b" stroke-width="3" d="M4.711 13.82c2.344-2.345 5.435-4.078 8.883-5.201m29.117 5.2c-4.914-4.914-13.108-7.145-21-6.692m-21 .693 6.5 3.5m-4.5-6.5 8 5m-4-7 6.883 5.799m0 0a30 30 0 0 1 2.617-.721M11.594.82l4.617 7.078m0 0a32 32 0 0 1 2.5-.467m-2-6.611 2 6.611m0 0c.99-.145 1.993-.247 3-.304m0-4.307v4.307M115.711 13.82c-2.344-2.345-5.434-4.078-8.882-5.201m-29.118 5.2c4.914-4.914 13.108-7.145 21-6.692m21 .693-6.5 3.5m4.5-6.5-8 5m4-7-6.882 5.799m0 0a30 30 0 0 0-2.618-.721M108.829.82l-4.618 7.078m0 0a32 32 0 0 0-2.5-.467m2-6.611-2 6.611m0 0a34 34 0 0 0-3-.304m0-4.307v4.307"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "happy",
      layer: 40,
      position: ItemPosition(xAbs: 0, xRatio: 0.35, yAbs: 0, yRatio: 0.45),
      width: 120,
      height: 36,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="120" height="36" fill="none" viewBox="0 0 120 36"><rect width="9" height="22" x="17.991" y="10.5" fill="#2b2b2b" rx="4.5"/><rect width="9" height="22" x="94.992" y="10.5" fill="#2b2b2b" rx="4.5"/><path stroke="#2b2b2b" stroke-width="3" d="M5.503 17.982c1.08-2.864 2.952-5.36 5.31-7.379m24.785-3.199c-5.521-3.268-12.75-3.092-18.85-.468m-16.403 6.5 6.309 1.492m-5.72-4.88 7.994 2.49M3.44 7.048l7.374 3.555m0 0q.876-.75 1.834-1.409M6.643 3.802l6.004 5.392m0 0a23 23 0 0 1 1.825-1.136m-3.776-5.68 3.776 5.68m0 0a24 24 0 0 1 2.275-1.122M15.32 2.872l1.428 4.064M114.12 16.982c-1.08-2.864-2.952-5.36-5.311-7.379M84.024 6.404c5.522-3.268 12.751-3.092 18.851-.468m16.402 6.5-6.308 1.492m5.719-4.88-7.994 2.49m5.489-5.49-7.374 3.555m0 0q-.876-.75-1.833-1.409m6.003-5.392-6.003 5.392m0 0a23 23 0 0 0-1.826-1.136m3.777-5.68-3.777 5.68m0 0a24 24 0 0 0-2.275-1.122m1.429-4.064-1.429 4.064"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "small",
      layer: 40,
      position: ItemPosition(xAbs: 0, xRatio: 0.35, yAbs: 0, yRatio: 0.45),
      width: 123,
      height: 37,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="123" height="37" fill="none" viewBox="0 0 123 37"><rect width="9" height="14" x="18.711" y="18.82" fill="#2b2b2b" rx="4.5"/><rect width="9" height="14" x="95.711" y="18.82" fill="#2b2b2b" rx="4.5"/><path stroke="#2b2b2b" stroke-width="3" d="M4.711 13.82c2.344-2.345 5.435-4.078 8.883-5.201m29.117 5.2c-4.914-4.914-13.108-7.145-21-6.692m-21 .693 6.5 3.5m-4.5-6.5 8 5m-4-7 6.883 5.799m0 0a30 30 0 0 1 2.617-.721M11.594.82l4.617 7.078m0 0a32 32 0 0 1 2.5-.467m-2-6.611 2 6.611m0 0c.99-.145 1.993-.247 3-.304m0-4.307v4.307M117.711 13.82c-2.344-2.345-5.434-4.078-8.882-5.201m-29.118 5.2c4.914-4.914 13.108-7.145 21-6.692m21 .693-6.5 3.5m4.5-6.5-8 5m4-7-6.882 5.799m0 0a30 30 0 0 0-2.618-.721M110.829.82l-4.618 7.078m0 0a32 32 0 0 0-2.5-.467m2-6.611-2 6.611m0 0a34 34 0 0 0-3-.304m0-4.307v4.307"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "standard",
      layer: 40,
      position: ItemPosition(xAbs: 0, xRatio: 0.35, yAbs: 0, yRatio: 0.45),
      width: 121,
      height: 36,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="121" height="36" fill="none" viewBox="0 0 121 36"><path fill="#2b2b2b" d="M16.711 12h9v6.5a4.5 4.5 0 1 1-9 0zM93.711 12h9v6.5a4.5 4.5 0 0 1-9 0z"/><path stroke="#2b2b2b" stroke-width="3" d="M4.711 19c2.344-2.344 5.435-4.078 8.883-5.2M42.71 19c-4.914-4.914-13.108-7.145-21-6.693M.711 13l6.5 3.5m-4.5-6.5 8 5m-4-7 6.883 5.8m0 0a30 30 0 0 1 2.617-.722M11.594 6l4.617 7.078m0 0a32 32 0 0 1 2.5-.466m-2-6.612 2 6.612m0 0c.99-.146 1.993-.247 3-.305m0-4.307v4.307M115.711 19c-2.344-2.344-5.434-4.078-8.882-5.2M77.711 19c4.914-4.914 13.108-7.145 21-6.693m21 .693-6.5 3.5m4.5-6.5-8 5m4-7-6.882 5.8m0 0a30 30 0 0 0-2.618-.722M108.829 6l-4.618 7.078m0 0a32 32 0 0 0-2.5-.466m2-6.612-2 6.612m0 0a34 34 0 0 0-3-.305m0-4.307v4.307"/></svg>"##,
          ],
          slots: [],
        )
      ]
    )
  ]
}
