// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

extension PawelOlekWomanTheme {
  static let mouthItems: [ItemDescriptor] = [
    ItemDescriptor(
      key: "chin",
      layer: 50,
      position: ItemPosition(xAbs: 0, xRatio: 0.435, yAbs: 0, yRatio: 0.67),
      width: 50,
      height: 19,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="50" height="19" fill="none" viewBox="0 0 50 19"><path stroke="#2b2b2b" stroke-width="6" d="M48.606 6c-5.684-1.042-9.137-2.147-14.569-2.919-3.085-.438-6.275 1.021-9.431 1.023-3.245.002-6.453-1.442-9.474-1.023C9.182 3.907 5.658 4.958.606 6"/><path stroke="#2b2b2b" stroke-width="3" d="M34.606 13c-6.05 5.851-17.05 4.787-22 0"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "philtrum1",
      layer: 50,
      position: ItemPosition(xAbs: 0, xRatio: 0.435, yAbs: 0, yRatio: 0.67),
      width: 49,
      height: 30,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="49" height="30" fill="none" viewBox="0 0 49 30"><path stroke="#2b2b2b" stroke-width="6" d="m47.12 18.285-12.091-6.062c-1.197-.6-2.582-.692-3.865-.31-2.027.6-5.132 1.418-7.044 1.419-1.888.001-4.476-.754-6.22-1.347-1.23-.419-2.575-.428-3.782.057L1.12 17.273"/><path stroke="#2b2b2b" stroke-width="3" d="M42.12 21.285c-10.175 10.241-28.675 8.38-37 0m13.214-20 3.236 1.948a5 5 0 0 0 5.157 0l3.236-1.948"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "philtrum2",
      layer: 50,
      position: ItemPosition(xAbs: 0, xRatio: 0.435, yAbs: 0, yRatio: 0.67),
      width: 55,
      height: 34,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="55" height="34" fill="none" viewBox="0 0 55 34"><path stroke="#2b2b2b" stroke-width="6" d="M53.249 20.493 39.53 12.67c-1.306-.745-2.875-.858-4.3-.377-2.29.774-5.815 1.83-7.981 1.832-2.143.001-5.085-.977-7.055-1.741-1.365-.53-2.892-.54-4.223.07L1.25 19.191"/><path stroke="#2b2b2b" stroke-width="3" d="M47.249 23.813c-11.276 12.7-31.775 10.39-41 0M20.89 1.493l5.964.574a5 5 0 0 0 .958 0l5.964-.574"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "sad",
      layer: 50,
      position: ItemPosition(xAbs: 0, xRatio: 0.435, yAbs: 0, yRatio: 0.67),
      width: 43,
      height: 13,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="43" height="13" fill="none" viewBox="0 0 43 13"><path stroke="#2b2b2b" stroke-width="6" d="M41 10.25c-10.529-9.212-30.383-7.474-38 0"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "small",
      layer: 50,
      position: ItemPosition(xAbs: 0, xRatio: 0.435, yAbs: 0, yRatio: 0.67),
      width: 43,
      height: 13,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="43" height="13" fill="none" viewBox="0 0 43 13"><path stroke="#2b2b2b" stroke-width="6" d="M29 6.17H13"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "smile",
      layer: 50,
      position: ItemPosition(xAbs: 0, xRatio: 0.435, yAbs: 0, yRatio: 0.67),
      width: 43,
      height: 13,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="43" height="13" fill="none" viewBox="0 0 43 13"><path stroke="#2b2b2b" stroke-width="6" d="M40.5 2.375c-9 9-29 9-38 0"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "tongue1",
      layer: 50,
      position: ItemPosition(xAbs: 0, xRatio: 0.435, yAbs: 0, yRatio: 0.67),
      width: 44,
      height: 34,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="44" height="34" fill="none" viewBox="0 0 44 34"><path stroke="#2b2b2b" stroke-width="6" d="M43 6c-4.974-1.043-7.994-2.147-12.747-2.919-2.7-.438-5.492 1.021-8.253 1.023-2.839.002-5.646-1.442-8.29-1.023C8.505 3.907 5.422 4.957 1 6"/><path fill=""##,
            ##"" stroke="#2b2b2b" d="M5 17V5.581L16.5 3.5l5 .5 7-1L38 5v12c0 8.837-7.163 16-16 16h-1c-8.837 0-16-7.163-16-16Z"/><path stroke="#2b2b2b" d="M22 3v21"/></svg>"##,
          ],
          slots: [.themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "tongue2",
      layer: 50,
      position: ItemPosition(xAbs: 0, xRatio: 0.435, yAbs: 0, yRatio: 0.67),
      width: 43,
      height: 29,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="43" height="29" fill="none" viewBox="0 0 43 29"><path stroke="#2b2b2b" stroke-width="6" d="M41 3.976c-10.529 9.212-30.383 7.474-38 0"/><path stroke="#2b2b2b" stroke-width="3" d="m8.5 8 1.7 9.962c.996 5.827 6.514 9.752 12.345 8.78 5.795-.965 9.737-6.411 8.843-12.218L31 12M19 9l2 10.5"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "vampire",
      layer: 50,
      position: ItemPosition(xAbs: 0, xRatio: 0.435, yAbs: 0, yRatio: 0.67),
      width: 55,
      height: 23,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="55" height="23" fill="none" viewBox="0 0 55 23"><path stroke="#2b2b2b" stroke-width="6" d="M53.067 8.998C46.91 6.915 43.17 4.706 37.285 3.163c-3.343-.877-6.799 2.042-10.218 2.045-3.515.004-6.99-2.884-10.263-2.045C10.358 4.815 6.541 6.915 1.067 8.998"/><path stroke="#2b2b2b" stroke-width="3" d="M36.067 12.998c-2.365 4.13-15.913 3.87-18 0M8.067 4.998l2.257 15.044c.162 1.081 1.694 1.155 1.959.094l3.784-15.138M45.067 4.998l-2.256 15.044c-.163 1.081-1.694 1.155-1.96.094L37.068 4.998"/></svg>"##,
          ],
          slots: [],
        )
      ]
    )
  ]
}
