// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

extension PawelOlekWomanTheme {
  static let headItems: [ItemDescriptor] = [
    ItemDescriptor(
      key: "chin",
      layer: 10,
      position: ItemPosition(xAbs: 0, xRatio: 0.26, yAbs: 0, yRatio: 0.18),
      width: 186,
      height: 275,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="186" height="275" fill="none" viewBox="0 0 186 275"><path fill=""#,
            ##"" stroke="#2b2b2b" stroke-width="6" d="M93 3C41.638 3 4 44.638 4 96l4 88c0 35.567 21.966 53.471 51.301 69.115C70.244 264.741 75.774 272 93 272s23.756-7.259 34.699-18.885C157.034 237.471 177 219.567 177 184l6-88c0-51.362-38.638-93-90-93Z"/></svg>"##,
          ],
          slots: [.themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "standard",
      layer: 10,
      position: ItemPosition(xAbs: 0, xRatio: 0.26, yAbs: 0, yRatio: 0.18),
      width: 186,
      height: 270,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="186" height="270" fill="none" viewBox="0 0 186 270"><path fill=""#,
            ##"" stroke="#2b2b2b" stroke-width="6" d="M4.565 95.712C2.081 45.263 42.315 3 92.825 3c50.641 0 90.923 42.475 88.241 93.045l-4.091 77.142a113.5 113.5 0 0 1-20.741 59.621l-1.428 2.015a76.293 76.293 0 0 1-124.6-.157l-1.318-1.869a113 113 0 0 1-20.504-59.544z"/></svg>"##,
          ],
          slots: [.themeColor],
        )
      ]
    )
  ]
}
