// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

extension PawelOlekWomanTheme {
  static let faceDetailsItems: [ItemDescriptor] = [
    ItemDescriptor(
      key: "chinDimple1",
      layer: 40,
      position: ItemPosition(xAbs: 0, xRatio: 0.26, yAbs: 0, yRatio: 0.6),
      width: 185,
      height: 104,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="185" height="104" fill="none" viewBox="0 0 185 104"><path stroke="#2b2b2b" stroke-width="3" d="M79 81c6.395-6.667 20.605-6.667 27 0M92.5 90v-9"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "chinDimple2",
      layer: 40,
      position: ItemPosition(xAbs: 0, xRatio: 0.26, yAbs: 0, yRatio: 0.6),
      width: 185,
      height: 104,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="185" height="104" fill="none" viewBox="0 0 185 104"><ellipse cx="92.5" cy="77.5" stroke="#2b2b2b" stroke-width="3" rx="8.5" ry="4.5"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "chinDimple3",
      layer: 40,
      position: ItemPosition(xAbs: 0, xRatio: 0.26, yAbs: 0, yRatio: 0.6),
      width: 185,
      height: 104,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="185" height="104" fill="none" viewBox="0 0 185 104"><path stroke="#2b2b2b" stroke-width="3" d="M92.5 90v-9"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "chinDimple4",
      layer: 40,
      position: ItemPosition(xAbs: 0, xRatio: 0.26, yAbs: 0, yRatio: 0.6),
      width: 185,
      height: 104,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="185" height="104" fill="none" viewBox="0 0 185 104"><path stroke="#2b2b2b" stroke-width="3" d="M84 81.5c4.026-6.667 12.974-6.667 17 0"/></svg>"##,
          ],
          slots: [],
        )
      ]
    )
  ]
}
