// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

extension PawelOlekWomanTheme {
  static let earsItems: [ItemDescriptor] = [
    ItemDescriptor(
      key: "dropEarrings",
      layer: 40,
      position: ItemPosition(xAbs: 0, xRatio: 0.17, yAbs: 0, yRatio: 0.45),
      width: 256,
      height: 88,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="256" height="88" fill="none" viewBox="0 0 256 88"><path fill="#bcbcbc" stroke="#2b2b2b" stroke-width="6" d="M217.166 6.657c11.787-3.128 23.207 6.124 22.593 18.304l-.082 1.63a27 27 0 0 1-20.042 24.738l-6.321 1.677 2.315-45.942z"/><circle cx="222" cy="79" r="9" fill="#2b2b2b"/><path fill="#bcbcbc" stroke="#2b2b2b" stroke-width="6" d="M38.736 6.81C26.998 3.505 15.44 12.583 15.87 24.77l.057 1.632A27 27 0 0 0 35.593 51.44l6.295 1.772L40.268 7.24z"/><path stroke="#2b2b2b" stroke-width="3" d="m234.629 14.343-1.155.15a12 12 0 0 0-10.435 11.296l-.78 15.466"/><path stroke="#2b2b2b" stroke-width="3" d="M223.127 24.03c4.869-.373 7.209.227 10.899 2.298M21.557 14.237l1.154.168a12 12 0 0 1 10.263 11.452l.546 15.475"/><path stroke="#2b2b2b" stroke-width="3" d="M32.912 24.097c-4.863-.447-7.211.117-10.932 2.133"/><circle cx="33" cy="79" r="9" fill="#2b2b2b"/><path stroke="#2b2b2b" stroke-width="3" d="M222 51v22M33 51v22"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "sharp",
      layer: 40,
      position: ItemPosition(xAbs: 0, xRatio: 0.17, yAbs: 0, yRatio: 0.45),
      width: 256,
      height: 58,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="256" height="58" fill="none" viewBox="0 0 256 58"><path fill="#bcbcbc" stroke="#2b2b2b" stroke-width="6" d="M230.75 3.353c5.239-1.39 10.314 2.722 10.042 8.135L240.02 26.8a27 27 0 0 1-20.042 24.738l-6.321 1.678 2.315-45.942zM25.605 3.307c-5.217-1.47-10.354 2.566-10.163 7.982l.54 15.322A27 27 0 0 0 35.65 51.65l6.295 1.772L40.322 7.45z"/><path stroke="#2b2b2b" stroke-width="3" d="m234.629 14.553-1.155.15A12 12 0 0 0 223.039 26l-.78 15.465"/><path stroke="#2b2b2b" stroke-width="3" d="M223.127 24.24c4.869-.373 7.209.226 10.899 2.298M21.557 14.447l1.154.168a12 12 0 0 1 10.263 11.451l.546 15.476"/><path stroke="#2b2b2b" stroke-width="3" d="M32.912 24.307c-4.863-.447-7.211.117-10.932 2.132"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "standard",
      layer: 40,
      position: ItemPosition(xAbs: 0, xRatio: 0.17, yAbs: 0, yRatio: 0.45),
      width: 256,
      height: 58,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="256" height="58" fill="none" viewBox="0 0 256 58"><path fill="#bcbcbc" stroke="#2b2b2b" stroke-width="6" d="M217.509 6.657c11.787-3.128 23.207 6.124 22.593 18.304l-.082 1.63a27 27 0 0 1-20.042 24.738l-6.321 1.677 2.315-45.942zM38.792 6.81c-11.739-3.305-23.297 5.773-22.867 17.96l.058 1.632A27 27 0 0 0 35.649 51.44l6.295 1.772L40.322 7.24z"/><path stroke="#2b2b2b" stroke-width="3" d="m234.629 14.343-1.155.15a12 12 0 0 0-10.435 11.296l-.78 15.466"/><path stroke="#2b2b2b" stroke-width="3" d="M223.127 24.03c4.869-.373 7.209.227 10.899 2.298M21.557 14.237l1.154.168a12 12 0 0 1 10.263 11.452l.546 15.475"/><path stroke="#2b2b2b" stroke-width="3" d="M32.912 24.097c-4.863-.447-7.211.117-10.932 2.133"/></svg>"##,
          ],
          slots: [],
        )
      ]
    )
  ]
}
