// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

extension PawelOlekWomanTheme {
  static let noseItems: [ItemDescriptor] = [
    ItemDescriptor(
      key: "big",
      layer: 50,
      position: ItemPosition(xAbs: 0, xRatio: 0.46, yAbs: 0, yRatio: 0.49),
      width: 28,
      height: 54,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="28" height="54" fill="none" viewBox="0 0 28 54"><path stroke="#2b2b2b" stroke-width="3" d="m17 .341 6 25.67s2.128 8.08 2.8 17.616c.245 3.492-1.126 7.194-4.472 8.225C15.181 53.744 7.248 51.065 1 47.69"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "small",
      layer: 50,
      position: ItemPosition(xAbs: 0, xRatio: 0.46, yAbs: 0, yRatio: 0.49),
      width: 26,
      height: 55,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="26" height="55" fill="none" viewBox="0 0 26 55"><path stroke="#2b2b2b" stroke-width="3" d="m23.345 29 .498 15.033c.102 3.051-.736 6.32-3.444 7.727C15.408 54.352 8.752 52.88 5 47.35"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "standard",
      layer: 50,
      position: ItemPosition(xAbs: 0, xRatio: 0.46, yAbs: 0, yRatio: 0.49),
      width: 26,
      height: 54,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="26" height="54" fill="none" viewBox="0 0 26 54"><path stroke="#2b2b2b" stroke-width="3" d="M24.04 8v35.46c0 3.861-1.708 7.946-5.537 8.433-5.847.745-12.834-2.5-17.464-6.947"/></svg>"##,
          ],
          slots: [],
        )
      ]
    )
  ]
}
