// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

/// Namespace for the pacovqzz theme's generated data.
public enum PacovqzzTheme {}

extension AvatuneTheme {
  /// The pacovqzz theme, generated from @avatune/pacovqzz-theme@2.1.1.
  public static let pacovqzz: AvatuneTheme = AvatuneTheme(
    name: "pacovqzz",
    style: AvatuneTheme.Style(size: 260, borderRadius: .percent(100)),
    backgroundPalette: [.hex(0xFD8575), .hex(0xE7B431), .hex(0x79ACE9), .hex(0xF4A464)],
    categories: [
      AvatuneTheme.Category(
        category: .hair,
        palette: [.hex(0x1A4730), .hex(0xE7B431), .hex(0x3A486B), .hex(0xDAB797)],
        items: PacovqzzTheme.hairItems
      ),
      AvatuneTheme.Category(
        category: .head,
        palette: [.hex(0xF5C09B), .hex(0xFDDCBC), .hex(0xDBA472), .hex(0x8C5A4A), .hex(0x734524), .hex(0x79ACE9)],
        items: PacovqzzTheme.headItems
      ),
      AvatuneTheme.Category(
        category: .body,
        palette: [.hex(0x273D32), .hex(0x1C2845), .hex(0xAEA08B), .hex(0x31333A)],
        items: PacovqzzTheme.bodyItems
      ),
      AvatuneTheme.Category(
        category: .eyes,
        palette: [.hex(0x000000)],
        items: PacovqzzTheme.eyesItems
      ),
      AvatuneTheme.Category(
        category: .mouth,
        palette: [.hex(0x000000)],
        items: PacovqzzTheme.mouthItems
      )
    ],
    connectedColors: [],
    predictorMappings: AvatuneTheme.PredictorMappings(
      hair: ["long": ["long", "longBeanie"], "medium": ["medium", "mediumCap", "curly", "curlyBandana"], "short": ["short", "mohawk"]],
      hairColor: ["black": [.hex(0x3A486B)], "blond": [.hex(0xE7B431)], "brown": [.hex(0xDAB797)], "gray": [.hex(0x1A4730)]],
      skinTone: ["dark": [.hex(0x734524), .hex(0x8C5A4A)], "light": [.hex(0xF5C09B), .hex(0xFDDCBC), .hex(0x79ACE9)], "medium": [.hex(0xDBA472)]]
    )
  )
}
