// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

/// Item identifiers for the pacovqzz theme.
public enum Pacovqzz {
  public enum Hair: String, CaseIterable, Sendable {
    case curly
    case curlyBandana
    case long
    case longBeanie
    case medium
    case mediumCap
    case mohawk
    case short
  }

  public enum Head: String, CaseIterable, Sendable {
    case standard
  }

  public enum Body: String, CaseIterable, Sendable {
    case hoodie
    case overall
    case overshirt1
    case overshirt2
    case pufferJacket
    case tshirt1
    case tshirt2
  }

  public enum Eyes: String, CaseIterable, Sendable {
    case apathetic
    case glasses
    case heartSunglasses
    case matrixSunglasses
    case opened
    case roundSunglasses
    case standard
  }

  public enum Mouth: String, CaseIterable, Sendable {
    case apathetic
    case beard
    case bristle1
    case bristle2
    case confused
    case happy
    case meh
    case mustache
  }
}
