// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

/// Namespace for the retro-cartoon theme's generated data.
public enum RetroCartoonTheme {}

extension AvatuneTheme {
  /// The retro-cartoon theme, generated from @avatune/retro-cartoon-theme@1.1.1.
  public static let retroCartoon: AvatuneTheme = AvatuneTheme(
    name: "retro-cartoon",
    style: AvatuneTheme.Style(size: 560, borderRadius: .percent(50)),
    backgroundPalette: [.hex(0xD09090), .hex(0x9EBDC7), .hex(0xCEBE9C)],
    categories: [
      AvatuneTheme.Category(
        category: .body,
        palette: [.hex(0x2E5E70), .hex(0x39604F), .hex(0x7D5454)],
        items: RetroCartoonTheme.bodyItems
      ),
      AvatuneTheme.Category(
        category: .eyebrows,
        palette: [.hex(0x000000)],
        items: RetroCartoonTheme.eyebrowsItems
      ),
      AvatuneTheme.Category(
        category: .eyes,
        palette: [.hex(0x45271B), .hex(0x556477), .hex(0x3D6C4F)],
        items: RetroCartoonTheme.eyesItems
      ),
      AvatuneTheme.Category(
        category: .hair,
        palette: [.hex(0x33231C), .hex(0xDFD4AF), .hex(0xD06925), .hex(0x915F36)],
        items: RetroCartoonTheme.hairItems
      ),
      AvatuneTheme.Category(
        category: .head,
        palette: [.hex(0x000000)],
        items: RetroCartoonTheme.headItems
      ),
      AvatuneTheme.Category(
        category: .mouth,
        palette: [.hex(0x000000)],
        items: RetroCartoonTheme.mouthItems
      ),
      AvatuneTheme.Category(
        category: .nose,
        palette: [.hex(0x000000)],
        items: RetroCartoonTheme.noseItems
      )
    ],
    connectedColors: [],
    predictorMappings: AvatuneTheme.PredictorMappings(
      hair: ["long": ["longCurly", "longWavy", "longStraight"], "medium": ["bob", "curlyBob"], "short": ["afro", "sideSwept", "buzzCut"]],
      hairColor: ["black": [.hex(0x33231C)], "blond": [.hex(0xDFD4AF)], "brown": [.hex(0x915F36)], "gray": [.hex(0xDFD4AF)]]
    )
  )
}
