// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

/// Item identifiers for the retro-cartoon theme.
public enum RetroCartoon {
  public enum Body: String, CaseIterable, Sendable {
    case crewneckSweater
    case collaredShirt
    case hoodie
    case turtleneckSweater
    case blazer
    case vNeckSweater
  }

  public enum Eyebrows: String, CaseIterable, Sendable {
    case soft
    case thick
    case angled
    case flat
    case raised
  }

  public enum Eyes: String, CaseIterable, Sendable {
    case neutral
    case happy
    case winking
    case surprised
    case sleepy
  }

  public enum Hair: String, CaseIterable, Sendable {
    case curlyBob
    case longWavy
    case longStraight
    case longCurly
    case bob
    case sideSwept
    case afro
    case buzzCut
  }

  public enum Head: String, CaseIterable, Sendable {
    case standard
  }

  public enum Mouth: String, CaseIterable, Sendable {
    case teethSmile
    case lips
    case openedSmile
    case smirk
    case neutral
    case sad
  }

  public enum Nose: String, CaseIterable, Sendable {
    case curve
  }
}
