// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

extension AshleyyTheme {
  static let eyesItems: [ItemDescriptor] = [
    ItemDescriptor(
      key: "standard",
      layer: 20,
      position: ItemPosition(xAbs: 0, xRatio: 0.514, yAbs: 0, yRatio: 0.416),
      width: 63,
      height: 20,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="63" height="20" fill="none" viewBox="0 0 63 20"><path fill=""#,
            ##"" d="M12.31 19.682c3.115 0 5.64-3.447 5.64-7.7 0-4.252-2.525-7.7-5.64-7.7s-5.64 3.448-5.64 7.7 2.525 7.7 5.64 7.7"/><path stroke="#050504" stroke-linecap="round" stroke-width="3" d="M16.02 9.202c-1.51-5.72-9.06-6.61-14.52-1.85"/><path fill=""##,
            ##"" d="M56.43 16.902c3.115 0 5.64-3.447 5.64-7.7 0-4.252-2.525-7.7-5.64-7.7s-5.64 3.448-5.64 7.7 2.525 7.7 5.64 7.7"/><path stroke="#050504" stroke-linecap="round" stroke-width="3" d="M60.14 6.422c-1.51-5.72-9.06-6.61-14.52-1.85"/></svg>"##,
          ],
          slots: [.themeColor, .themeColor],
        )
      ]
    )
  ]
}
