// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

extension AshleyyTheme {
  static let mouthItems: [ItemDescriptor] = [
    ItemDescriptor(
      key: "smile",
      layer: 32,
      position: ItemPosition(xAbs: 0, xRatio: 0.536, yAbs: 0, yRatio: 0.554),
      width: 21,
      height: 11,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="21" height="11" fill="none" viewBox="0 0 21 11"><path stroke="#050504" stroke-linecap="round" stroke-miterlimit="10" stroke-width="3" d="M1.5 1.5c2.982 6.94 13.299 8.609 18 7.821"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "standard",
      layer: 32,
      position: ItemPosition(xAbs: 0, xRatio: 0.574, yAbs: 0, yRatio: 0.55),
      width: 23,
      height: 9,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="23" height="9" fill="none" viewBox="0 0 23 9"><path stroke="#050504" stroke-linecap="round" stroke-miterlimit="10" stroke-width="3" d="M1.5 1.5c4.92 8.08 17.25 6.55 19.93 0"/></svg>"##,
          ],
          slots: [],
        )
      ]
    )
  ]
}
