// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

extension AshleyyTheme {
  static let accessoriesItems: [ItemDescriptor] = [
    ItemDescriptor(
      key: "none",
      layer: 0,
      position: ItemPosition(xAbs: 0, xRatio: 0, yAbs: 0, yRatio: 0),
      width: 0,
      height: 0,
      fragments: []
    ),
    ItemDescriptor(
      key: "earrings",
      layer: 41,
      position: ItemPosition(xAbs: 0, xRatio: 0.34, yAbs: 0, yRatio: 0.386),
      width: 147,
      height: 100,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="147" height="100" fill="none" viewBox="0 0 147 100"><path stroke="#f6bf42" stroke-linecap="round" stroke-linejoin="round" stroke-width="4" d="M9.5 51C4.109 55.194 2 62.251 2 71c0 13.255 8.283 24 18.5 24S39 84.255 39 71c0-11.007-5.712-20.283-13.5-23.113"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "mask",
      layer: 41,
      position: ItemPosition(xAbs: 0, xRatio: 0.328, yAbs: 0, yRatio: 0.386),
      width: 147,
      height: 100,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="147" height="100" fill="none" viewBox="0 0 147 100"><path fill="#050504" d="M66.72 37.93c3.23 16.77 1.59 34.46-3.71 52.84 29.9 11.35 51.39 12.69 65.23-3 16.58-19.46 17.13-32 15.29-51.54-10.27 8.45-38.87 7.48-76.81 1.7"/><path stroke="#050504" stroke-linecap="round" stroke-linejoin="round" stroke-width="4" d="M67.93 40.11c-5.79-3.33-36.06-22.27-39.31-23.42C18.4 13.07 5.8 22.05 9.76 38.37c4.58 18.83 11.53 27 17.76 32.25s37.13 18.62 37.13 18.62"/><path fill="#050504" d="M66.72 37.93c3.23 16.77 1.59 34.46-3.71 52.84 29.9 11.35 51.39 12.69 65.23-3 16.58-19.46 17.13-32 15.29-51.54-10.27 8.45-38.87 7.48-76.81 1.7" opacity=".4"/><path fill="#050504" d="M66.18 36.8a110.4 110.4 0 0 1-2.43 52.44c29.89 11.36 50.11 13.08 63.95-2.6 16.58-19.47 17.21-32.34 15.37-51.85-10.28 8.48-38.95 7.8-76.89 2.01" opacity=".4"/></svg>"##,
          ],
          slots: [],
        )
      ]
    )
  ]
}
