// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

/// Item identifiers for the yanliu theme.
public enum Yanliu {
  public enum Forelock: String, CaseIterable, Sendable {
    case bubble
    case curve
    case short
    case split
    case straight
    case underCut
  }

  public enum Hair: String, CaseIterable, Sendable {
    case braids
    case hijab
    case medium
    case puff
    case straightLong
    case straightMedium
  }

  public enum Head: String, CaseIterable, Sendable {
    case standard
  }

  public enum Body: String, CaseIterable, Sendable {
    case blouse
    case flowerCardigan
    case simpleCardigan
    case simpleOverall
    case striped
    case sweaterVest
    case sweaterWavy
    case teeBasic
    case teeButtoned
    case teePocket
    case teeRound
  }

  public enum Ears: String, CaseIterable, Sendable {
    case standard
  }

  public enum Neck: String, CaseIterable, Sendable {
    case standard
  }

  public enum Eyes: String, CaseIterable, Sendable {
    case standard
  }

  public enum Mouth: String, CaseIterable, Sendable {
    case smile
  }

  public enum Nose: String, CaseIterable, Sendable {
    case standard
  }

  public enum FaceDetails: String, CaseIterable, Sendable {
    case blushes
    case `none`
  }

  public enum FaceHair: String, CaseIterable, Sendable {
    case bigBeard
    case chevronMustache
    case mustache
    case `none`
  }

  public enum Glasses: String, CaseIterable, Sendable {
    case glass
    case `none`
  }

  public enum Hats: String, CaseIterable, Sendable {
    case beanie
    case hat
    case `none`
  }
}
