// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

/// Namespace for the yanliu theme's generated data.
public enum YanliuTheme {}

extension AvatuneTheme {
  /// The yanliu theme, generated from @avatune/yanliu-theme@3.1.1.
  public static let yanliu: AvatuneTheme = AvatuneTheme(
    name: "yanliu",
    style: AvatuneTheme.Style(size: 360, borderRadius: .percent(100)),
    backgroundPalette: [.hex(0xFFE5EC), .hex(0xE0F4FF), .hex(0xFFF9E6), .hex(0xE8F9E9), .hex(0xF3E5F5), .hex(0xFFE5D9)],
    categories: [
      AvatuneTheme.Category(
        category: .forelock,
        palette: [.hex(0x323232)],
        items: YanliuTheme.forelockItems
      ),
      AvatuneTheme.Category(
        category: .hair,
        palette: [.hex(0x323232)],
        items: YanliuTheme.hairItems
      ),
      AvatuneTheme.Category(
        category: .head,
        palette: [.hex(0x323232)],
        items: YanliuTheme.headItems
      ),
      AvatuneTheme.Category(
        category: .body,
        palette: [.hex(0x323232)],
        items: YanliuTheme.bodyItems
      ),
      AvatuneTheme.Category(
        category: .ears,
        palette: [.hex(0x323232)],
        items: YanliuTheme.earsItems
      ),
      AvatuneTheme.Category(
        category: .neck,
        palette: [.hex(0x323232)],
        items: YanliuTheme.neckItems
      ),
      AvatuneTheme.Category(
        category: .eyes,
        palette: [.hex(0x323232)],
        items: YanliuTheme.eyesItems
      ),
      AvatuneTheme.Category(
        category: .mouth,
        palette: [.hex(0x323232)],
        items: YanliuTheme.mouthItems
      ),
      AvatuneTheme.Category(
        category: .nose,
        palette: [.hex(0x323232)],
        items: YanliuTheme.noseItems
      ),
      AvatuneTheme.Category(
        category: .faceDetails,
        palette: [.hex(0xFC9D80)],
        items: YanliuTheme.faceDetailsItems
      ),
      AvatuneTheme.Category(
        category: .faceHair,
        palette: [.hex(0x323232)],
        items: YanliuTheme.faceHairItems
      ),
      AvatuneTheme.Category(
        category: .glasses,
        palette: [.hex(0x323232)],
        items: YanliuTheme.glassesItems
      ),
      AvatuneTheme.Category(
        category: .hats,
        palette: [.hex(0x323232)],
        items: YanliuTheme.hatsItems
      )
    ],
    connectedColors: [ConnectedColor(dependent: .ears, source: .head), ConnectedColor(dependent: .neck, source: .head), ConnectedColor(dependent: .hair, source: .forelock), ConnectedColor(dependent: .faceHair, source: .forelock)],
    predictorMappings: AvatuneTheme.PredictorMappings(
      hair: ["long": ["straightLong", "straightMedium", "braids", "puff"], "medium": ["medium", "straight", "curve"], "short": ["short", "underCut"]],
      faceHair: ["facial_hair": ["bigBeard", "chevronMustache", "mustache"], "none": ["none"]],
      hairColor: ["black": [.hex(0x323232)], "blond": [.hex(0x323232)], "brown": [.hex(0x323232)], "gray": [.hex(0x323232)]],
      skinTone: ["dark": [.hex(0x323232)], "light": [.hex(0x323232)], "medium": [.hex(0x323232)]]
    )
  )
}
