// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

/// A typed way to describe a pawel-olek-woman avatar.
///
/// Each method returns a copy, so calls chain the way SwiftUI modifiers do.
public struct PawelOlekWomanAvatar: AvatarSpecifying, Hashable, Sendable {
  public var configuration: AvatarConfiguration
  public var predictions: Predictions?

  public var theme: AvatuneTheme { .pawelOlekWoman }

  public init(seed: AvatuneSeed? = nil) {
    self.configuration = AvatarConfiguration(seed: seed)
  }

  public init(configuration: AvatarConfiguration, predictions: Predictions? = nil) {
    self.configuration = configuration
    self.predictions = predictions
  }

  /// Pins the ears item, optionally overriding its colour.
  public func ears(_ id: PawelOlekWoman.Ears, color: AvatuneColor? = nil) -> Self {
    var copy = self
    copy.configuration[.ears] = id.rawValue
    if let color { copy.configuration[color: .ears] = color }
    return copy
  }

  /// Pins the eyes item, optionally overriding its colour.
  public func eyes(_ id: PawelOlekWoman.Eyes, color: AvatuneColor? = nil) -> Self {
    var copy = self
    copy.configuration[.eyes] = id.rawValue
    if let color { copy.configuration[color: .eyes] = color }
    return copy
  }

  /// Pins the faceDetails item, optionally overriding its colour.
  public func faceDetails(_ id: PawelOlekWoman.FaceDetails, color: AvatuneColor? = nil) -> Self {
    var copy = self
    copy.configuration[.faceDetails] = id.rawValue
    if let color { copy.configuration[color: .faceDetails] = color }
    return copy
  }

  /// Pins the glasses item, optionally overriding its colour.
  public func glasses(_ id: PawelOlekWoman.Glasses, color: AvatuneColor? = nil) -> Self {
    var copy = self
    copy.configuration[.glasses] = id.rawValue
    if let color { copy.configuration[color: .glasses] = color }
    return copy
  }

  /// Pins the hair item, optionally overriding its colour.
  public func hair(_ id: PawelOlekWoman.Hair, color: AvatuneColor? = nil) -> Self {
    var copy = self
    copy.configuration[.hair] = id.rawValue
    if let color { copy.configuration[color: .hair] = color }
    return copy
  }

  /// Pins the head item, optionally overriding its colour.
  public func head(_ id: PawelOlekWoman.Head, color: AvatuneColor? = nil) -> Self {
    var copy = self
    copy.configuration[.head] = id.rawValue
    if let color { copy.configuration[color: .head] = color }
    return copy
  }

  /// Pins the mouth item, optionally overriding its colour.
  public func mouth(_ id: PawelOlekWoman.Mouth, color: AvatuneColor? = nil) -> Self {
    var copy = self
    copy.configuration[.mouth] = id.rawValue
    if let color { copy.configuration[color: .mouth] = color }
    return copy
  }

  /// Pins the nose item, optionally overriding its colour.
  public func nose(_ id: PawelOlekWoman.Nose, color: AvatuneColor? = nil) -> Self {
    var copy = self
    copy.configuration[.nose] = id.rawValue
    if let color { copy.configuration[color: .nose] = color }
    return copy
  }

  /// Overrides the ears colour.
  public func earsColor(_ color: AvatuneColor) -> Self {
    var copy = self
    copy.configuration[color: .ears] = color
    return copy
  }

  /// Overrides the eyes colour.
  public func eyesColor(_ color: AvatuneColor) -> Self {
    var copy = self
    copy.configuration[color: .eyes] = color
    return copy
  }

  /// Overrides the faceDetails colour.
  public func faceDetailsColor(_ color: AvatuneColor) -> Self {
    var copy = self
    copy.configuration[color: .faceDetails] = color
    return copy
  }

  /// Overrides the glasses colour.
  public func glassesColor(_ color: AvatuneColor) -> Self {
    var copy = self
    copy.configuration[color: .glasses] = color
    return copy
  }

  /// Overrides the hair colour.
  public func hairColor(_ color: AvatuneColor) -> Self {
    var copy = self
    copy.configuration[color: .hair] = color
    return copy
  }

  /// Overrides the head colour.
  public func headColor(_ color: AvatuneColor) -> Self {
    var copy = self
    copy.configuration[color: .head] = color
    return copy
  }

  /// Overrides the mouth colour.
  public func mouthColor(_ color: AvatuneColor) -> Self {
    var copy = self
    copy.configuration[color: .mouth] = color
    return copy
  }

  /// Overrides the nose colour.
  public func noseColor(_ color: AvatuneColor) -> Self {
    var copy = self
    copy.configuration[color: .nose] = color
    return copy
  }

  /// Sets the background behind the avatar.
  public func background(_ color: AvatuneColor) -> Self {
    var copy = self
    copy.configuration.backgroundColor = color
    return copy
  }

  /// Rounds the avatar's corners. Percentages resolve against the rendered size.
  public func cornerRadius(_ length: AvatuneLength) -> Self {
    var copy = self
    copy.configuration.cornerRadius = length
    return copy
  }

  /// Steers selection from predictor output. Supplying predictions replaces the
  /// seed entirely, matching the web renderers.
  public func predictions(_ predictions: Predictions) -> Self {
    var copy = self
    copy.predictions = predictions
    return copy
  }

  public func seed(_ seed: AvatuneSeed) -> Self {
    var copy = self
    copy.configuration.seed = seed
    return copy
  }
}
