// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

/// Namespace for the pawel-olek-woman theme's generated data.
public enum PawelOlekWomanTheme {}

extension AvatuneTheme {
  /// The pawel-olek-woman theme, generated from @avatune/pawel-olek-woman-theme@3.1.1.
  public static let pawelOlekWoman: AvatuneTheme = AvatuneTheme(
    name: "pawel-olek-woman",
    style: AvatuneTheme.Style(size: 400, borderColor: .hex(0x2B2B2B), borderWidth: 2, borderRadius: .percent(100)),
    backgroundPalette: [.hex(0xFFFFFF)],
    categories: [
      AvatuneTheme.Category(
        category: .ears,
        palette: [.hex(0xFFFFFF), .hex(0xBCBCBC)],
        items: PawelOlekWomanTheme.earsItems
      ),
      AvatuneTheme.Category(
        category: .eyes,
        palette: [.hex(0x2B2B2B)],
        items: PawelOlekWomanTheme.eyesItems
      ),
      AvatuneTheme.Category(
        category: .faceDetails,
        palette: [.hex(0x2B2B2B)],
        items: PawelOlekWomanTheme.faceDetailsItems
      ),
      AvatuneTheme.Category(
        category: .glasses,
        palette: [.hex(0x2B2B2B)],
        items: PawelOlekWomanTheme.glassesItems
      ),
      AvatuneTheme.Category(
        category: .hair,
        palette: [.hex(0x2B2B2B)],
        items: PawelOlekWomanTheme.hairItems
      ),
      AvatuneTheme.Category(
        category: .head,
        palette: [.hex(0xFFFFFF), .hex(0xBCBCBC)],
        items: PawelOlekWomanTheme.headItems
      ),
      AvatuneTheme.Category(
        category: .mouth,
        palette: [.hex(0x2B2B2B)],
        items: PawelOlekWomanTheme.mouthItems
      ),
      AvatuneTheme.Category(
        category: .nose,
        palette: [.hex(0x2B2B2B)],
        items: PawelOlekWomanTheme.noseItems
      )
    ],
    connectedColors: [],
    predictorMappings: AvatuneTheme.PredictorMappings(
      hair: ["long": ["long", "lowBun", "stickBun"], "medium": ["medium"], "short": ["bob"]]
    )
  )
}
