// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

/// Item identifiers for the pawel-olek-woman theme.
public enum PawelOlekWoman {
  public enum Ears: String, CaseIterable, Sendable {
    case dropEarrings
    case sharp
    case standard
  }

  public enum Eyes: String, CaseIterable, Sendable {
    case big
    case happy
    case small
    case standard
  }

  public enum FaceDetails: String, CaseIterable, Sendable {
    case chinDimple1
    case chinDimple2
    case chinDimple3
    case chinDimple4
  }

  public enum Glasses: String, CaseIterable, Sendable {
    case patch
    case round
    case square
    case stylish
  }

  public enum Hair: String, CaseIterable, Sendable {
    case bob
    case long
    case lowBun
    case medium
    case stickBun
    case hijab
  }

  public enum Head: String, CaseIterable, Sendable {
    case chin
    case standard
  }

  public enum Mouth: String, CaseIterable, Sendable {
    case chin
    case philtrum1
    case philtrum2
    case sad
    case small
    case smile
    case tongue1
    case tongue2
    case vampire
  }

  public enum Nose: String, CaseIterable, Sendable {
    case big
    case small
    case standard
  }
}
