// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

/// Item identifiers for the fatin-verse theme.
public enum FatinVerse {
  public enum Hair: String, CaseIterable, Sendable {
    case curlyPuff
    case curlyTop
    case curvedLong
    case doubleBuns
    case longBraid
    case longStraight
    case longWave
    case lowBun
    case shortCurly
    case shortFlip
    case shortMessy
    case shortWave
    case sidePonytail
    case sideSweep
    case spiky
    case tightCurls
    case volumized
  }

  public enum Head: String, CaseIterable, Sendable {
    case diamond
    case heart
    case oval
    case pear
    case round
    case square
    case thin
    case triangle
    case wide
  }

  public enum Eyes: String, CaseIterable, Sendable {
    case eyesFocused
    case eyesHappy
    case eyesNeutral
    case eyesSurprised
    case eyesWide
  }

  public enum Body: String, CaseIterable, Sendable {
    case hoodie
    case jacket
    case scarfTop
    case shirtTie
    case stripedOverall
    case suit
    case turtleneck
  }

  public enum Eyebrows: String, CaseIterable, Sendable {
    case browAngled
    case browFlat
    case browRaised
    case browSoft
    case browThick
    case browThin
  }

  public enum Mouth: String, CaseIterable, Sendable {
    case neutralLine
    case smileSmall
    case smileSoft
    case smirkLeft
    case smirkRight
    case tinyDot
  }

  public enum Nose: String, CaseIterable, Sendable {
    case noseCurve
    case noseLong
    case nosePointy
    case noseRound
    case noseSmall
    case noseSoft
  }

  public enum FaceHair: String, CaseIterable, Sendable {
    case beard
    case mustache
    case `none`
  }

  public enum Accessories: String, CaseIterable, Sendable {
    case beautyMark
    case cap
    case earpieceLeft
    case earringRight
    case headsetMic
    case mask
    case `none`
  }

  public enum Glasses: String, CaseIterable, Sendable {
    case glassesRound
    case glassesSquare
    case visorGlasses
    case `none`
  }
}
