// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

/// Namespace for the fatin-verse theme's generated data.
public enum FatinVerseTheme {}

extension AvatuneTheme {
  /// The fatin-verse theme, generated from @avatune/fatin-verse-theme@3.1.2.
  public static let fatinVerse: AvatuneTheme = AvatuneTheme(
    name: "fatin-verse",
    style: AvatuneTheme.Style(size: 350, borderRadius: .percent(100)),
    backgroundPalette: [.hex(0xB8E3A5), .hex(0xA7C7E7), .hex(0xFFF3B0), .hex(0xC8A2C8), .hex(0xEFADC5), .hex(0xFFD2B7)],
    categories: [
      AvatuneTheme.Category(
        category: .hair,
        palette: [.hex(0x000000)],
        items: FatinVerseTheme.hairItems
      ),
      AvatuneTheme.Category(
        category: .head,
        palette: [.hex(0x000000)],
        items: FatinVerseTheme.headItems
      ),
      AvatuneTheme.Category(
        category: .eyes,
        palette: [.hex(0x000000)],
        items: FatinVerseTheme.eyesItems
      ),
      AvatuneTheme.Category(
        category: .body,
        palette: [.hex(0x000000)],
        items: FatinVerseTheme.bodyItems
      ),
      AvatuneTheme.Category(
        category: .ears,
        palette: [.hex(0x000000)],
        items: FatinVerseTheme.earsItems
      ),
      AvatuneTheme.Category(
        category: .eyebrows,
        palette: [.hex(0x000000)],
        items: FatinVerseTheme.eyebrowsItems
      ),
      AvatuneTheme.Category(
        category: .mouth,
        palette: [.hex(0x000000)],
        items: FatinVerseTheme.mouthItems
      ),
      AvatuneTheme.Category(
        category: .nose,
        palette: [.hex(0x000000)],
        items: FatinVerseTheme.noseItems
      ),
      AvatuneTheme.Category(
        category: .faceHair,
        palette: [.hex(0x000000)],
        items: FatinVerseTheme.faceHairItems
      ),
      AvatuneTheme.Category(
        category: .accessories,
        palette: [.hex(0x000000)],
        items: FatinVerseTheme.accessoriesItems
      ),
      AvatuneTheme.Category(
        category: .glasses,
        palette: [.hex(0x000000)],
        items: FatinVerseTheme.glassesItems
      )
    ],
    connectedColors: [ConnectedColor(dependent: .ears, source: .head), ConnectedColor(dependent: .faceHair, source: .hair), ConnectedColor(dependent: .eyebrows, source: .hair)],
    predictorMappings: AvatuneTheme.PredictorMappings(
      hair: ["long": ["doubleBuns", "curlyPuff", "longStraight", "longWave", "longBraid", "curvedLong", "volumized"], "medium": ["lowBun", "shortWave"], "short": ["shortCurly", "shortFlip", "shortMessy", "spiky", "curlyTop", "sidePonytail", "sideSweep", "tightCurls"]],
      faceHair: ["facial_hair": ["beard", "mustache"], "none": ["none"]],
      hairColor: ["black": [.hex(0x000000)]],
      skinTone: ["dark": [.hex(0x000000)], "light": [.hex(0x000000)], "medium": [.hex(0x000000)]]
    )
  )
}
