// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

extension NevmstasTheme {
  static let eyesItems: [ItemDescriptor] = [
    ItemDescriptor(
      key: "boring",
      layer: 20,
      position: ItemPosition(xAbs: 0, xRatio: 0.3837, yAbs: 0, yRatio: 0.5761000000000001),
      width: 37.1,
      height: 12.2,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="37.1" height="12.2" fill="none" viewBox="0 0 371 122"><circle cx="310" cy="61.002" r="61" fill="#fff"/><mask id="a0" width="123" height="122" x="249" y="0" maskUnits="userSpaceOnUse"><circle cx="310" cy="61" r="61" fill="#fff"/></mask><g mask="url(#a0)"><path fill=""##,
            ##"" d="M330 61c0 11.046-8.954 20-20 20s-20-8.954-20-20 8.954-20 20-20 20 8.954 20 20"/><path fill="#e28d53" d="m403.435 59.999-186.999.663-.436-123L403-63z"/></g><circle cx="61" cy="61.002" r="61" fill="#fff"/><mask id="a1" width="123" height="122" x="0" y="0" maskUnits="userSpaceOnUse"><circle cx="61" cy="61" r="61" fill="#fff"/></mask><g mask="url(#a1)"><circle cx="61" cy="61" r="20" fill=""##,
            ##""/><path fill="#e28d53" d="m154.435 59.999-186.999.663-.436-123L154-63z"/></g></svg>"##,
          ],
          slots: [.derived([.darken(0.2)]), .derived([.darken(0.2)])],
        )
      ]
    ),
    ItemDescriptor(
      key: "dots",
      layer: 20,
      position: ItemPosition(xAbs: 0, xRatio: 0.42, yAbs: 0, yRatio: 0.5761000000000001),
      width: 25.1,
      height: 6.1,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="25.1" height="6.1" fill="none" viewBox="0 0 251 61"><rect width="32" height="61" x="219" fill="#000" rx="16"/><rect width="32" height="61" fill="#000" rx="16"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "openCircle",
      layer: 20,
      position: ItemPosition(xAbs: 0, xRatio: 0.3837, yAbs: 0, yRatio: 0.5761000000000001),
      width: 37.7,
      height: 12.2,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="37.7" height="12.2" fill="none" viewBox="0 0 377 122"><circle cx="61" cy="61" r="61" fill="#fff"/><circle cx="60.5" cy="60.5" r="17.5" fill=""##,
            ##""/><circle cx="316" cy="61" r="61" fill="#fff"/><circle cx="315.5" cy="60.5" r="17.5" fill=""##,
            #""/></svg>"#,
          ],
          slots: [.derived([.darken(0.2)]), .derived([.darken(0.2)])],
        )
      ]
    ),
    ItemDescriptor(
      key: "openRounded",
      layer: 20,
      position: ItemPosition(xAbs: 0, xRatio: 0.402, yAbs: 0, yRatio: 0.5761000000000001),
      width: 32,
      height: 13.2,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="32" height="13.2" fill="none" viewBox="0 0 320 132"><rect width="77" height="132" fill="#fff" rx="38.5"/><rect width="77" height="132" x="243" fill="#fff" rx="38.5"/><rect width="39" height="66" x="281" y="33" fill=""##,
            #"" rx="19.5"/><rect width="39" height="66" x="37" y="33" fill=""#,
            #"" rx="19.5"/></svg>"#,
          ],
          slots: [.derived([.darken(0.2)]), .derived([.darken(0.2)])],
        )
      ]
    )
  ]
}
