// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

extension NevmstasTheme {
  static let bodyItems: [ItemDescriptor] = [
    ItemDescriptor(
      key: "santa",
      layer: 10,
      position: ItemPosition(xAbs: 0, xRatio: 0.2804, yAbs: 0, yRatio: 0.807),
      width: 71,
      height: 32.8,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="71" height="32.8" fill="none" viewBox="0 0 710 328"><path fill="#dd6262" d="M546.456 0C643.474 49.008 710 149.588 710 265.707v61.5H0v-61.5C0 149.838 66.24 49.44 162.919.317c51.759 43.61 118.601 69.89 191.581 69.89C427.657 70.207 494.645 43.8 546.456 0"/><path fill=""##,
            ##"" fill-opacity=".41" d="M569 186a4.5 4.5 0 0 0-9 0h9m-411 0a4.5 4.5 0 0 0-9 0h9m406.5 0H560v141h9V186zm-411 0H149v141h9V186z"/><ellipse cx="355" cy="145" fill="#fff371" rx="42" ry="41"/><ellipse cx="355" cy="268" fill="#ffeb6a" rx="42" ry="41"/></svg>"##,
          ],
          slots: [.derived([.darken(0.2)])],
        )
      ]
    ),
    ItemDescriptor(
      key: "shirt",
      layer: 10,
      position: ItemPosition(xAbs: 0, xRatio: 0.28, yAbs: 0, yRatio: 0.8162999999999999),
      width: 71,
      height: 31.2,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="71" height="31.2" fill="none" viewBox="0 0 710 312"><path fill="#d9d9d9" d="m558.48 19.016-144.999 89.359-15 125.136 219-145.361zM158.999 23.563l144.999 89.359 15 125.136-219-145.362z"/><path fill=""##,
            #"" d="M352 191.062 581.654 4.3C659.204 57.995 710 147.597 710 249.063v61.5H0v-61.5C0 144.838 53.597 53.132 134.731 0z"/><path fill=""#,
            #"" fill-opacity=".22" d="M120 191.05a3 3 0 0 0-6 .025l3-.013zm-3 .012-3 .013.25 59.75 3-.012 3-.013-.25-59.75zm.25 59.751-3 .012.25 59.75 3-.012 3-.013-.25-59.75zM594.5 191.55a3 3 0 0 0-6 .025l3-.013zm-3 .012-3 .013.25 59.75 3-.012 3-.013-.25-59.75zm.25 59.751-3 .012.25 59.75 3-.012 3-.013-.25-59.75z"/><defs><filter id="a0" width="483.501" height="242.506" x="116.999" y=".063" color-interpolation-filters="sRGB" filterUnits="userSpaceOnUse"><feFlood flood-opacity="0" result="BackgroundImageFix"/><feColorMatrix in="SourceAlpha" result="hardAlpha" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"/><feOffset dy="21"/><feGaussianBlur stdDeviation="9"/><feComposite in2="hardAlpha" operator="out"/><feColorMatrix values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.25 0"/><feBlend in2="BackgroundImageFix" result="effect1_dropShadow_144_233"/><feBlend in="SourceGraphic" in2="effect1_dropShadow_144_233" result="shape"/></filter></defs></svg>"#,
          ],
          slots: [.themeColor, .derived([.darken(0.2)])],
        ),
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="71" height="31.2" fill="none" viewBox="0 0 710 312"><g fill="#ececec"><path d="M134.999.063 304.001 112.93l-83.149 90.639L173.5 100.563zM582.5 3.562 413.474 108.39l83.148 90.638 43.873-100.966z"/></g><defs><filter id="a0" width="483.501" height="242.506" x="116.999" y=".063" color-interpolation-filters="sRGB" filterUnits="userSpaceOnUse"><feFlood flood-opacity="0" result="BackgroundImageFix"/><feColorMatrix in="SourceAlpha" result="hardAlpha" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"/><feOffset dy="21"/><feGaussianBlur stdDeviation="9"/><feComposite in2="hardAlpha" operator="out"/><feColorMatrix values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.25 0"/><feBlend in2="BackgroundImageFix" result="effect1_dropShadow_144_233"/><feBlend in="SourceGraphic" in2="effect1_dropShadow_144_233" result="shape"/></filter></defs></svg>"##,
          ],
          slots: [],
          effects: [.dropShadow(dx: 0, dy: 21, stdDeviation: 0, color: AvatuneColor(red: 0, green: 0, blue: 0, alpha: 0.25))],
        )
      ]
    ),
    ItemDescriptor(
      key: "sweater",
      layer: 10,
      position: ItemPosition(xAbs: 0, xRatio: 0.28, yAbs: 0, yRatio: 0.8162999999999999),
      width: 71,
      height: 31.2,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="71" height="31.2" fill="none" viewBox="0 0 710 312"><path fill=""#,
            ##"" d="M305.914 216.956c26.025 33.08 76.147 33.08 102.172 0L577.396 1.737C657.339 55.072 710 146.082 710 249.394v61.5H0v-61.5C0 144.952 53.819 53.081 135.236 0z"/><path fill="#000" fill-opacity=".22" d="M119.5 191.487a3 3 0 0 0-6 .026l3-.013zm-3 .013-3 .013.25 59.75 3-.013 3-.012-.25-59.751zm.25 59.75-3 .013.25 59.75 3-.013 3-.012-.25-59.75zM594 191.987a3 3 0 0 0-6 .026l3-.013zm-3 .013-3 .013.25 59.75 3-.013 3-.012-.25-59.751zm.25 59.75-3 .013.25 59.75 3-.013 3-.012-.25-59.75z"/></svg>"##,
          ],
          slots: [.themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "tshirt",
      layer: 10,
      position: ItemPosition(xAbs: 0, xRatio: 0.3373, yAbs: 0, yRatio: 0.8162999999999999),
      width: 51.9,
      height: 31.1,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="51.9" height="31.1" fill="none" viewBox="0 0 519 311"><path fill=""#,
            #"" d="M210.312 216.956c26.024 33.08 76.147 33.08 102.171 0L481.794 1.737a299 299 0 0 1 36.967 29.122C504.43 60.54 496.397 93.832 496.397 129v181.894h-475V127c0-34.369-7.672-66.945-21.397-96.111A299 299 0 0 1 39.634 0z"/></svg>"#,
          ],
          slots: [.themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "turtleneck",
      layer: 10,
      position: ItemPosition(xAbs: 0, xRatio: 0.28, yAbs: 0, yRatio: 0.8078),
      width: 71,
      height: 32.8,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="71" height="32.8" fill="none" viewBox="0 0 710 328"><path fill=""#,
            #"" d="M546.456 0C643.474 49.008 710 149.588 710 265.707v61.5H0v-61.5C0 149.838 66.24 49.44 162.919.317c51.759 43.61 118.601 69.89 191.581 69.89C427.657 70.207 494.645 43.8 546.456 0"/><path fill=""#,
            #"" fill-opacity=".41" d="M569 186a4.5 4.5 0 0 0-9 0h9m-411 0a4.5 4.5 0 0 0-9 0h9m406.5 0H560v141h9V186zm-411 0H149v141h9V186z"/></svg>"#,
          ],
          slots: [.themeColor, .derived([.darken(0.2)])],
        )
      ]
    )
  ]
}
