// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

extension NevmstasTheme {
  static let hatsItems: [ItemDescriptor] = [
    ItemDescriptor(
      key: "santa",
      layer: 10,
      position: ItemPosition(xAbs: 0, xRatio: 0.266, yAbs: 0, yRatio: 0.2),
      width: 91.9,
      height: 49.3,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="91.9" height="49.3" fill="none" viewBox="0 0 919 493"><rect width="751.8" height="113" y="380" fill="#d8d8d8" rx="34"/><rect width="751.8" height="113" y="361" fill="#f2f2f2" rx="27"/><path fill="#c13a3a" d="M448.674 0c218.565 0 395.748 142.118 395.748 317.429 0 11.682-.788 23.216-2.321 34.571h-7.412c-59.95-114.977-212.449-196.679-391.107-196.679-176.474 0-327.423 79.717-388.866 192.477a258 258 0 0 1-1.79-30.369C52.927 142.118 230.11 0 448.675 0"/><path fill="#dd6262" d="M370.487 5C551.185 5 697.67 148.733 697.67 326.036c0 11.815-.65 23.48-1.918 34.964H45.222a319 319 0 0 1-1.918-34.964C43.304 148.733 189.789 5 370.487 5"/><ellipse cx="843.82" cy="374.5" fill="#f2f2f2" rx="75.18" ry="62.5"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "none",
      layer: 0,
      position: ItemPosition(xAbs: 0, xRatio: 0, yAbs: 0, yRatio: 0),
      width: 0,
      height: 0,
      fragments: []
    )
  ]
}
