// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

extension NevmstasTheme {
  static let mouthItems: [ItemDescriptor] = [
    ItemDescriptor(
      key: "bigSmile",
      layer: 25,
      position: ItemPosition(xAbs: 0, xRatio: 0.402, yAbs: 0, yRatio: 0.7102),
      width: 34,
      height: 14.9,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="34" height="14.9" fill="none" viewBox="0 0 340 149"><path stroke=""#,
            #"" stroke-linecap="round" stroke-width="49" d="M315.5 24.5c-104.76 98.14-235.045 129.278-291 69.549"/></svg>"#,
          ],
          slots: [.themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "flat",
      layer: 25,
      position: ItemPosition(xAbs: 0, xRatio: 0.402, yAbs: 0, yRatio: 0.7346),
      width: 30,
      height: 5,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="30" height="5" fill="none" viewBox="0 0 300 50"><path stroke=""#,
            #"" stroke-linecap="round" stroke-width="50" d="M25 25h250"/></svg>"#,
          ],
          slots: [.themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "frown",
      layer: 25,
      position: ItemPosition(xAbs: 0, xRatio: 0.423, yAbs: 0, yRatio: 0.7224),
      width: 24.5,
      height: 9.2,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="24.5" height="9.2" fill="none" viewBox="0 0 245 92"><path stroke=""#,
            #"" stroke-linecap="round" stroke-width="49" d="M24.5 63.15c57.078-52.973 144.769-51.287 195.865 3.767"/></svg>"#,
          ],
          slots: [.themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "halfOpen",
      layer: 25,
      position: ItemPosition(xAbs: 0, xRatio: 0.395, yAbs: 0, yRatio: 0.7224),
      width: 33.7,
      height: 15.3,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="33.7" height="15.3" fill="none" viewBox="0 0 337 153"><path fill="#fff" d="M336.676 0c-3.859 85.118-77.748 153-168.338 153S3.858 85.118 0 0z"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "laugh",
      layer: 25,
      position: ItemPosition(xAbs: 0, xRatio: 0.41, yAbs: 0, yRatio: 0.7224),
      width: 29.4,
      height: 11.9,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="29.4" height="11.9" fill="none" viewBox="0 0 294 119"><path fill="#9f1d39" fill-rule="evenodd" d="M235.819 0c42.627 0 76.602 38.48 46.603 68.764-30.116 30.402-79.587 50.235-135.511 50.235S41.517 99.166 11.401 68.764C-18.598 38.479 15.377 0 58.004 0z" clip-rule="evenodd"/><mask id="a0" width="294" height="119" x="0" y="0" maskUnits="userSpaceOnUse"><path fill="#fff" d="M235.819 0c42.627 0 76.602 38.48 46.603 68.764-30.116 30.402-79.587 50.235-135.51 50.235-55.924 0-105.395-19.833-135.51-50.235C-18.599 38.479 15.376 0 58.003 0z"/></mask><g mask="url(#a0)"><rect width="270" height="119" x="-84.999" y="47" fill="#fd87ff" rx="58"/></g><path fill="#f2f2f2" d="M235.818 0c14.225 0 27.487 4.286 37.729 11.122-3.836 6.594-10.977 11.027-19.156 11.027H44.765c-9.174 0-17.045-5.577-20.408-13.526C33.932 3.258 45.601 0 58.004 0z"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "smile",
      layer: 25,
      position: ItemPosition(xAbs: 0, xRatio: 0.3654, yAbs: 0, yRatio: 0.6859000000000001),
      width: 41,
      height: 18.5,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="41" height="18.5" fill="none" viewBox="0 0 410 185"><path stroke=""#,
            #"" stroke-linecap="round" stroke-width="49" d="M165.5 160.5c-77.872 0-141-60.89-141-136"/></svg>"#,
          ],
          slots: [.themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "nervous",
      layer: 25,
      position: ItemPosition(xAbs: 0, xRatio: 0.3959, yAbs: 0, yRatio: 0.7102),
      width: 33.5,
      height: 13.8,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="33.5" height="13.8" fill="none" viewBox="0 0 335 138"><rect width="322" height="124.988" x="6.5" y="6.5" fill="#f7f5f5" stroke=""##,
            ##"" stroke-width="13" rx="53.5"/><rect width="261.987" height="19.713" x="36.506" y="59.138" fill="#d9d9d9" rx="9.856"/><rect width="68.972" height="19.327" fill="#d9d9d9" rx="9.663" transform="rotate(90.09 20.839 55.828)skewX(-.004)"/><rect width="68.972" height="19.327" fill="#d9d9d9" rx="9.663" transform="rotate(90.093 38.013 73.7)skewY(-.004)"/><rect width="68.972" height="19.327" fill="#d9d9d9" rx="9.663" transform="rotate(90.09 58.764 95.151)skewX(-.004)"/><rect width="68.972" height="19.327" fill="#d9d9d9" rx="9.663" transform="rotate(90.09 80.245 115.87)skewX(-.004)"/><rect width="68.972" height="19.327" fill="#d9d9d9" rx="9.663" transform="rotate(90.09 101.726 136.588)skewX(-.004)"/><rect width="68.972" height="19.327" fill="#d9d9d9" rx="9.663" transform="rotate(90.09 122.113 158.402)skewX(-.004)"/></svg>"##,
          ],
          slots: [.themeColor],
        )
      ]
    )
  ]
}
