// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

extension NevmstasTheme {
  static let earsItems: [ItemDescriptor] = [
    ItemDescriptor(
      key: "standard",
      layer: 100,
      position: ItemPosition(xAbs: 0, xRatio: 0.258, yAbs: 0, yRatio: 0.5639),
      width: 78.1,
      height: 17.9,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="78.1" height="17.9" fill="none" viewBox="0 0 781 179"><path fill=""#,
            ##"" d="M688.054.002v178.995l.372.003C739.553 179 781 138.929 781 89.5S739.553 0 688.426 0z"/><path fill="#ff6f59" d="m688 41.228.481 98.743.22.001c30.153-.147 54.49-22.372 54.357-49.64-.133-27.267-24.685-49.253-54.838-49.106z"/><path fill=""##,
            ##"" d="M92.945.002v178.995l-.37.003C41.446 179 0 138.929 0 89.5S41.447 0 92.574 0z"/><path fill="#ff6f59" d="m93 41.228-.48 98.743-.22.001c-30.154-.147-54.49-22.372-54.358-49.64.133-27.267 24.685-49.253 54.838-49.106z"/></svg>"##,
          ],
          slots: [.derived([.darken(0.05)]), .derived([.darken(0.05)])],
        )
      ]
    )
  ]
}
