// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

extension NevmstasTheme {
  static let hairItems: [ItemDescriptor] = [
    ItemDescriptor(
      key: "bobRounded",
      layer: 5,
      position: ItemPosition(xAbs: 0, xRatio: 0.28, yAbs: 0, yRatio: 0.32),
      width: 71,
      height: 88.4,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="71" height="88.4" fill="none" viewBox="0 0 710 884"><path fill=""#,
            #"" d="M348.576.058C187.006 3.213 57 135.175 57 297.5v274c0 90.977 40.838 172.415 105.181 226.985-40.112 20.523-74.95 49.884-101.949 85.515H0V355C0 161.085 155.479 3.484 348.576.058M355 0c196.061 0 355 158.939 355 355v174c0 115.097-54.776 217.4-139.68 282.266a297 297 0 0 0-23.127-13.099C611.32 743.598 652 662.3 652 571.5v-274C652 133.278 518.938.133 354.747 0z"/><path fill=""#,
            #"" d="M355 0c196.061 0 355 158.939 355 355v30H328.487L307 278l-21.487 107h-10.852L222.5 215l-52.161 170H0v-30C0 158.939 158.939 0 355 0"/></svg>"#,
          ],
          slots: [.derived([.darken(0.1)]), .themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "bobStraight",
      layer: 5,
      position: ItemPosition(xAbs: 0, xRatio: 0.28, yAbs: 0, yRatio: 0.32),
      width: 71,
      height: 108.3,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="71" height="108.3" fill="none" viewBox="0 0 710 1083"><path fill=""#,
            #"" d="M355 0c196.061 0 355 158.939 355 355v727.5c0-121.704-73.08-226.339-177.752-272.417C604.935 755.842 652 669.168 652 571.5v-272C652 135.195 518.805 2 354.5 2S57 135.195 57 299.5v272c0 97.835 47.226 184.638 120.124 238.86C72.788 856.58 0 961.039 0 1082.5V355C0 158.939 158.939 0 355 0"/><path fill=""#,
            #"" d="M684 162C684 72.53 611.47 0 522 0H355v153c0 94.441 76.559 171 171 171h158z"/><path fill=""#,
            #"" d="M684 162C684 72.53 611.47 0 522 0H355v113c0 94.441 76.559 171 171 171h158z"/><path fill=""#,
            #"" d="M26 162C26 72.53 98.53 0 188 0h167v153c0 94.441-76.559 171-171 171H26z"/><path fill=""#,
            #"" d="M26 162C26 72.53 98.53 0 188 0h167v113c0 94.441-76.559 171-171 171H26z"/></svg>"#,
          ],
          slots: [.derived([.darken(0.1)]), .derived([.darken(0.05)]), .themeColor, .derived([.darken(0.05)]), .themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "short",
      layer: 5,
      position: ItemPosition(xAbs: 0, xRatio: 0.26780000000000004, yAbs: 0, yRatio: 0.3078),
      width: 76.6,
      height: 44.4,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="76.6" height="44.4" fill="none" viewBox="0 0 766 444"><path fill=""#,
            #"" d="M127.248 151C95.513 198.317 77 255.246 77 316.5V444H62c-11.598 0-21-9.402-21-21v-64.584C15.894 336.777 0 304.745 0 269c0-65.17 52.83-118 118-118zM648 151c65.17 0 118 52.83 118 118 0 43.262-23.282 81.087-58 101.628V423c0 11.598-9.402 21-21 21h-15V316.5c0-61.254-18.513-118.183-50.248-165.5z"/><path fill=""#,
            #"" d="M189 123.5C189 55.293 244.293 0 312.5 0H707v123.5c0 68.207-55.293 123.5-123.5 123.5h-271C244.293 247 189 191.707 189 123.5"/><ellipse cx="143" cy="128.5" fill=""#,
            #"" rx="123" ry="123.5"/><rect width="302" height="41" x="296" y="138" fill=""#,
            #"" fill-opacity=".35" rx="20.5"/></svg>"#,
          ],
          slots: [.derived([.darken(0.1)]), .themeColor, .themeColor, .themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "long",
      layer: 5,
      position: ItemPosition(xAbs: 0, xRatio: 0.07269999999999999, yAbs: 0, yRatio: 0.2834),
      width: 139.4,
      height: 71.3,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="139.4" height="71.3" fill="none" viewBox="0 0 1394 713"><path fill=""#,
            ##"" d="M1205.03 329c103.83 0 188 84.17 188 188v188h-298.28c-38.08 0-73.53-11.328-103.141-30.797.477-6.84.722-13.744.722-20.703v-274c0-17.214-1.485-34.086-4.331-50.5zM398.507 343a302 302 0 0 0-.507 17.5v274c0 14.117.983 28.005 2.885 41.598C369.985 699.27 331.596 713 290 713H0V528c0-102.173 82.827-185 185-185z"/><path fill="#eb4242" d="m397 404-37.499.001c-33.966 0-61.501-27.535-61.501-61.5s27.534-61.5 61.5-61.5L397 281zM992 441l37.5.001c33.97 0 61.5-27.535 61.5-61.5s-27.53-61.5-61.5-61.5L992 318z"/><path fill=""##,
            #"" d="M347 200C347 89.543 436.543 0 547 0h145v243c0 55.228-44.772 100-100 100H347zM1034 200C1034 89.543 944.457 0 834 0H692v243c0 55.228 44.772 100 100 100h242z"/><path stroke=""#,
            #"" stroke-linecap="round" stroke-width="16" d="M810 312c-38.457-9.755-81.721-49.069-90-94"/></svg>"#,
          ],
          slots: [.derived([.darken(0.05)]), .themeColor, .derived([.darken(0.1)])],
        )
      ]
    ),
    ItemDescriptor(
      key: "medium",
      layer: 5,
      position: ItemPosition(xAbs: 0, xRatio: 0.2751, yAbs: 0, yRatio: 0.29560000000000003),
      width: 66,
      height: 45.8,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="66" height="45.8" fill="none" viewBox="0 0 660 458"><path fill=""#,
            #"" d="M459.019 0c110.456 0 200 89.543 200 200v96H283.794l-46.036-82.178v75.164l-74.599-133.007v136.633C70.3 275.321 0 193.871 0 96V0h391.535l-.592 47.455L425.152 0z"/><rect width="470" height="51" x="52" y="86" fill=""#,
            #"" rx="25.5"/><path fill=""#,
            #"" fill-opacity=".34" d="M615 262h44v196h-44z"/></svg>"#,
          ],
          slots: [.themeColor, .derived([.darken(0.05)]), .themeColor],
        )
      ]
    )
  ]
}
