// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

extension NevmstasTheme {
  static let accessoriesItems: [ItemDescriptor] = [
    ItemDescriptor(
      key: "horns",
      layer: 200,
      position: ItemPosition(xAbs: 0, xRatio: 0.2, yAbs: 0, yRatio: 0.27),
      width: 99.1,
      height: 28.6,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="99.1" height="28.6" fill="none" viewBox="0 0 991 286"><rect width="53.042" height="261.765" x="263.253" y="165.699" fill="#6e382a" rx="26.521" transform="rotate(90.14 263.253 165.699)"/><path fill="#6e382a" d="M50.429 188.337c-.192 13.823-11.554 24.873-25.377 24.681S.18 201.465.371 187.642L2.631 25.03C2.823 11.207 14.184.157 28.007.349S52.88 11.902 52.688 25.725z"/><rect width="50.063" height="173.005" x="131.036" y="207.687" fill="#6e382a" rx="25.031" transform="rotate(-179.204 131.036 207.687)"/><rect width="50.063" height="130.909" x="207.036" y="212.595" fill="#6e382a" rx="25.031" transform="rotate(-179.204 207.036 212.595)"/><rect width="50.063" height="108.278" x="292.49" y="260.107" fill="#6e382a" rx="25.031" transform="rotate(159.02 292.49 260.107)"/><rect width="54.126" height="267.116" fill="#6e382a" rx="27.063" transform="rotate(89.9 275.304 447.087)scale(1 -1)"/><path fill="#6e382a" d="M939.068 194.256c.186 14.106 11.772 25.39 25.877 25.204 14.106-.186 25.39-11.772 25.204-25.877l-2.188-165.939c-.186-14.105-11.771-25.39-25.877-25.204s-25.39 11.772-25.204 25.878z"/><rect width="51.086" height="176.542" fill="#6e382a" rx="25.543" transform="rotate(179.245 427.694 109.795)scale(-1 1)"/><rect width="51.086" height="133.586" fill="#6e382a" rx="25.543" transform="rotate(179.245 388.899 112.017)scale(-1 1)"/><rect width="51.086" height="110.491" fill="#6e382a" rx="25.543" transform="rotate(201.021 370.8 69.465)scale(-1 1)"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "none",
      layer: 0,
      position: ItemPosition(xAbs: 0, xRatio: 0, yAbs: 0, yRatio: 0),
      width: 0,
      height: 0,
      fragments: []
    )
  ]
}
