// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

extension NevmstasTheme {
  static let eyebrowsItems: [ItemDescriptor] = [
    ItemDescriptor(
      key: "angry",
      layer: 30,
      position: ItemPosition(xAbs: 0, xRatio: 0.3532, yAbs: 0, yRatio: 0.5273),
      width: 47.1,
      height: 13,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="47.1" height="13" fill="none" viewBox="0 0 471 130"><rect width="179" height="71" x="278.236" y="62.661" fill=""#,
            #"" rx="35.5" transform="rotate(-20.491 278.236 62.661)"/><rect width="179" height="71" fill=""#,
            #"" rx="35.5" transform="rotate(20.491 -77.305 563.955)scale(-1 1)"/></svg>"#,
          ],
          slots: [.themeColor, .themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "small",
      layer: 30,
      position: ItemPosition(xAbs: 0, xRatio: 0.397, yAbs: 0, yRatio: 0.53),
      width: 32.5,
      height: 4.1,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="32.5" height="4.1" fill="none" viewBox="0 0 325 41"><g fill=""#,
            #""><rect width="100" height="34" rx="17"/><rect width="100" height="34" x="225" rx="17"/></g><defs><filter id="a0" width="325" height="41" x="0" y="0" color-interpolation-filters="sRGB" filterUnits="userSpaceOnUse"><feFlood flood-opacity="0" result="BackgroundImageFix"/><feColorMatrix in="SourceAlpha" result="hardAlpha" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"/><feOffset dy="7"/><feComposite in2="hardAlpha" operator="out"/><feColorMatrix values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0.25 0"/><feBlend in2="BackgroundImageFix" result="effect1_dropShadow_144_264"/><feBlend in="SourceGraphic" in2="effect1_dropShadow_144_264" result="shape"/></filter></defs></svg>"#,
          ],
          slots: [.themeColor],
          effects: [.dropShadow(dx: 0, dy: 7, stdDeviation: 0, color: AvatuneColor(red: 0, green: 0, blue: 0, alpha: 0.25))],
        )
      ]
    ),
    ItemDescriptor(
      key: "standard",
      layer: 30,
      position: ItemPosition(xAbs: 0, xRatio: 0.375, yAbs: 0, yRatio: 0.5273),
      width: 40.4,
      height: 7.1,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="40.4" height="7.1" fill="none" viewBox="0 0 404 71"><rect width="179" height="71" fill=""#,
            #"" rx="35.5"/><rect width="179" height="71" x="225" fill=""#,
            #"" rx="35.5"/></svg>"#,
          ],
          slots: [.themeColor, .themeColor],
        )
      ]
    )
  ]
}
