// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

extension NevmstasTheme {
  static let noseItems: [ItemDescriptor] = [
    ItemDescriptor(
      key: "big",
      layer: 15,
      position: ItemPosition(xAbs: 0, xRatio: 0.469, yAbs: 0, yRatio: 0.6249),
      width: 9.6,
      height: 13.4,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="9.6" height="13.4" fill="none" viewBox="0 0 96 134"><path fill=""#,
            #"" d="M0 48C0 21.49 21.49 0 48 0s48 21.49 48 48v38c0 26.51-21.49 48-48 48S0 112.51 0 86z"/></svg>"#,
          ],
          slots: [.themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "curve",
      layer: 15,
      position: ItemPosition(xAbs: 0, xRatio: 0.48120000000000007, yAbs: 0, yRatio: 0.6615),
      width: 5.8,
      height: 3.2,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="5.8" height="3.2" fill="none" viewBox="0 0 58 32"><path fill="#ff9c8d" d="M25.412 1.277a5 5 0 0 1 6.675 0l23.74 21.284c3.415 3.063 1.249 8.723-3.338 8.723H5.01c-4.587 0-6.753-5.66-3.338-8.723z"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "dots",
      layer: 15,
      position: ItemPosition(xAbs: 0, xRatio: 0.4751, yAbs: 0, yRatio: 0.6615),
      width: 8,
      height: 3,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="8" height="3" fill="none" viewBox="0 0 80 30"><circle cx="65.495" cy="14.505" r="14.505" fill="#ff9c8d"/><circle cx="14.505" cy="14.505" r="14.505" fill="#ff9c8d"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "halfOval",
      layer: 15,
      position: ItemPosition(xAbs: 0, xRatio: 0.4751, yAbs: 0, yRatio: 0.6615),
      width: 6.7,
      height: 2.9,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="6.7" height="2.9" fill="none" viewBox="0 0 67 29"><path fill=""#,
            #"" d="M67 29C66.955 12.977 51.974 0 33.5 0S.045 12.977 0 29z"/></svg>"#,
          ],
          slots: [.themeColor],
        )
      ]
    )
  ]
}
