// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

extension NevmstasTheme {
  static let headItems: [ItemDescriptor] = [
    ItemDescriptor(
      key: "oval",
      layer: 1,
      position: ItemPosition(xAbs: 0, xRatio: 0.28, yAbs: 0, yRatio: 0.32),
      width: 71,
      height: 112.5,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="71" height="112.5" fill="none" viewBox="0 0 710 1125"><path fill=""#,
            ##"" d="M412.5 766C576.805 766 710 899.195 710 1063.5v61.5H0v-61.5C0 899.195 133.195 766 297.5 766z"/><mask id="a0" width="710" height="359" x="0" y="766" maskUnits="userSpaceOnUse"><path fill="#fff" d="M412.5 766C576.805 766 710 899.195 710 1063.5v61.5H0v-61.5C0 899.195 133.195 766 297.5 766z"/></mask><g mask="url(#a0)"><rect width="304" height="391" x="203" y="555" fill=""##,
            #"" rx="152"/></g><rect width="595" height="869" x="57" fill=""#,
            #"" rx="297.5"/></svg>"#,
          ],
          slots: [.themeColor, .derived([.darken(0.05)]), .themeColor],
        )
      ]
    )
  ]
}
