// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

extension NevmstasTheme {
  static let faceHairItems: [ItemDescriptor] = [
    ItemDescriptor(
      key: "beard",
      layer: 10,
      position: ItemPosition(xAbs: 0, xRatio: 0.315, yAbs: 0, yRatio: 0.54),
      width: 59.5,
      height: 63.5,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="59.5" height="63.5" fill="none" viewBox="0 0 595 635"><path fill=""#,
            #"" d="M592.211 0A300 300 0 0 1 595 40.888V337.31c0 164.304-133.195 297.5-297.5 297.5S0 501.615 0 337.311V40.888q0-7.618.378-15.14C30.662 161.833 150.624 263.47 294 263.47c152.284 0 278.153-114.657 298.211-263.47"/></svg>"#,
          ],
          slots: [.themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "none",
      layer: 0,
      position: ItemPosition(xAbs: 0, xRatio: 0, yAbs: 0, yRatio: 0),
      width: 0,
      height: 0,
      fragments: []
    )
  ]
}
