// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

/// Namespace for the micah theme's generated data.
public enum MicahTheme {}

extension AvatuneTheme {
  /// The micah theme, generated from @avatune/micah-theme@3.1.1.
  public static let micah: AvatuneTheme = AvatuneTheme(
    name: "micah",
    style: AvatuneTheme.Style(size: 400, borderRadius: .percent(100)),
    backgroundPalette: [.hex(0xFFEDEF)],
    categories: [
      AvatuneTheme.Category(
        category: .hair,
        palette: [.hex(0x000000), .hex(0xFFFFFF), .hex(0x9287FF), .hex(0x6BD9E9), .hex(0xFC909F), .hex(0xF4D150)],
        items: MicahTheme.hairItems
      ),
      AvatuneTheme.Category(
        category: .head,
        palette: [.hex(0x80502E), .hex(0xC78A5C), .hex(0xFCBE93), .hex(0xFDCDAC), .hex(0xF5D0C5)],
        items: MicahTheme.headItems
      ),
      AvatuneTheme.Category(
        category: .faceHair,
        palette: [.hex(0x000000), .hex(0xFFFFFF), .hex(0x9287FF), .hex(0x6BD9E9), .hex(0xFC909F), .hex(0xF4D150)],
        items: MicahTheme.faceHairItems
      ),
      AvatuneTheme.Category(
        category: .eyes,
        palette: [.hex(0x000000)],
        items: MicahTheme.eyesItems
      ),
      AvatuneTheme.Category(
        category: .eyebrows,
        palette: [.hex(0x000000)],
        items: MicahTheme.eyebrowsItems
      ),
      AvatuneTheme.Category(
        category: .glasses,
        palette: [.hex(0x000000)],
        items: MicahTheme.glassesItems
      ),
      AvatuneTheme.Category(
        category: .mouth,
        palette: [.hex(0x000000)],
        items: MicahTheme.mouthItems
      ),
      AvatuneTheme.Category(
        category: .nose,
        palette: [.hex(0x000000)],
        items: MicahTheme.noseItems
      ),
      AvatuneTheme.Category(
        category: .ears,
        palette: [.hex(0x80502E), .hex(0xC78A5C), .hex(0xFCBE93), .hex(0xFDCDAC), .hex(0xF5D0C5)],
        items: MicahTheme.earsItems
      ),
      AvatuneTheme.Category(
        category: .accessories,
        palette: [.hex(0xF4D150)],
        items: MicahTheme.accessoriesItems
      ),
      AvatuneTheme.Category(
        category: .body,
        palette: [.hex(0x9287FF), .hex(0x6BD9E9), .hex(0xFC909F), .hex(0xF4D150)],
        items: MicahTheme.bodyItems
      )
    ],
    connectedColors: [ConnectedColor(dependent: .faceHair, source: .hair), ConnectedColor(dependent: .ears, source: .head)],
    predictorMappings: AvatuneTheme.PredictorMappings(
      hair: ["long": ["full", "dannyPhantom", "pixie"], "medium": ["fonze"], "short": ["dougFunny", "mrT", "fonze"]],
      faceHair: ["facial_hair": ["beard", "scruff"], "none": ["none"]],
      hairColor: ["black": [.hex(0x000000)], "blond": [.hex(0xF4D150)], "brown": [.hex(0x000000)], "gray": [.hex(0xFFFFFF)]],
      skinTone: ["dark": [.hex(0x80502E)], "light": [.hex(0xFCBE93)], "medium": [.hex(0xC78A5C)]]
    )
  )
}
