// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

/// Item identifiers for the micah theme.
public enum Micah {
  public enum Hair: String, CaseIterable, Sendable {
    case dannyPhantom
    case dougFunny
    case fonze
    case full
    case mrT
    case pixie
    case turban
  }

  public enum Head: String, CaseIterable, Sendable {
    case standard
  }

  public enum FaceHair: String, CaseIterable, Sendable {
    case beard
    case scruff
    case `none`
  }

  public enum Eyes: String, CaseIterable, Sendable {
    case eyeshadow
    case round
    case smiling
    case standard
  }

  public enum Eyebrows: String, CaseIterable, Sendable {
    case down
    case eyelashesDown
    case eyelashesUp
    case up
  }

  public enum Glasses: String, CaseIterable, Sendable {
    case round
    case square
    case `none`
  }

  public enum Mouth: String, CaseIterable, Sendable {
    case frown
    case laughing
    case nervous
    case pucker
    case sad
    case smile
    case smirk
    case surprised
  }

  public enum Nose: String, CaseIterable, Sendable {
    case curve
    case pointed
    case round
  }

  public enum Ears: String, CaseIterable, Sendable {
    case medium
    case small
  }

  public enum Accessories: String, CaseIterable, Sendable {
    case studEarRing
    case hoopEarRing
    case `none`
  }

  public enum Body: String, CaseIterable, Sendable {
    case collaredShirt
    case crewShirt
    case openShirt
  }
}
