// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

/// Namespace for the ashley-seo theme's generated data.
public enum AshleySeoTheme {}

extension AvatuneTheme {
  /// The ashley-seo theme, generated from @avatune/ashley-seo-theme@2.1.1.
  public static let ashleySeo: AvatuneTheme = AvatuneTheme(
    name: "ashley-seo",
    style: AvatuneTheme.Style(size: 700, borderRadius: .percent(100)),
    backgroundPalette: [.hex(0x6F6FFB), .hex(0x68DBF2), .hex(0xE4ECF7), .hex(0xFFBAF8), .hex(0xF16063), .hex(0x4C6FFF)],
    categories: [
      AvatuneTheme.Category(
        category: .hair,
        palette: [.hex(0x1B0B47), .hex(0xAD3A20), .hex(0x47280B), .hex(0x351700), .hex(0xAA5A10), .hex(0xD56C0C), .hex(0x238D81), .hex(0x272630), .hex(0x5754D2)],
        items: AshleySeoTheme.hairItems
      ),
      AvatuneTheme.Category(
        category: .head,
        palette: [.hex(0x836055), .hex(0xFFCB7E), .hex(0xF5D0C5), .hex(0xFFE4C0)],
        items: AshleySeoTheme.headItems
      ),
      AvatuneTheme.Category(
        category: .faceHair,
        palette: [.hex(0x1B0B47), .hex(0x47280B), .hex(0xAD3A20), .hex(0x351700), .hex(0xAA5A10), .hex(0xD56C0C)],
        items: AshleySeoTheme.faceHairItems
      ),
      AvatuneTheme.Category(
        category: .eyes,
        palette: [.hex(0x1B0B47), .hex(0x2A1200), .hex(0x71472D)],
        items: AshleySeoTheme.eyesItems
      ),
      AvatuneTheme.Category(
        category: .accessories,
        palette: [.hex(0x000000)],
        items: AshleySeoTheme.accessoriesItems
      ),
      AvatuneTheme.Category(
        category: .mouth,
        palette: [.hex(0xB03E67), .hex(0x873C41)],
        items: AshleySeoTheme.mouthItems
      )
    ],
    connectedColors: [ConnectedColor(dependent: .faceHair, source: .hair)],
    predictorMappings: AvatuneTheme.PredictorMappings(
      hair: ["long": ["wavyBob", "bangs", "braids", "bunHair", "curlyBob", "froBun"], "medium": ["dreads", "straightHair"], "short": ["bowlCutHair", "shortHair", "curlyShortHair", "mohawk", "shavedHead"]],
      faceHair: ["facial_hair": ["beard", "chinHair", "fuzz", "mustache"], "none": ["none"]],
      hairColor: ["black": [.hex(0x1B0B47)], "blond": [.hex(0xAD3A20)], "brown": [.hex(0x47280B)], "gray": [.hex(0xAD3A20)]],
      skinTone: ["dark": [.hex(0x836055)], "light": [.hex(0xF5D0C5)], "medium": [.hex(0xFFCB7E)]]
    )
  )
}
