// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

/// Item identifiers for the ashley-seo theme.
public enum AshleySeo {
  public enum Hair: String, CaseIterable, Sendable {
    case bangs
    case bowlCutHair
    case braids
    case bunHair
    case curlyBob
    case curlyShortHair
    case dreads
    case froBun
    case halfShavedHead
    case hijab
    case mohawk
    case shavedHead
    case shortHair
    case straightHair
    case wavyBob
  }

  public enum Head: String, CaseIterable, Sendable {
    case standart
  }

  public enum FaceHair: String, CaseIterable, Sendable {
    case beard
    case chinHair
    case fuzz
    case mustache
    case `none`
  }

  public enum Eyes: String, CaseIterable, Sendable {
    case angry
    case cherry
    case confused
    case normal
    case sad
    case sleepy
    case starstruck
    case winking
  }

  public enum Accessories: String, CaseIterable, Sendable {
    case catEars
    case clownNose
    case faceMask
    case glasses
    case mustache
    case sailormoonCrown
    case sleepMask
    case sunglasses
    case `none`
  }

  public enum Mouth: String, CaseIterable, Sendable {
    case awkwardSmile
    case braces
    case gapSmile
    case kawaii
    case openedSmile
    case openSad
    case teethSmile
    case unimpressed
  }
}
