// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

extension FatinVerseTheme {
  static let faceHairItems: [ItemDescriptor] = [
    ItemDescriptor(
      key: "beard",
      layer: 31,
      position: ItemPosition(xAbs: 0, xRatio: 0.08, yAbs: 0, yRatio: 0.03),
      width: 306,
      height: 306,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="306" height="306" fill="none" viewBox="0 0 306 306"><path fill=""#,
            #"" d="M201.1 195.725c1.5-7.9 2-15.9.7-23.8-.5-3-.7-5.005-4.3-4.505-2 .705-7.4 2.105-8.5 2.205-3.2.3-4.7.595-7-1.205-3-1.5-6.4-2.8-7-3-10.5-3.5-20.2-4.795-24.5 9.305-3.5 11.5-15.5 24.1-22 12.9-5-8.5-4.3-26.305-5-29.705-1.7-8.4-2.1-15.995-3.5-14.795 0 2.7.9 34.6 1 36.3.7 8.8 2 19.795 6 25.495s17.8 13.005 36 14.305c18.3 1.3 28.4-.2 38.6-11.9 9.2-10.6 9.5-32.6 9.5-32.6-4.5 13.3-7.6 17.7-10 21m-41.2-22.5c5.2-5.7 12.8.9 21 1.5 8.1.6 11.4-4.5 12 4.5.2 2.2.5 5.9.4 8.4v.3c-.3 2.8-1.2 5.9-4 7.6-5.9 3.7-15.4 2.8-21.5 1.6-8.5-1.7-10.3-5.6-10.7-7.4-.6-7.7.7-14.2 2.8-16.5"/></svg>"#,
          ],
          slots: [.themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "mustache",
      layer: 31,
      position: ItemPosition(xAbs: 0, xRatio: 0.08, yAbs: 0, yRatio: 0.03),
      width: 306,
      height: 306,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="306" height="306" fill="none" viewBox="0 0 306 306"><path fill=""#,
            #"" d="M193.076 172.232c-4.358.716-6.567-1.791-7.403-2.985-1.493 2.985-5.075 5.552-12.24 4.298-9.314-1.612-9.433-10.03-9.433-10.03 2.926 3.105 5.553 3.164 10.747 1.254 6.149-2.209 8.1-2.125 9.254-.971.896.896 2.09 1.791 5.373-.522 1.791-.97 3.284.94 4.18 1.716 2.985 2.747 3.343 1.389 4.418-.223 0 .059.239 6.627-4.896 7.463"/></svg>"#,
          ],
          slots: [.themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "none",
      layer: 0,
      position: ItemPosition(xAbs: 0, xRatio: 0, yAbs: 0, yRatio: 0),
      width: 0,
      height: 0,
      fragments: []
    )
  ]
}
