// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

extension FatinVerseTheme {
  static let earsItems: [ItemDescriptor] = []
}
