// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

extension FatinVerseTheme {
  static let accessoriesItems: [ItemDescriptor] = [
    ItemDescriptor(
      key: "beautyMark",
      layer: 32,
      position: ItemPosition(xAbs: 0, xRatio: 0.08, yAbs: 0, yRatio: 0.03),
      width: 306,
      height: 306,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="306" height="306" fill="none" viewBox="0 0 306 306"><circle cx="110" cy="165" r="3.5" fill="#fff" stroke=""##,
            ##""/><circle cx="110" cy="165" r="1.5" fill="#fff" stroke=""##,
            #""/></svg>"#,
          ],
          slots: [.themeColor, .themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "cap",
      layer: 32,
      position: ItemPosition(xAbs: 0, xRatio: 0.08, yAbs: 0, yRatio: 0.03),
      width: 306,
      height: 306,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="306" height="306" fill="none" viewBox="0 0 306 306"><path fill="#fff" stroke=""##,
            ##"" stroke-linejoin="round" stroke-width="6" d="M211.573 128.122c-20.607 9.9-59.865-5.225-74.431-16.09l86.567-15.52 32.9 14.751c-5.802-.478-24.43 6.959-45.036 16.859Z"/><path fill="#fff" stroke=""##,
            ##"" stroke-linejoin="round" stroke-width="6" d="M223.211 96.47c-87.524 26.544-128.131 8.508-144.91 5.119 3.355-19.962 22.284-57.907 68.828-62.058 40.938-3.65 74.307 23.68 76.082 56.94Z"/><mask id="a0" fill="#fff"><path d="M155.225 38.693c-.223 2.706-.871 3.94-3.006 4.192-2.467.29-4.275-1.064-4.052-3.77l3.529-.21z"/></mask><path fill="#fff" d="M155.225 38.693c-.223 2.706-.871 3.94-3.006 4.192-2.467.29-4.275-1.064-4.052-3.77l3.529-.21z"/><path fill=""##,
            #"" d="m155.225 38.693 5.98.493.568-6.895-6.906.413zm-3.006 4.192-.701-5.96zm-4.052-3.77-.358-5.99-5.195.311-.427 5.186zm1.079-.914c-.042.506-.089.733-.104.793-.014.055.047-.23.321-.636a3.6 3.6 0 0 1 1.283-1.154c.467-.248.793-.28.772-.278l1.401 11.918c2.248-.264 4.787-1.245 6.496-3.782 1.379-2.047 1.667-4.386 1.79-5.876zm2.272-1.275c.002 0 .041-.005.115-.001s.19.016.338.053c.304.076.735.255 1.163.628.439.384.731.852.886 1.291.147.418.128.69.127.71l-11.96-.985c-.231 2.81.579 5.86 3.048 8.018 2.351 2.056 5.278 2.487 7.684 2.204zm-2.993 8.178 3.529-.21-.716-11.98-3.529.212zm3.529-.21 3.529-.211-.716-11.98-3.529.212z" mask="url(#a0)"/></svg>"#,
          ],
          slots: [.themeColor, .themeColor, .themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "earpieceLeft",
      layer: 32,
      position: ItemPosition(xAbs: 0, xRatio: 0.08, yAbs: 0, yRatio: 0.03),
      width: 306,
      height: 306,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="306" height="306" fill="none" viewBox="0 0 306 306"><path fill=""#,
            #"" stroke=""#,
            ##"" d="M100.17 140.802c-1.076 5.563 3.214 7.678 5.493 8.04 1.345 1.304 4.484 4.324 6.277 5.976 2.242 2.064 5.156 2.933 5.941 1.412.628-1.217-1.382-3.911-2.466-5.107-1.532-1.521-4.618-4.628-4.708-4.889 1.681-4.237.112-7.171-2.13-8.474-2.242-1.304-7.398-1.304-8.407 3.042Z"/><path fill="#fff" stroke="#fff" d="M103.291 140.046c.41-.369 1.842 1.571 1.699 2.619-.179 1.31-2.861-1.571-1.699-2.619Z"/></svg>"##,
          ],
          slots: [.themeColor, .themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "earringRight",
      layer: 32,
      position: ItemPosition(xAbs: 0, xRatio: 0.08, yAbs: 0, yRatio: 0.03),
      width: 306,
      height: 306,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="306" height="306" fill="none" viewBox="0 0 306 306"><path stroke=""#,
            ##"" stroke-linejoin="round" stroke-width="6" d="M111 162v8z"/><path fill="#fff" stroke=""##,
            #"" stroke-linejoin="round" stroke-width="6" d="M108.691 176.89c-1.972-2.651.753-5.727 2.259-6.89 3.615 2.303 3.4 5.773 2.465 6.89-1.442 1.722-3.82 1.217-4.724 0Z"/></svg>"#,
          ],
          slots: [.themeColor, .themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "headsetMic",
      layer: 32,
      position: ItemPosition(xAbs: 0, xRatio: 0.08, yAbs: 0, yRatio: 0.03),
      width: 306,
      height: 306,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="306" height="306" fill="none" viewBox="0 0 306 306"><path fill="#fff" stroke=""##,
            ##"" stroke-width="6" d="M128.5 62.802c-19.5 14.084-23.667 51-23 61h-.001c-3.5 0-11.666 0-12.5-1-1-10.5 7.149-43.75 14.001-53 10-13.5 22.5-19 34-21.5 27.854-6.055 41.143 1.522 43.643 3.522-7.5-2-38.733-1.596-56.143 10.978Z"/><path fill="#fff" stroke=""##,
            ##"" stroke-width="6" d="M90.234 126.89c0-10.123 11.743-11.248 17.614-10.545s15.886 8.851 15.886 27.831-6.727 26.297-12.363 27c-14.091 0-21.137-31.633-21.137-44.286Z"/><path fill="#fff" stroke=""##,
            #"" stroke-width="6" d="M85.235 128.176c1.338-10.033 13.742-11.534 19.613-10.831 5.386 1.831 15.887 8.851 15.887 27.831s-6.728 26.297-12.364 27c-14.09 0-25.137-29-23.136-44Z"/></svg>"#,
          ],
          slots: [.themeColor, .themeColor, .themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "mask",
      layer: 32,
      position: ItemPosition(xAbs: 0, xRatio: 0.08, yAbs: 0, yRatio: 0.03),
      width: 306,
      height: 306,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="306" height="306" fill="none" viewBox="0 0 306 306"><path fill=""#,
            ##"" d="M134.5 153.8c-6-4.7-11-10.2-15.4-16.4-1.5-2-2.7-4.2-4-6.3-.2-.3-.1-.8.3-1 .3-.2.8-.1 1 .3 3.9 6.2 8.7 11.7 14.2 16.5 1.8 1.6 3.8 3.2 5.7 4.5 1.6 1.1-.1 3.6-1.8 2.4M128.5 189.8c-6-4.7-11-10.2-15.4-16.4-1.5-2-2.7-4.2-4-6.3-.2-.3-.1-.8.3-1 .3-.2.8-.1 1 .3 3.9 6.2 8.7 11.7 14.2 16.5 1.8 1.6 3.8 3.2 5.7 4.5 1.6 1.1-.1 3.6-1.8 2.4"/><path fill="#fff" stroke=""##,
            #"" stroke-linejoin="round" stroke-width="4" d="M190.809 138.013c5.302-.191 10.345 1.802 14.01 7.145q.094.135.207.254c3.744 3.898 7.328 5.454 9.26 6.734.982.651 1.58 1.223 1.983 1.987.415.788.731 1.99.731 4.075 0 4.317-1.053 13.053-3.861 22.174-2.819 9.155-7.305 18.359-13.951 23.947-6.913 5.814-15.882 11.006-25 12.904-9.049 1.885-18.144.523-25.738-6.592-4.213-3.948-7.557-6.738-10.391-9.601-2.751-2.778-4.754-5.382-6.082-8.63-2.68-6.554-2.814-16.204.706-35.984.289-.92 1.018-2.303 2.242-3.349 1.195-1.021 2.894-1.762 5.326-1.4 3.98.592 10.03.883 16.369.003 6.321-.878 13.124-2.946 18.418-7.234 4.646-3.762 10.372-6.239 15.771-6.433Z"/></svg>"#,
          ],
          slots: [.themeColor, .themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "none",
      layer: 0,
      position: ItemPosition(xAbs: 0, xRatio: 0, yAbs: 0, yRatio: 0),
      width: 0,
      height: 0,
      fragments: []
    )
  ]
}
