// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

extension FatinVerseTheme {
  static let glassesItems: [ItemDescriptor] = [
    ItemDescriptor(
      key: "glassesRound",
      layer: 33,
      position: ItemPosition(xAbs: 0, xRatio: 0.08, yAbs: 0, yRatio: 0.03),
      width: 306,
      height: 306,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="306" height="306" fill="none" viewBox="0 0 306 306"><path stroke=""#,
            #"" stroke-width="6" d="M166 122c8.134 0 15 7.009 15 16s-6.866 16-15 16-15-7.009-15-16 6.866-16 15-16ZM210 120c6.652 0 13 6.805 13 16.5s-6.348 16.5-13 16.5-13-6.805-13-16.5 6.348-16.5 13-16.5Z"/><path fill=""#,
            #"" stroke=""#,
            #"" stroke-linejoin="round" stroke-width="6" d="M181 134.35c2.5-3 10.5-5.5 16-.5 0 0-7-5.35-16 .5ZM151 132l-33 1v1.143L149 136z"/></svg>"#,
          ],
          slots: [.themeColor, .themeColor, .themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "glassesSquare",
      layer: 33,
      position: ItemPosition(xAbs: 0, xRatio: 0.08, yAbs: 0, yRatio: 0.03),
      width: 306,
      height: 306,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="306" height="306" fill="none" viewBox="0 0 306 306"><path stroke=""#,
            #"" stroke-linejoin="round" stroke-width="6" d="M152.5 119.017c-7.6-.4-9.5 6.167-9.5 9.5-1.833 6.5-2.8 20.3 8 23.5 13.5 4 28-1.5 32-5.5s3-9 3.5-16c.4-5.6-3.5-8-5.5-8.5-6.333-.833-20.9-2.6-28.5-3ZM204.5 123.517c-4.4.4-5.5 4.5-5.5 6.5-1.2 12.801 3.5 18 6 19 4 1.5 12.9 3.8 16.5 1 4.5-3.5 5-10.5 5-20 0-7.6-3.666-8.833-5.5-8.5-3.666.5-12.1 1.6-16.5 2Z"/><path fill=""#,
            #"" stroke=""#,
            #"" stroke-linejoin="round" stroke-width="4" d="M185 130.518c2.5-3 10.5-5.5 16-.5 0 0-10.5-1.5-16 .5ZM144 128l-28 .518v2l27 2.982z"/></svg>"#,
          ],
          slots: [.themeColor, .themeColor, .themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "visorGlasses",
      layer: 33,
      position: ItemPosition(xAbs: 0, xRatio: 0.08, yAbs: 0, yRatio: 0.03),
      width: 306,
      height: 306,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="306" height="306" fill="none" viewBox="0 0 306 306"><path fill=""#,
            #"" stroke=""#,
            ##"" stroke-width="2" d="M220.301 122h-81.5c1.199 22 3.236 29.179 14.7 33 5.999 2 17.8 3 27.8-8.5 8-9.2 11.699-3 14.5 0 3.699 5.5 10.584 9.43 17.699 6.5 8.5-3.5 6.801-19.5 6.801-31Z"/><path fill="#fff" stroke=""##,
            #"" stroke-width="2" d="M218.868 124H141.5c1.146 18.633 2.592 24.712 13.545 27.949 5.732 1.694 18.079 2.821 26.455-7.949 7-9 11.218-3.06 14 0 5 5.5 10.072 8.736 16.87 6.255 8.121-2.964 6.498-16.515 6.498-26.255Z"/><path fill=""#,
            #"" stroke=""#,
            #"" stroke-width="2" d="m118.5 136-5.5-9 25-5 1.5 14zM219.5 140.5 200 123h-1.5l21 19.5zM218 144.5l-14.5-14 .5 2.5 14 13.5z"/></svg>"#,
          ],
          slots: [.themeColor, .themeColor, .themeColor, .themeColor, .themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "none",
      layer: 0,
      position: ItemPosition(xAbs: 0, xRatio: 0, yAbs: 0, yRatio: 0),
      width: 0,
      height: 0,
      fragments: []
    )
  ]
}
