// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

extension FatinVerseTheme {
  static let noseItems: [ItemDescriptor] = [
    ItemDescriptor(
      key: "noseCurve",
      layer: 22,
      position: ItemPosition(xAbs: 0, xRatio: 0.08, yAbs: 0, yRatio: 0.03),
      width: 306,
      height: 306,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="306" height="306" fill="none" viewBox="0 0 306 306"><path stroke=""#,
            #"" stroke-linecap="round" stroke-linejoin="round" stroke-width="4" d="M193.573 144c5.376 9.196 12.387 25.985-2.573 19.578"/></svg>"#,
          ],
          slots: [.themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "noseLong",
      layer: 22,
      position: ItemPosition(xAbs: 0, xRatio: 0.08, yAbs: 0, yRatio: 0.03),
      width: 306,
      height: 306,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="306" height="306" fill="none" viewBox="0 0 306 306"><path stroke=""#,
            #"" stroke-linecap="round" stroke-linejoin="round" stroke-width="4" d="m191 143 4.3 10.781c4.357 3.534 9.597 10.925-4.3 12.219"/></svg>"#,
          ],
          slots: [.themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "nosePointy",
      layer: 22,
      position: ItemPosition(xAbs: 0, xRatio: 0.08, yAbs: 0, yRatio: 0.03),
      width: 306,
      height: 306,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="306" height="306" fill="none" viewBox="0 0 306 306"><path stroke=""#,
            #"" stroke-linecap="round" stroke-linejoin="round" stroke-width="4" d="M192.346 153c.939 1.586 1.584 5.007-3.346 6"/></svg>"#,
          ],
          slots: [.themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "noseRound",
      layer: 22,
      position: ItemPosition(xAbs: 0, xRatio: 0.08, yAbs: 0, yRatio: 0.03),
      width: 306,
      height: 306,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="306" height="306" fill="none" viewBox="0 0 306 306"><path stroke=""#,
            #"" stroke-linecap="round" stroke-linejoin="round" stroke-width="4" d="M188.656 144.269c-.435 2.963-.569 9.733 2.376 13.106 3.682 4.216 6.771 7.01-1.797 9.094"/></svg>"#,
          ],
          slots: [.themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "noseSmall",
      layer: 22,
      position: ItemPosition(xAbs: 0, xRatio: 0.08, yAbs: 0, yRatio: 0.03),
      width: 306,
      height: 306,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="306" height="306" fill="none" viewBox="0 0 306 306"><path stroke=""#,
            #"" stroke-linecap="round" stroke-linejoin="round" stroke-width="4" d="m188 146 5 18"/></svg>"#,
          ],
          slots: [.themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "noseSoft",
      layer: 22,
      position: ItemPosition(xAbs: 0, xRatio: 0.08, yAbs: 0, yRatio: 0.03),
      width: 306,
      height: 306,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="306" height="306" fill="none" viewBox="0 0 306 306"><path stroke=""#,
            #"" stroke-linecap="round" stroke-linejoin="round" stroke-width="4" d="M193.682 145c-1.385.492-3.865 2.103-2.709 4.612 1.445 3.136 12.641 11.99-3.973 14.388"/></svg>"#,
          ],
          slots: [.themeColor],
        )
      ]
    )
  ]
}
