// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

extension FatinVerseTheme {
  static let eyesItems: [ItemDescriptor] = [
    ItemDescriptor(
      key: "eyesFocused",
      layer: 20,
      position: ItemPosition(xAbs: 0, xRatio: 0.08, yAbs: 0, yRatio: 0.03),
      width: 306,
      height: 306,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="306" height="306" fill="none" viewBox="0 0 306 306"><ellipse cx="167.647" cy="134.5" fill=""#,
            #"" rx="2.647" ry="4.5"/><ellipse cx="204.647" cy="136.5" fill=""#,
            #"" rx="2.647" ry="4.5"/></svg>"#,
          ],
          slots: [.themeColor, .themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "eyesHappy",
      layer: 20,
      position: ItemPosition(xAbs: 0, xRatio: 0.08, yAbs: 0, yRatio: 0.03),
      width: 306,
      height: 306,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="306" height="306" fill="none" viewBox="0 0 306 306"><path fill=""#,
            #"" d="M173.822 135.211c-3.2 3.7-9.7 3.2-12.7-.4-.3-.3 0-.9.4-.8 1.1.1 2.1.3 3.1.4 3 .5 5.5.4 8.7.3.5-.2.7.3.5.5M211.822 137.211c-3.2 3.7-9.7 3.2-12.7-.4-.3-.3 0-.9.4-.8 1.1.1 2.1.3 3.1.4 3 .5 5.5.4 8.7.3.5-.2.7.3.5.5"/></svg>"#,
          ],
          slots: [.themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "eyesNeutral",
      layer: 20,
      position: ItemPosition(xAbs: 0, xRatio: 0.08, yAbs: 0, yRatio: 0.03),
      width: 306,
      height: 306,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="306" height="306" fill="none" viewBox="0 0 306 306"><circle cx="166.5" cy="134.5" r="4.5" fill=""#,
            ##""/><circle cx="164.647" cy="133.176" r="1.059" fill="#fff"/><circle cx="204.5" cy="136.5" r="4.5" fill=""##,
            ##""/><circle cx="202.647" cy="135.176" r="1.059" fill="#fff"/></svg>"##,
          ],
          slots: [.themeColor, .themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "eyesSurprised",
      layer: 20,
      position: ItemPosition(xAbs: 0, xRatio: 0.08, yAbs: 0, yRatio: 0.03),
      width: 306,
      height: 306,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="306" height="306" fill="none" viewBox="0 0 306 306"><path fill=""#,
            #"" d="M211.265 136.863c-2.4-1.7-5.9-1.4-8.7-1.1-1 .1-2 .3-3.1.6-.3.1-.6-.4-.4-.6l.2-.2c2.5-2.6 6.4-3.2 9.8-1.9 1.2.5 2.4 1.2 3 2.6.3.5-.4 1-.8.6M173.265 134.863c-2.4-1.7-5.9-1.4-8.7-1.1-1 .1-2 .3-3.1.6-.3.1-.6-.4-.4-.6l.2-.2c2.5-2.6 6.4-3.2 9.8-1.9 1.2.5 2.4 1.2 3 2.6.3.5-.4 1-.8.6"/></svg>"#,
          ],
          slots: [.themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "eyesWide",
      layer: 20,
      position: ItemPosition(xAbs: 0, xRatio: 0.08, yAbs: 0, yRatio: 0.03),
      width: 306,
      height: 306,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="306" height="306" fill="none" viewBox="0 0 306 306"><circle cx="166.5" cy="134.5" r="4.5" fill=""#,
            #""/><circle cx="204.5" cy="136.5" r="4.5" fill=""#,
            #""/></svg>"#,
          ],
          slots: [.themeColor, .themeColor],
        )
      ]
    )
  ]
}
