// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

extension FatinVerseTheme {
  static let mouthItems: [ItemDescriptor] = [
    ItemDescriptor(
      key: "neutralLine",
      layer: 70,
      position: ItemPosition(xAbs: 0, xRatio: 0.08, yAbs: 0, yRatio: 0.03),
      width: 306,
      height: 306,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="306" height="306" fill="none" viewBox="0 0 306 306"><path fill=""#,
            #"" d="M174.579 171.468c1.273 2.377-.546 5.205-2.728 6.105-.485.257-3.335.817-4.851 0 0-.129 2.244-.45 2.365-.515 2.182-.275 3.759-3.148 4.123-5.59a.516.516 0 0 1 .97-.193z"/><path fill=""#,
            #"" d="M183.486 178.19c-2.697 1.859-6.077 1.529-8.881.393-.909-.376-1.985-.684-2.394-1.875-.432-1.018.267-2.159 1.307-2.206 1.051-.133 1.614.463 2.444.828 2.166 1.145 6.931 1.208 9.389.636.649-.096-1.174 1.784-1.865 2.224"/></svg>"#,
          ],
          slots: [.themeColor, .themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "smileSmall",
      layer: 70,
      position: ItemPosition(xAbs: 0, xRatio: 0.08, yAbs: 0, yRatio: 0.03),
      width: 306,
      height: 306,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="306" height="306" fill="none" viewBox="0 0 306 306"><path fill=""#,
            #"" d="M186.827 180.38c-3.917 3.586-11.322.705-13.28-3.645-.245-.53-.851-1.944-.361-1.709 1.04.529 3.176 2.003 4.155 2.414 2.815 1.235 5.753 2.234 8.874 1.94.612-.117 1.04.588.612 1"/></svg>"#,
          ],
          slots: [.themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "smileSoft",
      layer: 70,
      position: ItemPosition(xAbs: 0, xRatio: 0.08, yAbs: 0, yRatio: 0.03),
      width: 306,
      height: 306,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="306" height="306" fill="none" viewBox="0 0 306 306"><path stroke=""#,
            #"" stroke-linecap="round" stroke-linejoin="round" stroke-width="3" d="M175 178c2.237-1.648 8.368-4.724 15-3.845"/></svg>"#,
          ],
          slots: [.themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "smirkLeft",
      layer: 70,
      position: ItemPosition(xAbs: 0, xRatio: 0.08, yAbs: 0, yRatio: 0.03),
      width: 306,
      height: 306,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="306" height="306" fill="none" viewBox="0 0 306 306"><path stroke=""#,
            #"" stroke-linecap="round" stroke-linejoin="round" stroke-width="2.5" d="M172.459 180.525c2.529-.829 8.497-1.761 12.143 1.147M170.807 172.076c-.432.588-1.648 1.88-3.049 2.351"/><path stroke=""#,
            #"" stroke-linecap="round" stroke-linejoin="round" stroke-width="2.5" d="M169.305 174.008c4.074.761 13.84 2.325 20.309 2.483-.249-.023-1.051.353-2.267 2.048-1.519 2.118-3.793 6.238-9.753 5.487-4.768-.602-7.513-6.93-8.289-10.018"/></svg>"#,
          ],
          slots: [.themeColor, .themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "smirkRight",
      layer: 70,
      position: ItemPosition(xAbs: 0, xRatio: 0.08, yAbs: 0, yRatio: 0.03),
      width: 306,
      height: 306,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="306" height="306" fill="none" viewBox="0 0 306 306"><path fill=""#,
            #"" d="M173.182 176.993c-3.412-5.893 1.184-5.922 5.893-3.411 4.653 2.481 6.257 1.861 8.404 2.17-5.272 6.939-10.885 7.134-14.297 1.241"/><path stroke=""#,
            ##"" stroke-linecap="round" stroke-linejoin="round" stroke-width="3" d="m187.479 175.752 1.521-.309zm0 0c-2.147-.309-3.751.311-8.404-2.17-4.709-2.511-9.305-2.482-5.893 3.411s9.025 5.698 14.297-1.241"/><path fill="#fff" d="M173.802 176.683c1.447-.103 5.272.373 8.994 3.102-.31.31-6.513 4.032-8.994-3.102"/></svg>"##,
          ],
          slots: [.themeColor, .themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "tinyDot",
      layer: 70,
      position: ItemPosition(xAbs: 0, xRatio: 0.08, yAbs: 0, yRatio: 0.03),
      width: 306,
      height: 306,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="306" height="306" fill="none" viewBox="0 0 306 306"><circle cx="181.5" cy="177.5" r="3" stroke=""#,
            #"" stroke-width="3"/></svg>"#,
          ],
          slots: [.themeColor],
        )
      ]
    )
  ]
}
