// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

extension FatinVerseTheme {
  static let eyebrowsItems: [ItemDescriptor] = [
    ItemDescriptor(
      key: "browAngled",
      layer: 21,
      position: ItemPosition(xAbs: 0, xRatio: 0.08, yAbs: 0, yRatio: 0.03),
      width: 306,
      height: 306,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="306" height="306" fill="none" viewBox="0 0 306 306"><path fill=""#,
            #"" stroke=""#,
            #"" stroke-linecap="round" stroke-linejoin="round" stroke-width="6" d="M169.226 124.214c-1.917-1.623-5.604-.738-7.226 0 2.949-2.36 7.521-2.802 8.553-1.475s.147 2.359-1.327 1.475M204.774 126.214c1.917-1.623 5.604-.738 7.226 0-2.949-2.36-7.521-2.802-8.553-1.475s-.147 2.359 1.327 1.475"/></svg>"#,
          ],
          slots: [.themeColor, .themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "browFlat",
      layer: 21,
      position: ItemPosition(xAbs: 0, xRatio: 0.08, yAbs: 0, yRatio: 0.03),
      width: 306,
      height: 306,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="306" height="306" fill="none" viewBox="0 0 306 306"><path stroke=""#,
            #"" stroke-linecap="round" stroke-linejoin="round" stroke-width="6" d="M157.924 123.941c-.196-1.552 1.963-4.166 12.161-2.2M211.971 127.375c.306-1.534-1.658-4.297-11.971-3.069"/></svg>"#,
          ],
          slots: [.themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "browRaised",
      layer: 21,
      position: ItemPosition(xAbs: 0, xRatio: 0.08, yAbs: 0, yRatio: 0.03),
      width: 306,
      height: 306,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="306" height="306" fill="none" viewBox="0 0 306 306"><path fill=""#,
            #"" d="M169.5 124.914c1 .136 1.772-.909 1.409-1.909-.182-.546-.5-1.045-1-1.364-1.546-.954-7.318-1.045-10.363 1.137-2.727 1.999 5.409 1.499 9.954 2.136M202.526 126.628c-1.184 0-1.907-1.15-1.315-2.1.328-.5.789-.95 1.446-1.2 2.038-.75 7.495-.3 9.928 2.25 2.169 2.25-4.603 1-10.059 1.05"/></svg>"#,
          ],
          slots: [.themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "browSoft",
      layer: 21,
      position: ItemPosition(xAbs: 0, xRatio: 0.08, yAbs: 0, yRatio: 0.03),
      width: 306,
      height: 306,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="306" height="306" fill="none" viewBox="0 0 306 306"><path stroke=""#,
            #"" stroke-linecap="round" stroke-linejoin="round" stroke-width="6" d="M159 123.704c2.204-2.04 7.69-4.898 12 0M200 125.704c2.204-2.04 7.69-4.898 12 0"/></svg>"#,
          ],
          slots: [.themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "browThick",
      layer: 21,
      position: ItemPosition(xAbs: 0, xRatio: 0.08, yAbs: 0, yRatio: 0.03),
      width: 306,
      height: 306,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="306" height="306" fill="none" viewBox="0 0 306 306"><path fill=""#,
            #"" stroke=""#,
            #"" stroke-linecap="round" stroke-linejoin="round" stroke-width="6" d="M170.557 123.838c-.511-.085-8.09-1.172-10.729-.736 4.058-1.25 9.366-1.592 11.07-1.308 1.703.283 1.363 2.327-.341 2.044M201.295 126.072c.518 0 8.173.173 10.705 1.036-3.799-1.899-8.978-3.108-10.705-3.108s-1.727 2.072 0 2.072"/></svg>"#,
          ],
          slots: [.themeColor, .themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "browThin",
      layer: 21,
      position: ItemPosition(xAbs: 0, xRatio: 0.08, yAbs: 0, yRatio: 0.03),
      width: 306,
      height: 306,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="306" height="306" fill="none" viewBox="0 0 306 306"><path fill=""#,
            #"" d="M170.5 124.914c1 .136 1.772-.909 1.409-1.909-.182-.546-.5-1.045-1-1.364-1.546-.954-7.318-1.045-10.363 1.137-2.727 1.999 5.409 1.499 9.954 2.136M201.526 126.628c-1.184 0-1.907-1.15-1.315-2.1.328-.5.789-.95 1.446-1.2 2.038-.75 7.495-.3 9.928 2.25 2.169 2.25-4.603 1-10.059 1.05"/></svg>"#,
          ],
          slots: [.themeColor],
        )
      ]
    )
  ]
}
