// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

/// Namespace for the toon-flat theme's generated data.
public enum ToonFlatTheme {}

extension AvatuneTheme {
  /// The toon-flat theme, generated from @avatune/toon-flat-theme@1.0.0.
  public static let toonFlat: AvatuneTheme = AvatuneTheme(
    name: "toon-flat",
    style: AvatuneTheme.Style(size: 534, borderRadius: .percent(50)),
    backgroundPalette: [.hex(0xFFEDEF)],
    categories: [
      AvatuneTheme.Category(
        category: .body,
        palette: [.hex(0x4B4EA0), .hex(0x2C2A2C), .hex(0xDD4B4B), .hex(0x7FD280), .hex(0xEAB65D), .hex(0x72D2DF)],
        items: ToonFlatTheme.bodyItems
      ),
      AvatuneTheme.Category(
        category: .eyes,
        palette: [.hex(0x000000), .hex(0xFFFFFF), .hex(0x9287FF), .hex(0x6BD9E9), .hex(0xFC909F), .hex(0xF4D150)],
        items: ToonFlatTheme.eyesItems
      ),
      AvatuneTheme.Category(
        category: .hair,
        palette: [.hex(0x262626), .hex(0xD8D5D5), .hex(0x8B522D), .hex(0xF09947), .hex(0xEECF9B), .hex(0xE26AD2)],
        items: ToonFlatTheme.hairItems
      ),
      AvatuneTheme.Category(
        category: .head,
        palette: [.hex(0xFCBE93), .hex(0xC78A5C), .hex(0x80502E), .hex(0xFDCDAC)],
        items: ToonFlatTheme.headItems
      ),
      AvatuneTheme.Category(
        category: .mouth,
        palette: [.hex(0x000000)],
        items: ToonFlatTheme.mouthItems
      ),
      AvatuneTheme.Category(
        category: .nose,
        palette: [.hex(0x000000)],
        items: ToonFlatTheme.noseItems
      )
    ],
    connectedColors: [],
    predictorMappings: AvatuneTheme.PredictorMappings(
      hair: ["long": ["pasted4", "pasted1"], "medium": ["pasted5", "pasted2"], "short": ["pasted8", "pasted9"]],
      hairColor: ["black": [.hex(0x262626)], "blond": [.hex(0xEECF9B), .hex(0xF09947)], "brown": [.hex(0x8B522D)], "gray": [.hex(0xD8D5D5)]]
    )
  )
}
