// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

/// Item identifiers for the toon-flat theme.
public enum ToonFlat {
  public enum Body: String, CaseIterable, Sendable {
    case halfZip
    case tshirt
    case turtleneck
    case shirt
    case sweater
    case jacket
    case vest
    case hoodie
  }

  public enum Eyes: String, CaseIterable, Sendable {
    case big
    case almond
    case narrow
  }

  public enum Hair: String, CaseIterable, Sendable {
    case dreads
    case messy
    case bun
    case bowlerHat
    case ponyTail
    case beanie
    case sidePart
    case short
  }

  public enum Head: String, CaseIterable, Sendable {
    case standard
  }

  public enum Mouth: String, CaseIterable, Sendable {
    case smile
    case flat
    case laugh
    case smirk
    case openSmile
  }

  public enum Nose: String, CaseIterable, Sendable {
    case curve
    case flat
    case thin
  }
}
