// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

extension MiniavsTheme {
  static let headItems: [ItemDescriptor] = [
    ItemDescriptor(
      key: "standard",
      layer: 1,
      position: ItemPosition(xAbs: 0, xRatio: 0, yAbs: 0, yRatio: 0),
      width: 64,
      height: 64,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" fill="none" viewBox="0 0 64 64"><circle cx="18" cy="37" r="5" fill=""#,
            #""/><path fill=""#,
            #"" d="M18 41h17v24.87S31.357 68 26.5 68 18 64.523 18 64.523z"/><path fill=""#,
            #"" d="M34.811 53.112c0 5.385-.87 4.875-6.533 4.875s-8.276-4.365-8.276-9.75S19.787 38 24.357 38c12.923.476 10.454 9.728 10.454 15.112"/><path fill=""#,
            #"" d="M45.887 36.1c0 8.922-1.385 19.893-12.385 19.893S17.43 45.022 17.43 36.1C15.002 25.5 15.502 13 32.002 13s13.885 14.177 13.885 23.1"/><rect width="3" height="2" x="36" y="41" fill=""#,
            #"" rx="1"/></svg>"#,
          ],
          slots: [.derived([.desaturate(0.08), .darken(0.06)]), .derived([.desaturate(0.08), .darken(0.06)]), .derived([.desaturate(0.16), .darken(0.12)]), .themeColor, .derived([.desaturate(0.08), .darken(0.06)])],
        )
      ]
    ),
    ItemDescriptor(
      key: "thin",
      layer: 1,
      position: ItemPosition(xAbs: 0, xRatio: 0, yAbs: 0, yRatio: 0),
      width: 64,
      height: 64,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" fill="none" viewBox="0 0 64 64"><circle cx="18" cy="37" r="5" fill=""#,
            #""/><path fill=""#,
            #"" d="M18 41h17v24.87S31.357 68 26.5 68 18 64.523 18 64.523z"/><path fill=""#,
            #"" d="M35 53.868c0 5.654-3.5 6.132-6.617 5.119S19 49.154 19 43.5s.784-5.5 5.413-5.5C37.5 38.5 35 48.214 35 53.868"/><path fill=""#,
            #"" d="M45.887 36.1C45.887 45.021 42 55 35.5 56.5c-9.5-1-18.07-11.478-18.07-20.4C15.002 25.5 15.502 13 32.002 13s13.885 14.177 13.885 23.1"/><rect width="3" height="2" x="36" y="41" fill=""#,
            #"" rx="1"/></svg>"#,
          ],
          slots: [.derived([.desaturate(0.08), .darken(0.06)]), .derived([.desaturate(0.08), .darken(0.06)]), .derived([.desaturate(0.16), .darken(0.12)]), .themeColor, .derived([.desaturate(0.08), .darken(0.06)])],
        )
      ]
    ),
    ItemDescriptor(
      key: "wide",
      layer: 1,
      position: ItemPosition(xAbs: 0, xRatio: 0, yAbs: 0, yRatio: 0),
      width: 64,
      height: 64,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" fill="none" viewBox="0 0 64 64"><circle cx="18" cy="37" r="5" fill=""#,
            #""/><path fill=""#,
            #"" d="M18 41h17v24.87S31.357 68 26.5 68 18 64.523 18 64.523z"/><path fill=""#,
            #"" d="M35 53.868c0 5.654-.882 5.118-6.617 5.118s-8.381-4.583-8.381-10.237S19.784 38 24.412 38C37.5 38.5 35 48.214 35 53.868"/><path fill=""#,
            #"" d="M45.887 36.1c0 8.922 3.686 19.893-12.385 19.893-16.072 0-16.072-10.971-16.072-19.894C15.002 25.5 15.502 13 32.002 13s13.885 14.177 13.885 23.1"/><rect width="3" height="2" x="36" y="41" fill=""#,
            #"" rx="1"/></svg>"#,
          ],
          slots: [.derived([.desaturate(0.08), .darken(0.06)]), .derived([.desaturate(0.08), .darken(0.06)]), .derived([.desaturate(0.16), .darken(0.12)]), .themeColor, .derived([.desaturate(0.08), .darken(0.06)])],
        )
      ]
    )
  ]
}
