// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

extension MiniavsTheme {
  static let faceDetailsItems: [ItemDescriptor] = [
    ItemDescriptor(
      key: "standard",
      layer: 25,
      position: ItemPosition(xAbs: 0, xRatio: 0, yAbs: 0, yRatio: 0),
      width: 64,
      height: 64,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" fill="none" viewBox="0 0 64 64"><rect width="5" height="3" x="24" y="39" fill=""#,
            #"" rx="1.5"/><rect width="4" height="3" x="43" y="39" fill=""#,
            #"" rx="1.5"/></svg>"#,
          ],
          slots: [.themeColor, .themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "none",
      layer: 0,
      position: ItemPosition(xAbs: 0, xRatio: 0, yAbs: 0, yRatio: 0),
      width: 0,
      height: 0,
      fragments: []
    )
  ]
}
