// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

extension MiniavsTheme {
  static let bodyItems: [ItemDescriptor] = [
    ItemDescriptor(
      key: "standard",
      layer: 10,
      position: ItemPosition(xAbs: 0, xRatio: 0, yAbs: 0, yRatio: 0),
      width: 64,
      height: 64,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" fill="none" viewBox="0 0 64 64"><rect width="40" height="23" x="7" y="60" fill=""#,
            #"" rx="9"/></svg>"#,
          ],
          slots: [.themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "golf",
      layer: 10,
      position: ItemPosition(xAbs: 0, xRatio: 0, yAbs: 0, yRatio: 0),
      width: 64,
      height: 64,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" fill="none" viewBox="0 0 64 64"><rect width="40" height="23" x="7" y="60" fill=""#,
            #"" rx="9"/><path fill=""#,
            #"" d="M17 58h19v3s-5 1-9.5 1-9.5-1-9.5-1z"/><path fill=""#,
            #"" d="M17 58h19v2s-3 1.5-9.5 1.5S17 60 17 60z"/><path fill=""#,
            #"" d="M16.5 59a2 2 0 0 1 2-2h16a2 2 0 0 1 2 2s-5 1-10 1-10-1-10-1"/></svg>"#,
          ],
          slots: [.themeColor, .themeColor, .derived([.rotate(-7), .desaturate(0.05), .darken(0.08)]), .themeColor],
        )
      ]
    )
  ]
}
