// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

extension MiniavsTheme {
  static let eyesItems: [ItemDescriptor] = [
    ItemDescriptor(
      key: "standard",
      layer: 20,
      position: ItemPosition(xAbs: 0, xRatio: 0, yAbs: 0, yRatio: 0),
      width: 64,
      height: 64,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" fill="none" viewBox="0 0 64 64"><rect width="3" height="4" x="30" y="36" fill=""#,
            #"" rx="1.5"/><rect width="3" height="4" x="40" y="36" fill=""#,
            #"" rx="1.5"/></svg>"#,
          ],
          slots: [.themeColor, .themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "confident",
      layer: 20,
      position: ItemPosition(xAbs: 0, xRatio: 0, yAbs: 0, yRatio: 0),
      width: 64,
      height: 64,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" fill="none" viewBox="0 0 64 64"><path fill=""#,
            #"" d="M43 37.5a1.5 1.5 0 0 1-3 0v-1.227c0-.15.122-.273.273-.273h2.454c.15 0 .273.122.273.273zM33 37.5a1.5 1.5 0 0 1-3 0v-1.227c0-.15.122-.273.273-.273h2.454c.15 0 .273.122.273.273z"/><path stroke=""#,
            #"" stroke-linecap="round" d="M29.5 36.5h4M39.5 36.5h4"/></svg>"#,
          ],
          slots: [.themeColor, .themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "happy",
      layer: 20,
      position: ItemPosition(xAbs: 0, xRatio: 0, yAbs: 0, yRatio: 0),
      width: 64,
      height: 64,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" fill="none" viewBox="0 0 64 64"><path fill=""#,
            #"" d="M30 37.5a1.5 1.5 0 0 1 3 0v1.227c0 .15-.122.273-.273.273h-2.454a.273.273 0 0 1-.273-.273zM40 37.5a1.5 1.5 0 0 1 3 0v1.227c0 .15-.122.273-.273.273h-2.454a.273.273 0 0 1-.273-.273z"/></svg>"#,
          ],
          slots: [.themeColor],
        )
      ]
    )
  ]
}
