// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

extension MiniavsTheme {
  static let hairItems: [ItemDescriptor] = [
    ItemDescriptor(
      key: "baldness",
      layer: 5,
      position: ItemPosition(xAbs: 0, xRatio: 0, yAbs: 0, yRatio: 0),
      width: 64,
      height: 64,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" fill="none" viewBox="0 0 64 64"><rect width="9" height="2" x="14" y="26" fill=""#,
            #"" rx="1"/><rect width="7" height="2" x="14" y="33" fill=""#,
            #"" rx="1"/><rect width="13" height="3" x="12" y="29" fill=""#,
            #"" rx="1.5"/></svg>"#,
          ],
          slots: [.themeColor, .themeColor, .themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "classic1",
      layer: 5,
      position: ItemPosition(xAbs: 0, xRatio: 0, yAbs: 0, yRatio: 0),
      width: 63,
      height: 64,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="63" height="64" fill="none" viewBox="0 0 63 64"><path fill=""#,
            #"" fill-rule="evenodd" d="M28.967 26.203c5.61 1.863 13.389 4.445 21.535-3.701 4-4-14-21-28.5-11.5-11.333 1.679-10.686 8.47-10.186 13.71.096 1.002.186 1.948.186 2.79 0 .533.07.931.2 1.218-.16 1.233-.2 2.467-.2 3.282a4 4 0 1 0 8 0A4 4 0 0 0 23.875 27l.127.002c1.224 0 2.319-.55 3.053-1.416.604.183 1.243.395 1.912.617" clip-rule="evenodd"/></svg>"#,
          ],
          slots: [.themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "classic2",
      layer: 5,
      position: ItemPosition(xAbs: 0, xRatio: 0, yAbs: 0, yRatio: 0),
      width: 64,
      height: 64,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" fill="none" viewBox="0 0 64 64"><path fill=""#,
            #"" fill-rule="evenodd" d="M28.118 27.466c7.796 1.142 21.48 3.147 22.882-9.464 1-9-12.5-19.5-27-10-9.11 1.35-11.389 8.278-11.908 14.254A3.99 3.99 0 0 0 11 25.002c0 .53.103 1.037.29 1.5-.187.463-.29.97-.29 1.5 0 1.106.449 2.106 1.174 2.83A4 4 0 1 0 20 32.002a4 4 0 0 0 3.874-4.999l.126-.001c.952 0 2.39.21 4.118.464" clip-rule="evenodd"/></svg>"#,
          ],
          slots: [.themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "curly",
      layer: 5,
      position: ItemPosition(xAbs: 0, xRatio: 0, yAbs: 0, yRatio: 0),
      width: 64,
      height: 64,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" fill="none" viewBox="0 0 64 64"><path fill=""#,
            #"" fill-rule="evenodd" d="M45.967 32.483a4 4 0 0 0 1.78-4.884 4 4 0 0 0-2.966-7.41c1.418 3.674 1.314 8.218 1.186 12.294" clip-rule="evenodd"/><path fill=""#,
            #"" fill-rule="evenodd" d="M36.297 22.76A4.98 4.98 0 0 1 33 24a4.98 4.98 0 0 1-3.057-1.043A6.98 6.98 0 0 1 25 25a7 7 0 0 1-2.045-.304 4 4 0 0 1-.892.731 4 4 0 0 1-1.351 6.189A1.5 1.5 0 0 1 19.465 34a4 4 0 0 1-7.291-3.17A3.99 3.99 0 0 1 11 28c0-1.106.449-2.107 1.174-2.83a4 4 0 0 1 .738-3.713 7.003 7.003 0 0 1 4.098-10.17 4 4 0 0 1 5.927-3.788A7 7 0 0 1 29 4c1.373 0 2.654.395 3.735 1.079a6.502 6.502 0 0 1 10.78 1.954 4 4 0 0 1 3.439 4.577C48.809 12.984 50 15.112 50 17.5c0 4.142-3.582 7.5-8 7.5-2.233 0-4.252-.858-5.703-2.24" clip-rule="evenodd"/></svg>"#,
          ],
          slots: [.themeColor, .themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "elvis",
      layer: 5,
      position: ItemPosition(xAbs: 0, xRatio: 0, yAbs: 0, yRatio: 0),
      width: 64,
      height: 64,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" fill="none" viewBox="0 0 64 64"><path fill=""#,
            #"" d="M21.998 28c-.629 3 1 6.982 1 7.744s-3.93 3.025-5 3.757c-1.069.731-1.5-7-1.5-7-3 0-3.5 5.5-3.5 5.5s-2.244-.74-3-4.5c-.51-2.54.299-8.089.5-9.5.5-3.5 1-11.5 7.5-15.5s23-4 27-3c9.894 2.473 11.218 15.986 8 20.5-5 5.5-19-1-23.5-1s-6.87 0-7.5 3"/></svg>"#,
          ],
          slots: [.themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "long",
      layer: 5,
      position: ItemPosition(xAbs: 0, xRatio: 0, yAbs: 0, yRatio: 0),
      width: 64,
      height: 64,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" fill="none" viewBox="0 0 64 64"><g clip-path="url(#clip0_73_85)"><path fill=""#,
            #"" fill-rule="evenodd" d="M48 25a18 18 0 0 0-35.993-.5H12V65h11V34.597c2.485-.478 6.78-1.53 12.208-3.756 5.464-2.241 8.873-4.359 10.668-5.637.242 2.524.158 5.16.08 7.61v.001c-.036 1.145-.071 2.25-.071 3.284q0 .612-.025 1.229c.231-.073.447-.153.639-.24 1.5-.684 1.5-1.597 1.5-1.597V25zm-33 8a5 5 0 0 0-1.62 2.087A5 5 0 0 0 15 41z" clip-rule="evenodd"/></g></svg>"#,
          ],
          slots: [.themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "ponyTail",
      layer: 5,
      position: ItemPosition(xAbs: 0, xRatio: 0, yAbs: 0, yRatio: 0),
      width: 64,
      height: 64,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" fill="none" viewBox="0 0 64 64"><g clip-path="url(#clip0_90_1)"><path fill=""#,
            ##"" d="M0 10c7.997-7.997 13.002 3 13.002 3L11 21s-2 2.5 0 10-2.5 11.5-2.5 11.5-3.5 2.502-6.5.502-3.397-3.922-3-7.5c.5-4.5 2-3.002 2-7.502s-8.997-10.004-1-18"/><path fill="#ff6c98" d="m13.03 13.181 5.508 2.382-3.572 8.26-5.507-2.38s-.96-1.943.54-4.942c1.497-3 3.032-3.32 3.032-3.32"/><path fill=""##,
            #"" fill-rule="evenodd" d="m18 41-1.323-8.823A5 5 0 0 0 18 42v8.3a22.1 22.1 0 0 1-4.083-4.83c-1.7-2.704-2.888-5.804-3.482-9.093a27.5 27.5 0 0 1 .04-9.97c.62-3.283 1.833-6.37 3.556-9.055 1.722-2.684 3.915-4.903 6.43-6.506s5.292-2.555 8.147-2.789a17 17 0 0 1 1.868-.05Q30.739 8 31 8c2.495 0 4.966.453 7.271 1.332 2.305.88 4.4 2.169 6.164 3.794a17.5 17.5 0 0 1 4.119 5.677A16.4 16.4 0 0 1 49.93 24H50v4.286s-.329.152-.998.366v8.488s0 1.404-1.5 2.456c-.52.365-1.218.645-1.91.856a33 33 0 0 0 .297-4.353c0-1.034.035-2.139.071-3.284.036-1.118.073-2.275.08-3.441-1.852.339-4.367.626-7.578.626C30.615 30 26 28.286 26 28.286v-.999c-.68 1.064-1.416 2.35-2 3.713-.75 1.75-.75 3.544-.75 5.051s0 2.73-.75 3.335C21 40.596 18 41 18 41" clip-rule="evenodd"/></g></svg>"#,
          ],
          slots: [.themeColor, .themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "slaughter",
      layer: 5,
      position: ItemPosition(xAbs: 0, xRatio: 0, yAbs: 0, yRatio: 0),
      width: 64,
      height: 64,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" fill="none" viewBox="0 0 64 64"><path fill=""#,
            #"" fill-rule="evenodd" d="M24 25c0 .53-.103 1.037-.29 1.5A4 4 0 0 1 20 32a4 4 0 0 1-8 0c0-1.046.065-2.782.368-4.321a4 4 0 0 1 4.801-5.505A4 4 0 0 1 24 25M45.849 33.895a4.002 4.002 0 0 0 2.785-5.393 4 4 0 0 0-3.134-5.459c.593 3.14.482 6.61.382 9.774z" clip-rule="evenodd"/></svg>"#,
          ],
          slots: [.themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "stylish",
      layer: 5,
      position: ItemPosition(xAbs: 0, xRatio: 0, yAbs: 0, yRatio: 0),
      width: 64,
      height: 64,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" fill="none" viewBox="0 0 64 64"><path fill=""#,
            #"" d="M20.673 28.222v6.018c0 .762-.673 1.761-1.173 2.261s-2 1.5-2.85 1.5c-.848 0-3.539-.451-4.826-2.257-1.287-1.805-.893-11.322 0-13.54.892-2.218 4.183-6.888 8.85-10.452 3.38-2.582 7.665-4.717 12.871-5.345C58.485 3.397 49.218 20.987 46 25.5c-5.5-2-9.5-2.5-16.717-1.518-7.217.983-8.016 1.982-8.61 4.239"/></svg>"#,
          ],
          slots: [.themeColor],
        )
      ]
    )
  ]
}
