// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

extension MiniavsTheme {
  static let mouthItems: [ItemDescriptor] = [
    ItemDescriptor(
      key: "standard",
      layer: 15,
      position: ItemPosition(xAbs: 0, xRatio: 0, yAbs: 0, yRatio: 0),
      width: 64,
      height: 64,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" fill="none" viewBox="0 0 64 64"><path fill=""#,
            #"" d="M27.93 46a1 1 0 0 1 1-1h9.142a1 1 0 0 1 1 1 5 5 0 0 1-5 5H32.93a5 5 0 0 1-5-5"/><path fill=""#,
            ##"" fill-rule="evenodd" d="M35.756 50.708a5 5 0 0 1-1.684.29H32.93a5 5 0 0 1-4.996-4.8c.764-.285 1.898-.253 3.017-.22.356.01.71.02 1.05.02 2.21 0 4 1.568 4 3.5 0 .426-.087.833-.245 1.21" clip-rule="evenodd"/><path fill="#fff" d="M29 45h10v1a1 1 0 0 1-1 1h-8a1 1 0 0 1-1-1z"/></svg>"##,
          ],
          slots: [.derived([.rotate(3), .darken(0.2)]), .themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "toothless",
      layer: 15,
      position: ItemPosition(xAbs: 0, xRatio: 0, yAbs: 0, yRatio: 0),
      width: 64,
      height: 64,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" fill="none" viewBox="0 0 64 64"><path fill=""#,
            #"" d="M27.93 46a1 1 0 0 1 1-1h9.142a1 1 0 0 1 1 1 5 5 0 0 1-5 5H32.93a5 5 0 0 1-5-5"/><path fill=""#,
            ##"" fill-rule="evenodd" d="M35.756 50.708a5 5 0 0 1-1.684.29H32.93a5 5 0 0 1-4.996-4.8c.764-.285 1.898-.253 3.017-.22.356.01.71.02 1.05.02 2.21 0 4 1.568 4 3.5 0 .426-.087.833-.245 1.21" clip-rule="evenodd"/><path fill="#fff" d="M29 45h10v1a1 1 0 0 1-1 1h-8a1 1 0 0 1-1-1z"/></svg>"##,
          ],
          slots: [.derived([.rotate(3), .darken(0.2)]), .themeColor],
        )
      ]
    )
  ]
}
