// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

extension PawelOlekManTheme {
  static let eyesItems: [ItemDescriptor] = [
    ItemDescriptor(
      key: "big",
      layer: 40,
      position: ItemPosition(xAbs: 0, xRatio: 0.36, yAbs: 0, yRatio: 0.45),
      width: 118,
      height: 38,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="118" height="38" fill="none" viewBox="0 0 118 38"><rect width="13" height="22" x="13.561" y="15.25" fill="#2b2b2b" rx="6.5"/><rect width="13" height="22" x="90.561" y="15.25" fill="#2b2b2b" rx="6.5"/><path stroke="#2b2b2b" stroke-width="3" d="M1.06 8.25c9-9 29-9 38 0M78.06 8.25c9-9 29.001-9 38.001 0"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "happy",
      layer: 40,
      position: ItemPosition(xAbs: 0, xRatio: 0.36, yAbs: 0, yRatio: 0.45),
      width: 115,
      height: 36,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="115" height="36" fill="none" viewBox="0 0 115 36"><rect width="13" height="22" x="12.5" y="10.75" fill="#2b2b2b" rx="6.5"/><rect width="13" height="22" x="102.5" y="32.75" fill="#2b2b2b" rx="6.5" transform="rotate(-180 102.5 32.75)"/><path stroke="#2b2b2b" stroke-width="3" d="M2.892 13.578C7.51 3.023 22.949-1.114 32.226 5.718M113.335 13.578C108.716 3.023 93.277-1.114 84 5.718"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "small",
      layer: 40,
      position: ItemPosition(xAbs: 0, xRatio: 0.36, yAbs: 0, yRatio: 0.45),
      width: 116,
      height: 36,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="116" height="36" fill="none" viewBox="0 0 116 36"><rect width="13" height="14" x="12.41" y="11.25" fill="#2b2b2b" rx="6.5"/><rect width="13" height="14" x="89.41" y="11.25" fill="#2b2b2b" rx="6.5"/><path stroke="#2b2b2b" stroke-width="3" d="M1.22 9.82c2.86-4 7.194-8.526 12.105-8.302 7.05.32 14.809.821 21.585 3.732M112.546 9.82c-2.86-4-7.193-8.526-12.105-8.302-7.05.32-14.809.821-21.585 3.732"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "standard",
      layer: 40,
      position: ItemPosition(xAbs: 0, xRatio: 0.36, yAbs: 0, yRatio: 0.45),
      width: 118,
      height: 36,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="118" height="36" fill="none" viewBox="0 0 118 36"><path fill="#2b2b2b" d="M13.06 12.294h13v4.5a6.5 6.5 0 0 1-13 0zM90.06 12.294h13.001v4.5a6.5 6.5 0 0 1-13 0z"/><path stroke="#2b2b2b" stroke-width="3" d="M1.06 19.044c9-9 29-9 38 0M78.06 19.044c9-9 29.001-9 38.001 0"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "eyelashes",
      layer: 40,
      position: ItemPosition(xAbs: 0, xRatio: 0.345, yAbs: 0, yRatio: 0.44),
      width: 123,
      height: 43,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="123" height="43" fill="none" viewBox="0 0 123 43"><rect width="13" height="14" x="16.711" y="24.82" fill="#2b2b2b" rx="6.5"/><rect width="13" height="14" x="93.711" y="24.82" fill="#2b2b2b" rx="6.5"/><path stroke="#2b2b2b" stroke-width="3" d="M4.711 13.82c2.344-2.345 5.435-4.078 8.883-5.201m29.117 5.2c-4.914-4.914-13.108-7.145-21-6.692m-21 .693 6.5 3.5m-4.5-6.5 8 5m-4-7 6.883 5.799m0 0a30 30 0 0 1 2.617-.721M11.594.82l4.617 7.078m0 0a32 32 0 0 1 2.5-.467m-2-6.611 2 6.611m0 0c.99-.145 1.993-.247 3-.304m0-4.307v4.307M117.711 16.82c-2.344-2.345-5.435-4.078-8.883-5.201m-29.117 5.2c4.914-4.914 13.108-7.145 21-6.692m21 .692-6.5 3.5m4.5-6.5-8 5m4-7-6.883 5.8m0 0a30 30 0 0 0-2.617-.721m4.617-7.078-4.617 7.078m0 0a32 32 0 0 0-2.5-.467m2-6.611-2 6.611m0 0a34 34 0 0 0-3-.304m0-4.307v4.307"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "eyelids",
      layer: 40,
      position: ItemPosition(xAbs: 0, xRatio: 0.345, yAbs: 0, yRatio: 0.45),
      width: 127,
      height: 36,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="127" height="36" fill="none" viewBox="0 0 127 36"><path fill="#2b2b2b" d="M15.889 10h15v6.5a7.5 7.5 0 0 1-15 0zM110.888 10h-15v6.5a7.5 7.5 0 1 0 15 0z"/><path stroke="#2b2b2b" stroke-width="3" d="M.962 15.504C12.61 5.772 36.365 7.9 46.097 19.548M125.768 15.985c-11.44-9.974-35.235-8.346-45.21 3.095"/></svg>"##,
          ],
          slots: [],
        )
      ]
    )
  ]
}
