// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

extension PawelOlekManTheme {
  static let noseItems: [ItemDescriptor] = [
    ItemDescriptor(
      key: "big",
      layer: 50,
      position: ItemPosition(xAbs: 0, xRatio: 0.45, yAbs: 0, yRatio: 0.48),
      width: 31,
      height: 54,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="31" height="54" fill="none" viewBox="0 0 31 54"><path stroke="#2b2b2b" stroke-width="3" d="m22.713.341 2.299 9.837c2.459 10.52 3.7 21.287 3.7 32.09v1.354c0 3.5-1.363 7.143-4.72 8.139-6.966 2.066-16.934-.644-23.28-4.07"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "bigWide",
      layer: 50,
      position: ItemPosition(xAbs: 0, xRatio: 0.45, yAbs: 0, yRatio: 0.48),
      width: 39,
      height: 55,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="39" height="55" fill="none" viewBox="0 0 39 55"><path stroke="#2b2b2b" stroke-width="3" d="M.696 47c3.933 2.059 6.982 3.605 10.633 5.317 3.651 1.71 6.853 1.32 10.733 0s8.42-3.269 11.587-5.15c3.166-1.88 4.569-5.6 3.311-9.373-2.45-7.35-8.717-9.807-9.62-19.014L25.697 2"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "small",
      layer: 50,
      position: ItemPosition(xAbs: 0, xRatio: 0.45, yAbs: 0, yRatio: 0.48),
      width: 34,
      height: 53,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="34" height="53" fill="none" viewBox="0 0 34 53"><path stroke="#2b2b2b" stroke-width="3" d="m29.042 27 2.465 12.173c.946 4.673-.774 9.696-5.39 10.891-8.33 2.157-19.588.585-25.075-4.715"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "standard",
      layer: 50,
      position: ItemPosition(xAbs: 0, xRatio: 0.46, yAbs: 0, yRatio: 0.48),
      width: 27,
      height: 55,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="27" height="55" fill="none" viewBox="0 0 27 55"><path stroke="#2b2b2b" stroke-width="3" d="M25.122 0v43.28c0 3.502-1.321 7.112-4.554 8.456-6.31 2.624-14.522 1.162-19.446-4.387"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "wide",
      layer: 50,
      position: ItemPosition(xAbs: 0, xRatio: 0.445, yAbs: 0, yRatio: 0.48),
      width: 45,
      height: 55,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="45" height="55" fill="none" viewBox="0 0 45 55"><path stroke="#2b2b2b" stroke-width="3" d="M.613 46.676c4.5 2.016 7.986 3.53 12.162 5.206s7.838 1.293 12.275 0 9.63-3.2 13.252-5.042c3.622-1.843 5.225-5.485 3.787-9.18-2.802-7.197-9.97-13.644-11.002-22.66"/></svg>"##,
          ],
          slots: [],
        )
      ]
    )
  ]
}
