// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

extension PawelOlekManTheme {
  static let glassesItems: [ItemDescriptor] = [
    ItemDescriptor(
      key: "brow",
      layer: 60,
      position: ItemPosition(xAbs: 0, xRatio: 0.25, yAbs: 0, yRatio: 0.4),
      width: 202,
      height: 70,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="202" height="70" fill="none" viewBox="0 0 202 70"><path stroke="#2b2b2b" stroke-width="6" d="M6 26.541h15m69 3.884.59.124c7.054 1.492 14.333 1.585 21.41.212m86-4.22h-17M51.5 4.986c37.732-2.683 59.203-2.613 98 0"/><path stroke="#2b2b2b" stroke-width="6" d="M23.206 45.417 19.717 25.25c-.971-5.62 2.507-11.095 8.088-12.264 21.061-4.411 39.014-4.027 58.373 1.615 5.148 1.5 8.12 6.754 7.161 12.029L88.09 55.49a14 14 0 0 1-13.774 11.495h-25.49c-12.65 0-23.464-9.104-25.62-21.569ZM178.794 45.417l3.489-20.167c.972-5.62-2.507-11.095-8.088-12.264-21.061-4.411-39.014-4.027-58.373 1.615-5.148 1.5-8.12 6.754-7.161 12.029l5.249 28.861a14 14 0 0 0 13.774 11.495h25.491c12.65 0 23.464-9.104 25.619-21.569Z"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "patch",
      layer: 60,
      position: ItemPosition(xAbs: 0, xRatio: 0.25, yAbs: 0, yRatio: 0.41),
      width: 202,
      height: 63,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="202" height="63" fill="none" viewBox="0 0 202 63"><path stroke="#2b2b2b" stroke-width="6" d="M7 4c33.343 6.981 66.5 5.5 102.5 13.5M200 17l-21.5-1"/><path fill="#2b2b2b" stroke="#2b2b2b" stroke-width="6" d="M179 36v-9.194c0-10.888-7.289-20.703-18.037-22.45-13.028-2.118-23.698-1.779-35.91 1.183C115.245 7.917 109 17.229 109 27.32V36c0 13.255 10.745 24 24 24h22c13.255 0 24-10.745 24-24Z"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "round",
      layer: 60,
      position: ItemPosition(xAbs: 0, xRatio: 0.25, yAbs: 0, yRatio: 0.42),
      width: 205,
      height: 63,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="205" height="63" fill="none" viewBox="0 0 205 63"><circle cx="62.809" cy="31.5" r="28.5" stroke="#2b2b2b" stroke-width="6"/><circle cx="142.809" cy="31.5" r="28.5" stroke="#2b2b2b" stroke-width="6"/><path stroke="#2b2b2b" stroke-width="6" d="M89.309 31c11.268-4.238 17.097-3.755 27 0M171.309 27l32-16M34.309 27l-33-16"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "square",
      layer: 60,
      position: ItemPosition(xAbs: 0, xRatio: 0.25, yAbs: 0, yRatio: 0.42),
      width: 204,
      height: 63,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="204" height="63" fill="none" viewBox="0 0 204 63"><path stroke="#2b2b2b" stroke-width="6" d="M.67 13c10.737-2.463 20.186-4.28 29-5.445m61 2.884c7.446 1.559 15.159 1.835 22.63.407l.371-.071m89 2.225c-10.736-2.463-20.186-4.28-29-5.445"/><path stroke="#2b2b2b" stroke-width="6" d="m28.876 38.431-3.488-20.168c-.972-5.618 2.506-11.095 8.076-12.318 20.043-4.403 33.764-3.939 52.262 1.862 4.725 1.483 7.668 6.125 7.27 11.061l-1.393 17.226C90.51 49.598 79.235 60 65.687 60H54.496c-12.65 0-23.464-9.104-25.62-21.569ZM174.465 38.431l3.488-20.168c.972-5.618-2.506-11.095-8.075-12.318-20.043-4.403-33.765-3.939-52.262 1.862-4.726 1.483-7.669 6.125-7.27 11.061l1.393 17.226C112.83 49.598 124.107 60 137.654 60h11.191c12.65 0 23.464-9.104 25.62-21.569Z"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "stylish",
      layer: 60,
      position: ItemPosition(xAbs: 0, xRatio: 0.25, yAbs: 0, yRatio: 0.43),
      width: 204,
      height: 55,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="204" height="55" fill="none" viewBox="0 0 204 55"><path stroke="#2b2b2b" stroke-width="6" d="M.67 10C33.464 2.478 54.256.976 81.596 5.698c13.487 2.33 27.261 2.533 40.771.343 28.38-4.598 48.865-3.346 80.305 3.959"/><path stroke="#2b2b2b" stroke-width="6" d="m23.67 5 4.917 25.856C30.919 43.123 41.642 52 54.129 52h13.542c14.36 0 26-11.64 26-26V6.979M180.671 5l-4.916 25.856C173.422 43.123 162.699 52 150.212 52h-13.541c-14.36 0-26-11.64-26-26V6.979"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "none",
      layer: 0,
      position: ItemPosition(xAbs: 0, xRatio: 0, yAbs: 0, yRatio: 0),
      width: 0,
      height: 0,
      fragments: []
    )
  ]
}
