// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

/// Item identifiers for the ashleyy theme.
public enum Ashleyy {
  public enum Accessories: String, CaseIterable, Sendable {
    case `none`
    case earrings
    case mask
  }

  public enum Body: String, CaseIterable, Sendable {
    case buttonShirt
    case doubleCollarShirt
    case knitSweater
    case peterPanCollarShirt
    case polkaDotShirt
    case tieShirt
    case turtleneckShirt
  }

  public enum Eyes: String, CaseIterable, Sendable {
    case standard
  }

  public enum Glasses: String, CaseIterable, Sendable {
    case `none`
    case glasses
  }

  public enum Hair: String, CaseIterable, Sendable {
    case afro
    case curlyBun
    case longWavy
    case mediumStraigh
    case ponyTail
    case shortCurly
    case short
    case sideSwept
  }

  public enum Head: String, CaseIterable, Sendable {
    case standard
  }

  public enum Mouth: String, CaseIterable, Sendable {
    case smile
    case standard
  }

  public enum Nose: String, CaseIterable, Sendable {
    case standard
  }
}
