// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

/// Namespace for the ashleyy theme's generated data.
public enum AshleyyTheme {}

extension AvatuneTheme {
  /// The ashleyy theme, generated from @avatune/ashleyy-theme@1.1.1.
  public static let ashleyy: AvatuneTheme = AvatuneTheme(
    name: "ashleyy",
    style: AvatuneTheme.Style(size: 400, borderRadius: .percent(100)),
    backgroundPalette: [.hex(0xE5ECF9), .hex(0xE3F0DF), .hex(0xFAE5E3), .hex(0xFFFCF5)],
    categories: [
      AvatuneTheme.Category(
        category: .accessories,
        palette: [.hex(0xF4D150)],
        items: AshleyyTheme.accessoriesItems
      ),
      AvatuneTheme.Category(
        category: .body,
        palette: [.hex(0x9287FF), .hex(0x6BD9E9), .hex(0xFC909F), .hex(0xA2BFF8), .hex(0xEB8682), .hex(0xF1CF73)],
        items: AshleyyTheme.bodyItems
      ),
      AvatuneTheme.Category(
        category: .eyes,
        palette: [.hex(0x000000)],
        items: AshleyyTheme.eyesItems
      ),
      AvatuneTheme.Category(
        category: .glasses,
        palette: [.hex(0x000000)],
        items: AshleyyTheme.glassesItems
      ),
      AvatuneTheme.Category(
        category: .hair,
        palette: [.hex(0x000000), .hex(0xF4D150), .hex(0x8CB2A5), .hex(0xFC909F), .hex(0x6BD9E9)],
        items: AshleyyTheme.hairItems
      ),
      AvatuneTheme.Category(
        category: .head,
        palette: [.hex(0xFDCDAC), .hex(0xC78A5C), .hex(0x80502E), .hex(0xA2BFF8), .hex(0xEB8682), .hex(0xF1CF73)],
        items: AshleyyTheme.headItems
      ),
      AvatuneTheme.Category(
        category: .mouth,
        palette: [.hex(0x000000)],
        items: AshleyyTheme.mouthItems
      ),
      AvatuneTheme.Category(
        category: .nose,
        palette: [.hex(0x000000)],
        items: AshleyyTheme.noseItems
      )
    ],
    connectedColors: [],
    predictorMappings: AvatuneTheme.PredictorMappings(
      hair: ["long": ["longWavy", "ponyTail"], "medium": ["mediumStraigh"], "short": ["shortCurly", "short"]],
      hairColor: ["black": [.hex(0x000000)], "blond": [.hex(0xF1CF73)], "brown": [.hex(0x000000)], "gray": [.hex(0xFFFCF5)]],
      skinTone: ["dark": [.hex(0x80502E)], "light": [.hex(0xFDCDAC)], "medium": [.hex(0xC78A5C)]]
    )
  )
}
