import {
  accessoriesBeautyMark,
  accessoriesCap,
  accessoriesEarpieceLeft,
  accessoriesEarringRight,
  accessoriesGlassesRound,
  accessoriesGlassesSquare,
  accessoriesHeadsetMic,
  accessoriesMask,
  accessoriesVisorGlasses,
  bodyHoodie,
  bodyJacket,
  bodyScarfTop,
  bodyShirtTie,
  bodyStripedOverall,
  bodySuit,
  bodyTurtleneck,
  eyebrowsBrowAngled,
  eyebrowsBrowFlat,
  eyebrowsBrowRaised,
  eyebrowsBrowSoft,
  eyebrowsBrowThick,
  eyebrowsBrowThin,
  eyesEyesFocused,
  eyesEyesHappy,
  eyesEyesNeutral,
  eyesEyesSurprised,
  eyesEyesWide,
  faceHairBeard,
  faceHairMustache,
  hairCurlyPuff,
  hairCurlyTop,
  hairCurvedLong,
  hairDoubleBuns,
  hairLongBraid,
  hairLongStraight,
  hairLongWave,
  hairLowBun,
  hairShortCurly,
  hairShortFlip,
  hairShortMessy,
  hairShortWave,
  hairSidePonytail,
  hairSideSweep,
  hairSpiky,
  hairTightCurls,
  hairVolumized,
  headDiamond,
  headHeart,
  headOval,
  headPear,
  headRound,
  headSquare,
  headThin,
  headTriangle,
  headWide,
  mouthNeutralLine,
  mouthSmileSmall,
  mouthSmileSoft,
  mouthSmirkLeft,
  mouthSmirkRight,
  mouthTinyDot,
  nosesNoseCurve,
  nosesNoseLong,
  nosesNosePointy,
  nosesNoseRound,
  nosesNoseSmall,
  nosesNoseSoft,
} from '@avatune/fatin-verse-assets'
import type { VanillaAvatarItem } from '@avatune/types'
import shared from './shared'

export default shared
  .toFramework<VanillaAvatarItem>()
  .withComponents('accessories', {
    beautyMark: { code: accessoriesBeautyMark },
    cap: { code: accessoriesCap },
    earpieceLeft: { code: accessoriesEarpieceLeft },
    earringRight: { code: accessoriesEarringRight },
    headsetMic: { code: accessoriesHeadsetMic },
    mask: { code: accessoriesMask },
  })
  .withComponents('glasses', {
    glassesRound: { code: accessoriesGlassesRound },
    glassesSquare: { code: accessoriesGlassesSquare },
    visorGlasses: { code: accessoriesVisorGlasses },
  })
  .withComponents('hair', {
    curlyPuff: { code: hairCurlyPuff },
    curlyTop: { code: hairCurlyTop },
    curvedLong: { code: hairCurvedLong },
    doubleBuns: { code: hairDoubleBuns },
    longBraid: { code: hairLongBraid },
    longStraight: { code: hairLongStraight },
    longWave: { code: hairLongWave },
    lowBun: { code: hairLowBun },
    shortCurly: { code: hairShortCurly },
    shortFlip: { code: hairShortFlip },
    shortMessy: { code: hairShortMessy },
    shortWave: { code: hairShortWave },
    sidePonytail: { code: hairSidePonytail },
    sideSweep: { code: hairSideSweep },
    spiky: { code: hairSpiky },
    tightCurls: { code: hairTightCurls },
    volumized: { code: hairVolumized },
  })
  .withComponents('body', {
    hoodie: { code: bodyHoodie },
    jacket: { code: bodyJacket },
    scarfTop: { code: bodyScarfTop },
    shirtTie: { code: bodyShirtTie },
    stripedOverall: { code: bodyStripedOverall },
    suit: { code: bodySuit },
    turtleneck: { code: bodyTurtleneck },
  })
  .withComponents('eyes', {
    eyesFocused: { code: eyesEyesFocused },
    eyesHappy: { code: eyesEyesHappy },
    eyesNeutral: { code: eyesEyesNeutral },
    eyesSurprised: { code: eyesEyesSurprised },
    eyesWide: { code: eyesEyesWide },
  })
  .withComponents('eyebrows', {
    browAngled: { code: eyebrowsBrowAngled },
    browFlat: { code: eyebrowsBrowFlat },
    browRaised: { code: eyebrowsBrowRaised },
    browSoft: { code: eyebrowsBrowSoft },
    browThick: { code: eyebrowsBrowThick },
    browThin: { code: eyebrowsBrowThin },
  })
  .withComponents('faceHair', {
    beard: { code: faceHairBeard },
    mustache: { code: faceHairMustache },
  })
  .withComponents('head', {
    diamond: { code: headDiamond },
    heart: { code: headHeart },
    oval: { code: headOval },
    pear: { code: headPear },
    round: { code: headRound },
    square: { code: headSquare },
    thin: { code: headThin },
    triangle: { code: headTriangle },
    wide: { code: headWide },
  })
  .withComponents('mouth', {
    neutralLine: { code: mouthNeutralLine },
    smileSmall: { code: mouthSmileSmall },
    smileSoft: { code: mouthSmileSoft },
    smirkLeft: { code: mouthSmirkLeft },
    smirkRight: { code: mouthSmirkRight },
    tinyDot: { code: mouthTinyDot },
  })
  .withComponents('noses', {
    noseCurve: { code: nosesNoseCurve },
    noseLong: { code: nosesNoseLong },
    nosePointy: { code: nosesNosePointy },
    noseRound: { code: nosesNoseRound },
    noseSmall: { code: nosesNoseSmall },
    noseSoft: { code: nosesNoseSoft },
  })
  .build()

