// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

extension YanliuTheme {
  static let mouthItems: [ItemDescriptor] = [
    ItemDescriptor(
      key: "smile",
      layer: 22,
      position: ItemPosition(xAbs: 0, xRatio: 0.46, yAbs: 0, yRatio: 0.57),
      width: 22,
      height: 9,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="22" height="9" fill="none" viewBox="0 0 22 9"><path stroke=""#,
            #"" stroke-linecap="round" stroke-linejoin="round" stroke-width="4" d="M2 2c3 3.667 10.8 8.8 18 0"/></svg>"#,
          ],
          slots: [.themeColor],
        )
      ]
    )
  ]
}
