// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

extension YanliuTheme {
  static let faceHairItems: [ItemDescriptor] = [
    ItemDescriptor(
      key: "bigBeard",
      layer: 30,
      position: ItemPosition(xAbs: 0, xRatio: 0.30560000000000004, yAbs: 0, yRatio: 0.4556),
      width: 136,
      height: 109,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="136" height="109" fill="none" viewBox="0 0 136 109"><path fill=""#,
            ##"" d="M20.547 25.832C13.102 21.81 9.105 16.5 5.07 7.92c-.837-1.78-3.367-1.529-3.63.42C-1.655 31.263-6.552 108.5 67.963 108.5c73.474 0 69.74-76.504 66.654-101.03-.256-2.039-2.98-2.25-3.808-.369-3.395 7.71-7.969 12.927-17.582 18.242-3.911 2.163-8.61 2.153-12.79.573-25.556-9.656-42.294-10.022-67.972.1-3.873 1.527-8.255 1.795-11.918-.184"/><ellipse cx="69.463" cy="43.5" fill="#fff" rx="17" ry="12"/><path stroke=""##,
            #"" stroke-linecap="round" stroke-linejoin="round" stroke-width="4" d="M60.463 41.5c3 3.667 10.8 8.8 18 0"/></svg>"#,
          ],
          slots: [.themeColor, .themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "chevronMustache",
      layer: 30,
      position: ItemPosition(xAbs: 0, xRatio: 0.39, yAbs: 0, yRatio: 0.535),
      width: 76,
      height: 34,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="76" height="34" fill="none" viewBox="0 0 76 34"><path fill=""#,
            #"" d="M13 33.5 0 29l1.678-9.23C3.634 9.012 12.614.843 23.538.348c10.21-.463 18.66-.464 28.285-.004 10.278.49 18.856 7.873 21.352 17.855L75.5 27.5l-14.5 6-.988-8.694A15 15 0 0 0 45.108 11.5H29.093a15 15 0 0 0-14.862 12.973z"/></svg>"#,
          ],
          slots: [.themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "mustache",
      layer: 30,
      position: ItemPosition(xAbs: 0, xRatio: 0.41, yAbs: 0, yRatio: 0.54),
      width: 60,
      height: 25,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="60" height="25" fill="none" viewBox="0 0 60 25"><path fill=""#,
            #"" d="M0 19.494C0 8.728 8.728 0 19.494 0h21.012C51.272 0 60 8.728 60 19.494c0 1.542-.85 2.96-2.212 3.685l-1.759.939a7.5 7.5 0 0 1-7.058 0L48.75 24a7.97 7.97 0 0 0-7.5 0 7.97 7.97 0 0 1-7.5 0 7.97 7.97 0 0 0-7.5 0 7.97 7.97 0 0 1-7.5 0 7.97 7.97 0 0 0-7.5 0l-.22.118a7.5 7.5 0 0 1-7.06 0l-1.759-.939A4.18 4.18 0 0 1 0 19.494"/></svg>"#,
          ],
          slots: [.themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "none",
      layer: 0,
      position: ItemPosition(xAbs: 0, xRatio: 0, yAbs: 0, yRatio: 0),
      width: 0,
      height: 0,
      fragments: []
    )
  ]
}
