// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

extension YanliuTheme {
  static let faceDetailsItems: [ItemDescriptor] = [
    ItemDescriptor(
      key: "blushes",
      layer: 25,
      position: ItemPosition(xAbs: 0, xRatio: 0.3167, yAbs: 0, yRatio: 0.4611),
      width: 122,
      height: 35,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="122" height="35" fill="none" viewBox="0 0 122 35"><g><ellipse cx="21.5" cy="17.5" fill=""#,
            #"" rx="9.5" ry="5.5"/></g><defs><filter id="a0" width="43" height="35" x="0" y="0" color-interpolation-filters="sRGB" filterUnits="userSpaceOnUse"><feFlood flood-opacity="0" result="BackgroundImageFix"/><feBlend in="SourceGraphic" in2="BackgroundImageFix" result="shape"/><feGaussianBlur result="effect1_foregroundBlur_23_2184" stdDeviation="6"/></filter><filter id="a1" width="43" height="35" x="79" y="0" color-interpolation-filters="sRGB" filterUnits="userSpaceOnUse"><feFlood flood-opacity="0" result="BackgroundImageFix"/><feBlend in="SourceGraphic" in2="BackgroundImageFix" result="shape"/><feGaussianBlur result="effect1_foregroundBlur_23_2184" stdDeviation="6"/></filter></defs></svg>"#,
          ],
          slots: [.themeColor],
          effects: [.blur(stdDeviation: 0)],
        ),
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="122" height="35" fill="none" viewBox="0 0 122 35"><g><ellipse cx="100.5" cy="17.5" fill=""#,
            #"" rx="9.5" ry="5.5"/></g><defs><filter id="a0" width="43" height="35" x="0" y="0" color-interpolation-filters="sRGB" filterUnits="userSpaceOnUse"><feFlood flood-opacity="0" result="BackgroundImageFix"/><feBlend in="SourceGraphic" in2="BackgroundImageFix" result="shape"/><feGaussianBlur result="effect1_foregroundBlur_23_2184" stdDeviation="6"/></filter><filter id="a1" width="43" height="35" x="79" y="0" color-interpolation-filters="sRGB" filterUnits="userSpaceOnUse"><feFlood flood-opacity="0" result="BackgroundImageFix"/><feBlend in="SourceGraphic" in2="BackgroundImageFix" result="shape"/><feGaussianBlur result="effect1_foregroundBlur_23_2184" stdDeviation="6"/></filter></defs></svg>"#,
          ],
          slots: [.themeColor],
          effects: [.blur(stdDeviation: 0)],
        )
      ]
    ),
    ItemDescriptor(
      key: "none",
      layer: 0,
      position: ItemPosition(xAbs: 0, xRatio: 0, yAbs: 0, yRatio: 0),
      width: 0,
      height: 0,
      fragments: []
    )
  ]
}
