// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

extension YanliuTheme {
  static let hatsItems: [ItemDescriptor] = [
    ItemDescriptor(
      key: "beanie",
      layer: 60,
      position: ItemPosition(xAbs: 0, xRatio: 0.2944, yAbs: 0, yRatio: 0.1),
      width: 148,
      height: 88,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="148" height="88" fill="none" viewBox="0 0 148 88"><path fill=""#,
            #"" d="M139 67c0-17.77-6.796-34.811-18.892-47.376S91.606 0 74.5 0 40.988 7.059 28.892 19.624 10 49.23 10 67z"/><defs><filter id="a0" width="147" height="31" x="0" y="49" color-interpolation-filters="sRGB" filterUnits="userSpaceOnUse"><feFlood flood-opacity="0" result="BackgroundImageFix"/><feBlend in="SourceGraphic" in2="BackgroundImageFix" result="shape"/><feGaussianBlur result="effect1_foregroundBlur_24_335" stdDeviation="6"/></filter></defs></svg>"#,
          ],
          slots: [.themeColor],
        ),
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="148" height="88" fill="none" viewBox="0 0 148 88"><g><path fill="#1a1a1a" fill-opacity=".65" d="M12 61h123v7H12z"/></g><defs><filter id="a0" width="147" height="31" x="0" y="49" color-interpolation-filters="sRGB" filterUnits="userSpaceOnUse"><feFlood flood-opacity="0" result="BackgroundImageFix"/><feBlend in="SourceGraphic" in2="BackgroundImageFix" result="shape"/><feGaussianBlur result="effect1_foregroundBlur_24_335" stdDeviation="6"/></filter></defs></svg>"##,
          ],
          slots: [],
          effects: [.blur(stdDeviation: 0)],
        ),
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="148" height="88" fill="none" viewBox="0 0 148 88"><rect width="147" height="23" x="1" y="65" fill=""#,
            #"" rx="11.5"/><defs><filter id="a0" width="147" height="31" x="0" y="49" color-interpolation-filters="sRGB" filterUnits="userSpaceOnUse"><feFlood flood-opacity="0" result="BackgroundImageFix"/><feBlend in="SourceGraphic" in2="BackgroundImageFix" result="shape"/><feGaussianBlur result="effect1_foregroundBlur_24_335" stdDeviation="6"/></filter></defs></svg>"#,
          ],
          slots: [.themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "hat",
      layer: 60,
      position: ItemPosition(xAbs: 0, xRatio: 0.24, yAbs: 0, yRatio: 0.09),
      width: 191,
      height: 108,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="191" height="108" fill="none" viewBox="0 0 191 108"><g><path fill="#1a1a1a" fill-opacity=".55" d="M28 80.088h134v13H28z"/></g><defs><filter id="a0" width="158" height="37" x="16" y="68.088" color-interpolation-filters="sRGB" filterUnits="userSpaceOnUse"><feFlood flood-opacity="0" result="BackgroundImageFix"/><feBlend in="SourceGraphic" in2="BackgroundImageFix" result="shape"/><feGaussianBlur result="effect1_foregroundBlur_24_319" stdDeviation="6"/></filter><filter id="a1" width="158" height="35" x="16" y="56.088" color-interpolation-filters="sRGB" filterUnits="userSpaceOnUse"><feFlood flood-opacity="0" result="BackgroundImageFix"/><feBlend in="SourceGraphic" in2="BackgroundImageFix" result="shape"/><feGaussianBlur result="effect1_foregroundBlur_24_319" stdDeviation="6"/></filter><filter id="a2" width="191" height="43" x="0" y="64.088" color-interpolation-filters="sRGB" filterUnits="userSpaceOnUse"><feFlood flood-opacity="0" result="BackgroundImageFix"/><feColorMatrix in="SourceAlpha" result="hardAlpha" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"/><feOffset dy="4"/><feGaussianBlur stdDeviation="6"/><feColorMatrix values="0 0 0 0 0.101961 0 0 0 0 0.101961 0 0 0 0 0.101961 0 0 0 0.25 0"/><feBlend in2="BackgroundImageFix" result="effect1_dropShadow_24_319"/><feBlend in="SourceGraphic" in2="effect1_dropShadow_24_319" result="shape"/></filter></defs></svg>"##,
          ],
          slots: [],
          effects: [.blur(stdDeviation: 0)],
        ),
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="191" height="108" fill="none" viewBox="0 0 191 108"><path fill=""#,
            #"" d="M27.39 40.735C27.39 17.27 47.49-.925 70.936.04c16.293.671 31.394.676 47.902-.004 23.447-.966 43.554 17.236 43.554 40.703v36.348h-135z"/><defs><filter id="a0" width="158" height="37" x="16" y="68.088" color-interpolation-filters="sRGB" filterUnits="userSpaceOnUse"><feFlood flood-opacity="0" result="BackgroundImageFix"/><feBlend in="SourceGraphic" in2="BackgroundImageFix" result="shape"/><feGaussianBlur result="effect1_foregroundBlur_24_319" stdDeviation="6"/></filter><filter id="a1" width="158" height="35" x="16" y="56.088" color-interpolation-filters="sRGB" filterUnits="userSpaceOnUse"><feFlood flood-opacity="0" result="BackgroundImageFix"/><feBlend in="SourceGraphic" in2="BackgroundImageFix" result="shape"/><feGaussianBlur result="effect1_foregroundBlur_24_319" stdDeviation="6"/></filter><filter id="a2" width="191" height="43" x="0" y="64.088" color-interpolation-filters="sRGB" filterUnits="userSpaceOnUse"><feFlood flood-opacity="0" result="BackgroundImageFix"/><feColorMatrix in="SourceAlpha" result="hardAlpha" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"/><feOffset dy="4"/><feGaussianBlur stdDeviation="6"/><feColorMatrix values="0 0 0 0 0.101961 0 0 0 0 0.101961 0 0 0 0 0.101961 0 0 0 0.25 0"/><feBlend in2="BackgroundImageFix" result="effect1_dropShadow_24_319"/><feBlend in="SourceGraphic" in2="effect1_dropShadow_24_319" result="shape"/></filter></defs></svg>"#,
          ],
          slots: [.themeColor],
        ),
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="191" height="108" fill="none" viewBox="0 0 191 108"><g><path fill="#1a1a1a" fill-opacity=".45" d="M28 68.088h134v11H28z"/></g><defs><filter id="a0" width="158" height="37" x="16" y="68.088" color-interpolation-filters="sRGB" filterUnits="userSpaceOnUse"><feFlood flood-opacity="0" result="BackgroundImageFix"/><feBlend in="SourceGraphic" in2="BackgroundImageFix" result="shape"/><feGaussianBlur result="effect1_foregroundBlur_24_319" stdDeviation="6"/></filter><filter id="a1" width="158" height="35" x="16" y="56.088" color-interpolation-filters="sRGB" filterUnits="userSpaceOnUse"><feFlood flood-opacity="0" result="BackgroundImageFix"/><feBlend in="SourceGraphic" in2="BackgroundImageFix" result="shape"/><feGaussianBlur result="effect1_foregroundBlur_24_319" stdDeviation="6"/></filter><filter id="a2" width="191" height="43" x="0" y="64.088" color-interpolation-filters="sRGB" filterUnits="userSpaceOnUse"><feFlood flood-opacity="0" result="BackgroundImageFix"/><feColorMatrix in="SourceAlpha" result="hardAlpha" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"/><feOffset dy="4"/><feGaussianBlur stdDeviation="6"/><feColorMatrix values="0 0 0 0 0.101961 0 0 0 0 0.101961 0 0 0 0 0.101961 0 0 0 0.25 0"/><feBlend in2="BackgroundImageFix" result="effect1_dropShadow_24_319"/><feBlend in="SourceGraphic" in2="effect1_dropShadow_24_319" result="shape"/></filter></defs></svg>"##,
          ],
          slots: [],
          effects: [.blur(stdDeviation: 0)],
        ),
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="191" height="108" fill="none" viewBox="0 0 191 108"><g><rect width="167" height="19" x="12" y="72.088" fill=""#,
            #"" rx="4"/></g><defs><filter id="a0" width="158" height="37" x="16" y="68.088" color-interpolation-filters="sRGB" filterUnits="userSpaceOnUse"><feFlood flood-opacity="0" result="BackgroundImageFix"/><feBlend in="SourceGraphic" in2="BackgroundImageFix" result="shape"/><feGaussianBlur result="effect1_foregroundBlur_24_319" stdDeviation="6"/></filter><filter id="a1" width="158" height="35" x="16" y="56.088" color-interpolation-filters="sRGB" filterUnits="userSpaceOnUse"><feFlood flood-opacity="0" result="BackgroundImageFix"/><feBlend in="SourceGraphic" in2="BackgroundImageFix" result="shape"/><feGaussianBlur result="effect1_foregroundBlur_24_319" stdDeviation="6"/></filter><filter id="a2" width="191" height="43" x="0" y="64.088" color-interpolation-filters="sRGB" filterUnits="userSpaceOnUse"><feFlood flood-opacity="0" result="BackgroundImageFix"/><feColorMatrix in="SourceAlpha" result="hardAlpha" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"/><feOffset dy="4"/><feGaussianBlur stdDeviation="6"/><feColorMatrix values="0 0 0 0 0.101961 0 0 0 0 0.101961 0 0 0 0 0.101961 0 0 0 0.25 0"/><feBlend in2="BackgroundImageFix" result="effect1_dropShadow_24_319"/><feBlend in="SourceGraphic" in2="effect1_dropShadow_24_319" result="shape"/></filter></defs></svg>"#,
          ],
          slots: [.themeColor],
          effects: [.dropShadow(dx: 0, dy: 4, stdDeviation: 0, color: AvatuneColor(red: 26.000055, green: 26.000055, blue: 26.000055, alpha: 0.25))],
        )
      ]
    ),
    ItemDescriptor(
      key: "none",
      layer: 0,
      position: ItemPosition(xAbs: 0, xRatio: 0, yAbs: 0, yRatio: 0),
      width: 0,
      height: 0,
      fragments: []
    )
  ]
}
