// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

extension YanliuTheme {
  static let neckItems: [ItemDescriptor] = [
    ItemDescriptor(
      key: "standard",
      layer: 8,
      position: ItemPosition(xAbs: 0, xRatio: 0.4, yAbs: 0, yRatio: 0.4389),
      width: 73,
      height: 133,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="73" height="133" fill="none" viewBox="0 0 73 133"><rect width="68.214" height="128.131" x="2" y="2" fill="#fff" stroke=""##,
            ##"" stroke-linecap="round" stroke-width="4" rx="13.777"/><path fill="#7e7e7e" fill-opacity=".45" d="M3.896 84.634V43.678H72.5C67.333 64.68 36.524 85.768 3.896 84.634"/></svg>"##,
          ],
          slots: [.themeColor],
        )
      ]
    )
  ]
}
