// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

extension YanliuTheme {
  static let headItems: [ItemDescriptor] = [
    ItemDescriptor(
      key: "standard",
      layer: 10,
      position: ItemPosition(xAbs: 0, xRatio: 0.30560000000000004, yAbs: 0, yRatio: 0.2167),
      width: 137,
      height: 166,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="137" height="166" fill="none" viewBox="0 0 137 166"><path fill="#fff" stroke=""##,
            #"" stroke-linecap="round" stroke-width="4" d="M69.03 2c21.013 0 37.443 11.893 48.71 29.611C129.026 49.358 135 72.787 135 95.261c0 22.452-5.958 39.573-17.015 51.076C106.941 157.828 90.533 164 69.03 164c-21.504 0-38.188-6.174-49.502-17.68C8.211 134.81 2 117.69 2 95.262c0-22.458 6.232-45.883 17.78-63.633C31.31 13.903 48.01 2 69.03 2Z"/></svg>"#,
          ],
          slots: [.themeColor],
        )
      ]
    )
  ]
}
