// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

extension YanliuTheme {
  static let glassesItems: [ItemDescriptor] = [
    ItemDescriptor(
      key: "glass",
      layer: 50,
      position: ItemPosition(xAbs: 0, xRatio: 0.30889999999999995, yAbs: 0, yRatio: 0.3722),
      width: 134,
      height: 60,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="134" height="60" fill="none" viewBox="0 0 134 60"><path stroke=""#,
            #"" stroke-linecap="round" stroke-width="4" d="M55.894 26.61c9.277-3.705 14.32-3.797 23 0"/><path stroke=""#,
            ##"" stroke-width="4" d="m9.284 21.8-7.89-7.665M123.333 17.44l8.56-3.805"/><path fill="#fff" fill-opacity=".15" fill-rule="evenodd" d="m34.053 4.07 3.586 3.587L7.941 37.355l-1.402-1.402a25.7 25.7 0 0 1-.73-7.78L29.942 4.041a26 26 0 0 1 4.111.03" clip-rule="evenodd"/><path fill="url(#a0)" fill-opacity=".3" stroke=""##,
            ##"" stroke-width="4" d="M27.724 6.32c13.05-2.22 25.373 6.45 27.56 19.311C57.474 38.493 48.71 50.75 35.66 52.97S10.287 46.521 8.1 33.659C5.91 20.797 14.674 8.54 27.724 6.32Z"/><path fill="#fff" fill-opacity=".15" fill-rule="evenodd" d="M129.17 30.612a25.5 25.5 0 0 0-.443-5.868l-2.502-2.501-31.161 31.161.901.901a26 26 0 0 0 8.536.975z" clip-rule="evenodd"/><path fill="url(#a1)" fill-opacity=".3" stroke=""##,
            ##"" stroke-width="4" d="M99.294 6.32c13.05-2.22 25.373 6.45 27.561 19.311S120.28 50.75 107.23 52.97s-25.373-6.448-27.561-19.31S86.244 8.54 99.294 6.32Z"/><defs><linearGradient id="a0" x1="27.388" x2="51.394" y1="4.349" y2="53.635" gradientUnits="userSpaceOnUse"><stop stop-color="#fff"/><stop offset="1" stop-color="#c0c8fe" stop-opacity="0"/></linearGradient><linearGradient id="a1" x1="98.959" x2="122.964" y1="4.349" y2="53.635" gradientUnits="userSpaceOnUse"><stop stop-color="#fff"/><stop offset="1" stop-color="#c0c8fe" stop-opacity="0"/></linearGradient></defs></svg>"##,
          ],
          slots: [.themeColor, .themeColor, .themeColor, .themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "none",
      layer: 0,
      position: ItemPosition(xAbs: 0, xRatio: 0, yAbs: 0, yRatio: 0),
      width: 0,
      height: 0,
      fragments: []
    )
  ]
}
