// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

extension YanliuTheme {
  static let hairItems: [ItemDescriptor] = [
    ItemDescriptor(
      key: "braids",
      layer: 2,
      position: ItemPosition(xAbs: 0, xRatio: 0.08, yAbs: 0, yRatio: 0.15),
      width: 298,
      height: 289,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="298" height="289" fill="none" viewBox="0 0 298 289"><path fill=""#,
            #"" fill-rule="evenodd" d="M243.7 166.17c8.137-15.784 12.462-34.923 12.462-57.348C256.162 46.212 217.335 0 157.035 0S47.853 50.756 47.853 113.367c0 19.814 6.219 38.59 16.503 54.687-12.498 5.433-20.584 18.516-19.047 32.781q.046.422.102.841c-12.232 4.464-20.325 16.821-18.867 30.349a29 29 0 0 0 2.198 8.384l-22.498 9.123c-7.102 2.88-8.458 12.351-2.449 17.108l24.684 19.539c6.009 4.757 14.915 1.264 16.088-6.31L48.11 257a28.9 28.9 0 0 0 10.375.75c14.996-1.616 26.084-14.392 25.893-29.174 10.928-2.528 19.492-10.554 23.011-20.747 18.334 9.731 38.935 13.99 58.807 10.493 11.738-2.065 22.494-5.31 32.168-9.722 4.397 7.898 12.065 13.813 21.344 15.766.102 14.784 11.442 27.337 26.466 28.655q1.696.148 3.356.102l3.698 21.096c1.323 7.548 10.297 10.864 16.211 5.989l24.29-20.026c5.914-4.875 4.37-14.317-2.788-17.055l-16.2-6.198a28.9 28.9 0 0 0 2.857-10.263c1.189-13.554-7.148-25.747-19.466-29.968q.048-.42.085-.843c1.073-12.228-4.88-23.452-14.516-29.685" clip-rule="evenodd"/></svg>"#,
          ],
          slots: [.themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "hijab",
      layer: 40,
      position: ItemPosition(xAbs: 0, xRatio: 0.18, yAbs: 0, yRatio: 0.15),
      width: 228,
      height: 342,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="228" height="342" fill="none" viewBox="0 0 228 342"><path fill=""#,
            #"" fill-rule="evenodd" d="M115.376 245c56.886 0 103-56.86 103-127s-46.114-118-103-118c-56.885 0-103 47.86-103 118s46.115 127 103 127m-2-56c37.003 0 67-32.012 67-71.5s-29.997-71.5-67-71.5-67 32.012-67 71.5 29.997 71.5 67 71.5" clip-rule="evenodd"/><defs><filter id="a0" width="227.084" height="162.163" x="0" y="179" color-interpolation-filters="sRGB" filterUnits="userSpaceOnUse"><feFlood flood-opacity="0" result="BackgroundImageFix"/><feColorMatrix in="SourceAlpha" result="hardAlpha" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"/><feOffset dy="2"/><feGaussianBlur stdDeviation="6"/><feColorMatrix values="0 0 0 0 0.0784314 0 0 0 0 0.137255 0 0 0 0 0.490196 0 0 0 0.16 0"/><feBlend in2="BackgroundImageFix" result="effect1_dropShadow_22_3268"/><feBlend in="SourceGraphic" in2="effect1_dropShadow_22_3268" result="shape"/></filter></defs></svg>"#,
          ],
          slots: [.themeColor],
        ),
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="228" height="342" fill="none" viewBox="0 0 228 342"><g><path fill=""#,
            #"" d="M48.93 189c-14.3 0-25.893 14.327-25.893 32.001 0 2.867.307 5.656.885 8.314-4.691 6.454-12.838 10.185-11.838 25.185s32.5 68.054 56.5 71.5c58.398 8.386 56.976-31.042 105.5-39 14.521-2.381 41-14.898 41-33 0-10.388-6.176-19.604-11.76-26.317.321-2.029.489-4.121.489-6.254 0-17.91-11.748-32.429-26.241-32.429z"/></g><defs><filter id="a0" width="227.084" height="162.163" x="0" y="179" color-interpolation-filters="sRGB" filterUnits="userSpaceOnUse"><feFlood flood-opacity="0" result="BackgroundImageFix"/><feColorMatrix in="SourceAlpha" result="hardAlpha" values="0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 127 0"/><feOffset dy="2"/><feGaussianBlur stdDeviation="6"/><feColorMatrix values="0 0 0 0 0.0784314 0 0 0 0 0.137255 0 0 0 0 0.490196 0 0 0 0.16 0"/><feBlend in2="BackgroundImageFix" result="effect1_dropShadow_22_3268"/><feBlend in="SourceGraphic" in2="effect1_dropShadow_22_3268" result="shape"/></filter></defs></svg>"#,
          ],
          slots: [.themeColor],
          effects: [.dropShadow(dx: 0, dy: 2, stdDeviation: 0, color: AvatuneColor(red: 20.000007, green: 35.000025, blue: 124.99998, alpha: 0.16))],
        )
      ]
    ),
    ItemDescriptor(
      key: "medium",
      layer: 2,
      position: ItemPosition(xAbs: 0, xRatio: 0.13, yAbs: 0, yRatio: 0.18330000000000002),
      width: 271,
      height: 224,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="271" height="224" fill="none" viewBox="0 0 271 224"><path fill=""#,
            #"" d="M258.812 224c6.627 0 12.02-5.374 11.805-11.998-.821-25.316-4.237-50.247-10.12-73.723-6.809-27.177-16.79-51.87-29.372-72.67s-27.52-37.301-43.96-48.558C170.726 5.794 153.106 0 135.312 0S99.898 5.794 83.458 17.051s-31.377 27.757-43.96 48.557c-12.582 20.8-22.562 45.494-29.372 72.671C4.244 161.755.828 186.686.006 212.002-.209 218.626 5.184 224 11.812 224z"/></svg>"#,
          ],
          slots: [.themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "puff",
      layer: 2,
      position: ItemPosition(xAbs: 0, xRatio: 0.16, yAbs: 0, yRatio: 0.1056),
      width: 251,
      height: 226,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="251" height="226" fill="none" viewBox="0 0 251 226"><path fill=""#,
            #"" d="M92.55 225.356a4.8 4.8 0 0 0 1.196-.396l29.089-14.019a5 5 0 0 1 4.749.22l18.065 10.874a4.96 4.96 0 0 0 2.156.694c18.553 1.466 26.689-1.577 34.816-11.195 1.574-1.863 4.215-2.51 6.529-1.74 4.956 1.649 13.66 3.377 20.35-1.573 4.354-3.222 5.84-8.088 6.138-12.532.284-4.248 5.198-8.88 9.424-9.395 4.316-.526 9.261-2.507 13.438-7.794 5.697-7.211 5.519-14.227 4.349-18.874-.763-3.031.359-6.912 2.39-9.288 2.662-3.114 5.522-8.531 5.748-17.529.236-9.346-2.884-15.517-5.765-19.194-2.007-2.561-2.466-6.742-1.029-9.662 1.949-3.96 3.392-9.823.307-16.453-1.518-3.262-3.721-5.213-6.132-6.322-4.369-2.01-10.87-9.328-10.513-14.124.504-6.76-.794-15.266-7.05-24.068-8.926-12.558-20.697-16.157-28.2-17.099-3.51-.44-6.927-4.142-8.289-7.406-1.234-2.957-3.758-6.459-8.785-9.776-8.056-5.315-15.415-4.235-19.421-2.928-1.975.645-4.251.524-6.052-.512-4.456-2.56-13.663-6.642-24.789-4.804-10.108 1.669-17.368 9.664-21.277 15.188-1.871 2.645-5.861 3.543-8.847 2.284-5.28-2.226-14.142-4.234-25.685-.55-13.1 4.182-16.715 14.988-17.682 21.554-.422 2.863-2.776 5.397-5.618 5.942-5.88 1.127-15.608 4.309-23.7 13.294-8.924 9.912-9.148 22.965-8.537 29.661.23 2.519-1.157 5.1-3.138 6.674-3.501 2.781-8.447 8.544-10.314 19.642-1.408 8.37.558 14.255 3.057 18.152 2.127 3.316 2.327 9.562.37 12.982-1.86 3.25-3.427 7.82-3.427 13.995 0 6.501 2.584 10.737 5.54 13.455 3.002 2.762 5.256 9.558 5.796 13.601.407 3.045 1.999 6.789 5.91 11.129 6.193 6.87 12.922 7.147 17.76 5.978 3.446-.833 7.993.756 10.02 3.664a26.1 26.1 0 0 0 8.44 7.715c4.111 2.365 8.384 2.68 11.907 2.278 3.74-.427 7.916 2.628 10.433 5.427 3.204 3.563 9.193 4.144 16.273 2.83"/></svg>"#,
          ],
          slots: [.themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "straightLong",
      layer: 1,
      position: ItemPosition(xAbs: 0, xRatio: 0.21, yAbs: 0, yRatio: 0.1611),
      width: 213,
      height: 302,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="213" height="302" fill="none" viewBox="0 0 213 302"><path fill=""#,
            #"" d="M0 100C0 44.772 44.772 0 100 0h13c55.228 0 100 44.772 100 100v202H0z"/></svg>"#,
          ],
          slots: [.themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "straightMedium",
      layer: 2,
      position: ItemPosition(xAbs: 0, xRatio: 0.26, yAbs: 0, yRatio: 0.1611),
      width: 176,
      height: 213,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="176" height="213" fill="none" viewBox="0 0 176 213"><path fill=""#,
            #"" d="M0 88C0 39.399 39.399 0 88 0s88 39.399 88 88v97c0 15.464-12.536 28-28 28H28c-15.464 0-28-12.536-28-28z"/></svg>"#,
          ],
          slots: [.themeColor],
        )
      ]
    )
  ]
}
