// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

extension YanliuTheme {
  static let noseItems: [ItemDescriptor] = [
    ItemDescriptor(
      key: "standard",
      layer: 22,
      position: ItemPosition(xAbs: 0, xRatio: 0.47, yAbs: 0, yRatio: 0.47),
      width: 14,
      height: 23,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="14" height="23" fill="none" viewBox="0 0 14 23"><path stroke=""#,
            #"" stroke-linecap="round" stroke-linejoin="round" stroke-width="4" d="M5 2C3.03 8.812 2 12.371 2 19.458c2.64 1.263 5.163 1.578 9.5 1.543"/></svg>"#,
          ],
          slots: [.themeColor],
        )
      ]
    )
  ]
}
