// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

extension YanliuTheme {
  static let bodyItems: [ItemDescriptor] = [
    ItemDescriptor(
      key: "blouse",
      layer: 10,
      position: ItemPosition(xAbs: 0, xRatio: 0.17, yAbs: 0, yRatio: 0.7),
      width: 237,
      height: 116,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="237" height="116" fill="none" viewBox="0 0 237 116"><path fill="#fff" stroke=""##,
            #"" stroke-linecap="round" stroke-linejoin="round" stroke-width="4" d="M84.18 3.032c.458-.211 1.123-.043 1.457.534 16.144 27.974 55.237 25.784 67.427.255.332-.694 1.08-.9 1.559-.682 26.958 12.218 44.661 25.214 56.75 42.181 12.103 16.987 18.729 38.162 23.139 67.035a.996.996 0 0 1-.975 1.145H3.471a.994.994 0 0 1-.971-1.146c4.763-30.318 12.598-51.743 25.43-68.502 12.835-16.76 30.817-29.049 56.25-40.82"/><path stroke=""#,
            #"" stroke-linecap="round" stroke-width="4" d="m83 3.5 1.436 43.552a1 1 0 0 0 1.609.76L117 24M155 3.5l-1.436 43.552a1 1 0 0 1-1.609.76L121 24"/><path stroke=""#,
            #"" stroke-width="4" d="m119 24.477 1.011 87"/><circle cx="133" cy="59.5" r="6" fill=""#,
            #""/><circle cx="133" cy="89.5" r="6" fill=""#,
            #""/></svg>"#,
          ],
          slots: [.themeColor, .themeColor, .themeColor, .themeColor, .themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "flowerCardigan",
      layer: 10,
      position: ItemPosition(xAbs: 0, xRatio: 0.17, yAbs: 0, yRatio: 0.7),
      width: 237,
      height: 116,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="237" height="116" fill="none" viewBox="0 0 237 116"><path fill="#fff" stroke=""##,
            #"" stroke-linecap="round" stroke-linejoin="round" stroke-width="4" d="M84.18 3.032c.458-.211 1.123-.043 1.457.534 16.144 27.974 55.237 25.784 67.427.255.332-.694 1.08-.9 1.559-.682 26.958 12.218 44.661 25.214 56.75 42.181 12.103 16.987 18.729 38.162 23.139 67.035a.996.996 0 0 1-.975 1.145H3.471a.994.994 0 0 1-.971-1.146c4.763-30.318 12.598-51.743 25.43-68.502 12.835-16.76 30.817-29.049 56.25-40.82"/><path stroke=""#,
            #"" stroke-width="4" d="M85.5 4c4.393 42.359 5.447 67.359.5 108.5M154.776 4.5c-4.392 42.359-5.447 67.359-.5 108.5"/><path fill=""#,
            #"" fill-rule="evenodd" d="M191.966 56.402c-1.72-5.203-9.212-5.203-10.932 0l-.663 2.005c-.77 2.327-2.977 3.902-5.466 3.902h-2.147c-5.567 0-7.882 7-3.378 10.215l1.736 1.24c2.015 1.438 2.858 3.987 2.088 6.313l-.663 2.005c-1.72 5.203 4.34 9.53 8.845 6.314l1.736-1.24a5.83 5.83 0 0 1 6.756 0l1.736 1.24c4.505 3.215 10.565-1.11 8.845-6.314l-.663-2.005c-.77-2.326.073-4.875 2.088-6.313l1.736-1.24c4.504-3.215 2.189-10.215-3.378-10.215h-2.147c-2.489 0-4.696-1.575-5.466-3.902zM186.5 77.99c3.174 0 5.747-2.528 5.747-5.647s-2.573-5.647-5.747-5.647-5.747 2.528-5.747 5.647c0 3.118 2.573 5.647 5.747 5.647" clip-rule="evenodd"/></svg>"#,
          ],
          slots: [.themeColor, .themeColor, .themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "simpleCardigan",
      layer: 10,
      position: ItemPosition(xAbs: 0, xRatio: 0.17, yAbs: 0, yRatio: 0.7),
      width: 238,
      height: 116,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="238" height="116" fill="none" viewBox="0 0 238 116"><path fill="#fff" stroke=""##,
            #"" stroke-linecap="round" stroke-linejoin="round" stroke-width="4" d="M84.18 3.032c.458-.211 1.123-.043 1.457.534 16.144 27.974 55.237 25.784 67.427.255.332-.694 1.08-.9 1.559-.682 26.958 12.218 44.661 25.214 56.75 42.181 12.103 16.987 18.729 38.162 23.139 67.035a.996.996 0 0 1-.975 1.145H3.471a.994.994 0 0 1-.971-1.146c4.763-30.318 12.598-51.743 25.43-68.502 12.835-16.76 30.817-29.049 56.25-40.82"/><path fill=""#,
            #"" stroke=""#,
            #"" stroke-linecap="round" stroke-linejoin="round" stroke-width="4" d="M82.617 3.76A.973.973 0 0 1 84 4.65V112.5a1 1 0 0 1-1 1H3.47a.994.994 0 0 1-.97-1.146c4.714-30.006 12.437-51.3 25.035-67.982C40.132 27.692 57.75 15.433 82.617 3.761M155.383 3.76a.974.974 0 0 0-1.383.89V112.5a1 1 0 0 0 1 1h79.529a.994.994 0 0 0 .971-1.146c-4.714-30.006-12.437-51.3-25.035-67.982-12.597-16.68-30.214-28.939-55.082-40.611"/></svg>"#,
          ],
          slots: [.themeColor, .themeColor, .themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "simpleOverall",
      layer: 10,
      position: ItemPosition(xAbs: 0, xRatio: 0.17, yAbs: 0, yRatio: 0.7),
      width: 237,
      height: 116,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="237" height="116" fill="none" viewBox="0 0 237 116"><path fill="#fff" stroke=""##,
            #"" stroke-linecap="round" stroke-linejoin="round" stroke-width="4" d="M84.18 3.032c.458-.211 1.123-.043 1.457.534 16.144 27.974 55.237 25.784 67.427.255.332-.694 1.08-.9 1.559-.682 26.958 12.218 44.661 25.214 56.75 42.181 12.103 16.987 18.729 38.162 23.139 67.035a.996.996 0 0 1-.975 1.145H3.471a.994.994 0 0 1-.971-1.146c4.763-30.318 12.598-51.743 25.43-68.502 12.835-16.76 30.817-29.049 56.25-40.82"/><path stroke=""#,
            ##"" stroke-width="4" d="M57.838 17.178v59M72.838 10.178v59M177.838 15.178v61M162.838 7.178v61"/><path fill="#fff" stroke=""##,
            #"" stroke-width="4" d="M55.838 59.178h125c5.523 0 10 4.477 10 10v44h-145v-44c0-5.35 4.201-9.72 9.485-9.988z"/><circle cx="63.792" cy="74.647" r="9" fill=""#,
            #""/><circle cx="169.792" cy="74.647" r="9" fill=""#,
            #""/></svg>"#,
          ],
          slots: [.themeColor, .themeColor, .themeColor, .themeColor, .themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "striped",
      layer: 10,
      position: ItemPosition(xAbs: 0, xRatio: 0.17, yAbs: 0, yRatio: 0.7),
      width: 237,
      height: 116,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="237" height="116" fill="none" viewBox="0 0 237 116"><path fill="#fff" stroke=""##,
            #"" stroke-linecap="round" stroke-linejoin="round" stroke-width="4" d="M84.18 3.032c.458-.211 1.123-.043 1.457.534 16.144 27.974 55.237 25.784 67.427.255.332-.694 1.08-.9 1.559-.682 26.958 12.218 44.661 25.214 56.75 42.181 12.103 16.987 18.729 38.162 23.139 67.035a.996.996 0 0 1-.975 1.145H3.471a.994.994 0 0 1-.971-1.146c4.763-30.318 12.598-51.743 25.43-68.502 12.835-16.76 30.817-29.049 56.25-40.82"/><path stroke=""#,
            #"" stroke-opacity=".5" stroke-width="4" d="M39 32.178h160M22 53.178h194M12 74.178h213M4 95.178h227"/></svg>"#,
          ],
          slots: [.themeColor, .themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "sweaterVest",
      layer: 10,
      position: ItemPosition(xAbs: 0, xRatio: 0.17, yAbs: 0, yRatio: 0.7),
      width: 237,
      height: 116,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="237" height="116" fill="none" viewBox="0 0 237 116"><path fill="#fff" stroke=""##,
            #"" stroke-linecap="round" stroke-linejoin="round" stroke-width="4" d="M84.18 3.032c.458-.211 1.123-.043 1.457.534 16.144 27.974 55.237 25.784 67.427.255.332-.694 1.08-.9 1.559-.682 26.958 12.218 44.661 25.214 56.75 42.181 12.103 16.987 18.729 38.162 23.139 67.035a.996.996 0 0 1-.975 1.145H3.471a.994.994 0 0 1-.971-1.146c4.763-30.318 12.598-51.743 25.43-68.502 12.835-16.76 30.817-29.049 56.25-40.82"/><path fill=""#,
            #"" stroke=""#,
            #"" stroke-width="4" d="m118.851 57.834 1.683 2.457 1.637-2.49 34.555-52.563C173.564 13.03 182.111 18.78 197 31.618v78.085H41V31.621C55.894 18.814 65.805 13.054 82.804 5.225z"/></svg>"#,
          ],
          slots: [.themeColor, .themeColor, .themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "sweaterWavy",
      layer: 10,
      position: ItemPosition(xAbs: 0, xRatio: 0.17, yAbs: 0, yRatio: 0.7),
      width: 237,
      height: 116,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="237" height="116" fill="none" viewBox="0 0 237 116"><path fill="#fff" stroke=""##,
            #"" stroke-linecap="round" stroke-linejoin="round" stroke-width="4" d="M84.18 3.032c.458-.211 1.123-.043 1.457.534 16.144 27.974 55.237 25.784 67.427.255.332-.694 1.08-.9 1.559-.682 26.958 12.218 44.661 25.214 56.75 42.181 12.103 16.987 18.729 38.162 23.139 67.035a.996.996 0 0 1-.975 1.145H3.471a.994.994 0 0 1-.971-1.146c4.763-30.318 12.598-51.743 25.43-68.502 12.835-16.76 30.817-29.049 56.25-40.82"/><path fill=""#,
            #"" fill-opacity=".3" d="M215.963 47.906A16.97 16.97 0 0 1 220 58.913C220 68.35 212.312 76 202.829 76a17.16 17.16 0 0 1-11.975-4.842A17.16 17.16 0 0 1 178.878 76a17.16 17.16 0 0 1-11.976-4.842A17.16 17.16 0 0 1 154.927 76a17.16 17.16 0 0 1-11.976-4.842A17.16 17.16 0 0 1 130.975 76 17.16 17.16 0 0 1 119 71.158 17.16 17.16 0 0 1 107.024 76a17.16 17.16 0 0 1-11.975-4.842A17.16 17.16 0 0 1 83.073 76a17.16 17.16 0 0 1-11.975-4.842A17.16 17.16 0 0 1 59.122 76a17.16 17.16 0 0 1-11.976-4.842A17.16 17.16 0 0 1 35.171 76C25.688 76 18 68.35 18 58.913c0-4.401 1.672-8.414 4.42-11.443C38.94 27.64 56.777 12.055 83.072 4c23.379 29 53.997 28.5 73.219 0 32.944 12.35 48.203 26.77 59.671 43.906"/><path fill=""#,
            #"" d="M212.522 37.906c2.424 2.974 3.885 6.814 3.885 11.007 0 9.437-7.399 17.087-16.525 17.087-4.483 0-8.549-1.845-11.526-4.842-2.977 2.997-7.043 4.842-11.525 4.842s-8.549-1.845-11.526-4.842C162.328 64.155 158.262 66 153.78 66s-8.549-1.845-11.526-4.842C139.277 64.155 135.211 66 130.729 66s-8.549-1.845-11.526-4.842C116.226 64.155 112.161 66 107.678 66s-8.548-1.845-11.525-4.842C93.175 64.155 89.11 66 84.627 66s-8.548-1.845-11.525-4.842C70.125 64.155 66.059 66 61.576 66s-8.548-1.845-11.525-4.842C47.074 64.155 43.008 66 38.525 66 29.4 66 22 58.35 22 48.913c0-4.401 1.61-8.414 4.253-11.443C42.152 17.64 60.193 8.556 85.5.5c23.051 28.5 48 28 66.5-.5 31.705 12.35 49.485 20.77 60.522 37.906"/></svg>"#,
          ],
          slots: [.themeColor, .themeColor, .themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "teeBasic",
      layer: 10,
      position: ItemPosition(xAbs: 0, xRatio: 0.17, yAbs: 0, yRatio: 0.7),
      width: 237,
      height: 116,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="237" height="116" fill="none" viewBox="0 0 237 116"><path fill="#fff" stroke=""##,
            #"" stroke-linecap="round" stroke-linejoin="round" stroke-width="4" d="M84.18 3.032c.458-.211 1.123-.043 1.457.534 16.144 27.974 55.237 25.784 67.427.255.332-.694 1.08-.9 1.559-.682 26.958 12.218 44.661 25.214 56.75 42.181 12.103 16.987 18.729 38.162 23.139 67.035a.996.996 0 0 1-.975 1.145H3.471a.994.994 0 0 1-.971-1.146c4.763-30.318 12.598-51.743 25.43-68.502 12.835-16.76 30.817-29.049 56.25-40.82"/></svg>"#,
          ],
          slots: [.themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "teeButtoned",
      layer: 10,
      position: ItemPosition(xAbs: 0, xRatio: 0.17, yAbs: 0, yRatio: 0.7),
      width: 237,
      height: 116,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="237" height="116" fill="none" viewBox="0 0 237 116"><path fill="#fff" stroke=""##,
            #"" stroke-linecap="round" stroke-linejoin="round" stroke-width="4" d="M84.18 3.032c.458-.211 1.123-.043 1.457.534 16.144 27.974 55.237 25.784 67.427.255.332-.694 1.08-.9 1.559-.682 26.958 12.218 44.661 25.214 56.75 42.181 12.103 16.987 18.729 38.162 23.139 67.035a.996.996 0 0 1-.975 1.145H3.471a.994.994 0 0 1-.971-1.146c4.763-30.318 12.598-51.743 25.43-68.502 12.835-16.76 30.817-29.049 56.25-40.82"/><path fill=""#,
            ##"" d="M108 23.5h22v90h-22z"/><circle cx="119" cy="59.5" r="6" fill="#fff" fill-opacity=".5"/><circle cx="119" cy="85.5" r="6" fill="#fff" fill-opacity=".5"/><rect width="55" height="12" x="149" y="65.5" fill=""##,
            #"" rx="6"/></svg>"#,
          ],
          slots: [.themeColor, .themeColor, .themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "teePocket",
      layer: 10,
      position: ItemPosition(xAbs: 0, xRatio: 0.17, yAbs: 0, yRatio: 0.7),
      width: 237,
      height: 116,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="237" height="116" fill="none" viewBox="0 0 237 116"><path fill="#fff" stroke=""##,
            #"" stroke-linecap="round" stroke-linejoin="round" stroke-width="4" d="M84.18 3.032c.458-.211 1.123-.043 1.457.534 16.144 27.974 55.237 25.784 67.427.255.332-.694 1.08-.9 1.559-.682 26.958 12.218 44.661 25.214 56.75 42.181 12.103 16.987 18.729 38.162 23.139 67.035a.996.996 0 0 1-.975 1.145H3.471a.994.994 0 0 1-.971-1.146c4.763-30.318 12.598-51.743 25.43-68.502 12.835-16.76 30.817-29.049 56.25-40.82"/><path stroke=""#,
            ##"" stroke-width="4" d="M168.5 10C153 46.5 88.5 47 73 7.5"/><path fill="#fff" stroke=""##,
            #"" stroke-width="4" d="M195 52.322v24.704c0 11.874-9.626 21.5-21.5 21.5S152 88.9 152 77.026V52.322z"/><path stroke=""#,
            #"" stroke-width="4" d="M152.136 64.344h42.728"/></svg>"#,
          ],
          slots: [.themeColor, .themeColor, .themeColor, .themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "teeRound",
      layer: 10,
      position: ItemPosition(xAbs: 0, xRatio: 0.17, yAbs: 0, yRatio: 0.7),
      width: 237,
      height: 116,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="237" height="116" fill="none" viewBox="0 0 237 116"><path fill="#fff" stroke=""##,
            #"" stroke-linecap="round" stroke-linejoin="round" stroke-width="4" d="M84.18 3.032c.458-.211 1.123-.043 1.457.534 16.144 27.974 55.237 25.784 67.427.255.332-.694 1.08-.9 1.559-.682 26.958 12.218 44.661 25.214 56.75 42.181 12.103 16.987 18.729 38.162 23.139 67.035a.996.996 0 0 1-.975 1.145H3.471a.994.994 0 0 1-.971-1.146c4.763-30.318 12.598-51.743 25.43-68.502 12.835-16.76 30.817-29.049 56.25-40.82"/><path stroke=""#,
            #"" stroke-width="4" d="M167.5 10.178c-15.5 36.5-80 37-95.5-2.5"/></svg>"#,
          ],
          slots: [.themeColor, .themeColor],
        )
      ]
    )
  ]
}
