// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

extension YanliuTheme {
  static let earsItems: [ItemDescriptor] = [
    ItemDescriptor(
      key: "standard",
      layer: 5,
      position: ItemPosition(xAbs: 0, xRatio: 0.25, yAbs: 0, yRatio: 0.4),
      width: 187,
      height: 47,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="187" height="47" fill="none" viewBox="0 0 187 47"><path fill="#fff" stroke=""##,
            #"" stroke-width="4" d="M26 2c13.45 0 24 9.811 24 21.5S39.45 45 26 45 2 35.189 2 23.5 12.55 2 26 2ZM161 2c-13.45 0-24 9.811-24 21.5S147.55 45 161 45s24-9.811 24-21.5S174.45 2 161 2Z"/></svg>"#,
          ],
          slots: [.themeColor],
        )
      ]
    )
  ]
}
