// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

extension YanliuTheme {
  static let eyesItems: [ItemDescriptor] = [
    ItemDescriptor(
      key: "standard",
      layer: 20,
      position: ItemPosition(xAbs: 0, xRatio: 0.37, yAbs: 0, yRatio: 0.43),
      width: 88,
      height: 21,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="88" height="21" fill="none" viewBox="0 0 88 21"><path fill=""#,
            #"" stroke=""#,
            ##"" stroke-linecap="round" d="M7.768.5c2.061 0 3.89 1.115 5.185 2.843 1.296 1.727 2.082 4.091 2.082 6.68 0 2.59-.786 4.954-2.082 6.681s-3.124 2.843-5.185 2.843c-2.062 0-3.89-1.115-5.186-2.843S.5 12.613.5 10.024c0-2.59.786-4.954 2.082-6.681S5.706.5 7.768.5Z"/><circle cx="10.616" cy="7.809" r="2.5" fill="#fff" stroke=""##,
            #""/><path fill=""#,
            #"" stroke=""#,
            ##"" stroke-linecap="round" d="M79.768.5c2.061 0 3.89 1.115 5.185 2.843 1.296 1.727 2.082 4.091 2.082 6.68 0 2.59-.786 4.954-2.082 6.681s-3.124 2.843-5.185 2.843c-2.062 0-3.89-1.115-5.186-2.843s-2.082-4.091-2.082-6.68c0-2.59.786-4.954 2.082-6.681S77.706.5 79.768.5Z"/><circle cx="82.616" cy="7.809" r="2" fill="#fff"/></svg>"##,
          ],
          slots: [.themeColor, .themeColor, .themeColor, .themeColor, .themeColor],
        )
      ]
    )
  ]
}
