// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

extension YanliuTheme {
  static let forelockItems: [ItemDescriptor] = [
    ItemDescriptor(
      key: "bubble",
      layer: 40,
      position: ItemPosition(xAbs: 0, xRatio: 0.2944, yAbs: 0, yRatio: 0.19440000000000002),
      width: 148,
      height: 88,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="148" height="88" fill="none" viewBox="0 0 148 88"><path fill=""#,
            #"" d="M134.451 48.5c4.218-4.413 4.426-9.399 4.426-14.614C138.877 15.171 108.469 0 70.959 0S3.04 15.171 3.04 33.886c0 5.775 2.896 11.213 8.002 15.972C4.516 52.728 0 58.91 0 66.075 0 75.975 8.623 84 19.26 84c5.352 0 10.195-2.032 13.685-5.312C36.435 81.968 41.278 84 46.63 84s10.195-2.032 13.685-5.312C63.805 81.968 68.648 84 74 84s10.194-2.032 13.685-5.312C91.175 81.968 96.018 84 101.37 84s10.194-2.032 13.685-5.312c3.49 3.28 8.333 5.312 13.685 5.312C139.377 84 148 75.975 148 66.075c0-8.77-4.612-16.022-13.549-17.575"/></svg>"#,
          ],
          slots: [.themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "curve",
      layer: 40,
      position: ItemPosition(xAbs: 0, xRatio: 0.31110000000000004, yAbs: 0, yRatio: 0.2167),
      width: 134,
      height: 83,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="134" height="83" fill="none" viewBox="0 0 134 83"><path fill=""#,
            #"" d="M13.62 69.489C10.653 74.865 6.5 77.83 0 82.006l7.5-63s13-18.5 51.5-19 74.5 32.5 74.5 32.5v50.5c-14.196-2.533-25.254-5.08-31.27-15.012-3.95-6.521-12.56-10.812-18.732-6.337a9.826 9.826 0 0 1-11.829-.221l-5.164-4.048a12 12 0 0 0-14.93.1l-4.283 3.449a12 12 0 0 1-13.355 1.145l-.768-.427c-7.193-3.996-15.57.63-19.548 7.834"/></svg>"#,
          ],
          slots: [.themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "short",
      layer: 40,
      position: ItemPosition(xAbs: 0, xRatio: 0.2833, yAbs: 0, yRatio: 0.1722),
      width: 155,
      height: 111,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="155" height="111" fill="none" viewBox="0 0 155 111"><path fill=""#,
            #"" d="M.254 68.797c-1.64-22.073 4.5-33.5 23-38 0 0 55-54.5 103.5-18.5s18.5 97.203 18.5 97.203c-11.5-15.5-16.534-18.607-15.5-38.203-41.843 12.574-59.284 8.85-82.5-17C44.235 70.987 40.754 77 28.754 84c2.147 12.313-10.5 23-14 26.5C3.59 98.258 1.477 89.302.254 68.797"/></svg>"#,
          ],
          slots: [.themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "split",
      layer: 40,
      position: ItemPosition(xAbs: 0, xRatio: 0.30560000000000004, yAbs: 0, yRatio: 0.2167),
      width: 134,
      height: 86,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="134" height="86" fill="none" viewBox="0 0 134 86"><path fill=""#,
            #"" d="M100.838 38.678C72.838 78.678 47.136 81.762 0 86 8.748 24.794 4.5 3 76.5 0 134 3.5 132.619 34.613 134 86c-17.162-9.322-20.818-15.52-33.162-47.322"/></svg>"#,
          ],
          slots: [.themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "straight",
      layer: 40,
      position: ItemPosition(xAbs: 0, xRatio: 0.30560000000000004, yAbs: 0, yRatio: 0.19440000000000002),
      width: 138,
      height: 89,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="138" height="89" fill="none" viewBox="0 0 138 89"><path fill=""#,
            #"" d="M87.758 33C65.907 75.4 47.394 84.262.258 88.5c-2-68 6.16-77.696 77-88.5 57.644 19.22 57.619 37.113 59 88.5-34.567-9.85-36.156-23.697-48.5-55.5"/></svg>"#,
          ],
          slots: [.themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "underCut",
      layer: 40,
      position: ItemPosition(xAbs: 0, xRatio: 0.2811, yAbs: 0, yRatio: 0.1611),
      width: 157,
      height: 132,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="157" height="132" fill="none" viewBox="0 0 157 132"><path fill=""#,
            #"" d="M.464 79c-3.358 30.005 12.5 50.5 15.5 53 0 0 3.23-26.543 15.788-47.5 38.457 13.847 54.29 14.298 92.712 0 6.501 11 15 27 18.757 47.5 6.243-2.5 16.141-48.555 12.743-70-3.397-21.446-19.858-19.885-19.858-19.885s11.858-10.644 7.115-21.288-27.274 0-27.274 0S126.619 5.452 108.831.72 69.699 16.096 69.699 16.096 77.999.72 62.583.72 31.752 31.47 31.752 31.47 28.08 19.404 20.965 26.5 17.52 58.673 17.52 58.673 3.823 48.995.464 79"/></svg>"#,
          ],
          slots: [.themeColor],
        )
      ]
    )
  ]
}
