// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

extension OrksTheme {
  static let noseItems: [ItemDescriptor] = [
    ItemDescriptor(
      key: "default",
      layer: 21,
      position: ItemPosition(xAbs: 0, xRatio: 0.43710000000000004, yAbs: 0, yRatio: 0.5127),
      width: 124.8,
      height: 63.673,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="124.8" height="63.673" fill="none" viewBox="0 0 98 50"><path fill="#15160E" d="M71.659 7.61c14.62-2.82 24.77 4.71 25.93 18.5-1.41 20.17-18.2 10.44-24.92 15.62-3.92 9.55-37.2 8.77-45.43 3.58-8.28-11.45-17.51.33-25.8-11.29-6.33-17.4 9.27-31.56 26.45-26.6 8.42-9.91 35.37-9.94 43.77.19"/><path fill=""##,
            #"" d="m2.883 30.35.55-9.24C7.173 11.53 14.703 8 29.113 9.36c7.39-9.79 35.5-9.06 41.77.82 16.43-2.79 25.23 5.21 23.36 20.75-.23-.13-1.88 0-1.88 0-3.01-1.69-2.37-4.2-9.62-4.69-8.83-.6-14.64 5-21.25 7.17-28.94 9.52-34.44-16.84-58.61-3.06"/><path fill=""#,
            #"" d="M94.239 30.93c-1.3 3.54-4.99 7.61-9.99 6.18-3.77-11.63-15.72 1.3-17.01 6-4.56 3.51-33.85 4.12-38.25-.27-1.93-5.64-8.51-13.93-16.07-8.92.42 8.46-10.28-.46-10.04-3.57 24.17-13.78 29.67 12.58 58.61 3.06 6.61-2.17 12.42-7.77 21.25-7.17 7.25.49 6.61 3 9.62 4.69 0 0 1.65-.13 1.88 0"/></svg>"#,
          ],
          slots: [.derived([.darken(0.1)]), .derived([.darken(0.2)])],
        )
      ]
    )
  ]
}
