// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore
import AvatuneAshleySeo
import AvatuneAshleyy
import AvatuneCyberpunk
import AvatuneFatinVerse
import AvatuneKyute
import AvatuneMicah
import AvatuneMiniavs
import AvatuneNevmstas
import AvatuneOrks
import AvatunePacovqzz
import AvatunePawelOlekMan
import AvatunePawelOlekWoman
import AvatuneRetroCartoon
import AvatuneToonFlat
import AvatuneVampireSkin
import AvatuneYanliu

/// Every generated theme, keyed by its short name.
public let allThemes: [String: AvatuneTheme] = [
  "ashley-seo": .ashleySeo,
  "ashleyy": .ashleyy,
  "cyberpunk": .cyberpunk,
  "fatin-verse": .fatinVerse,
  "kyute": .kyute,
  "micah": .micah,
  "miniavs": .miniavs,
  "nevmstas": .nevmstas,
  "orks": .orks,
  "pacovqzz": .pacovqzz,
  "pawel-olek-man": .pawelOlekMan,
  "pawel-olek-woman": .pawelOlekWoman,
  "retro-cartoon": .retroCartoon,
  "toon-flat": .toonFlat,
  "vampire-skin": .vampireSkin,
  "yanliu": .yanliu,
]
