// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

/// Item identifiers for the pawel-olek-man theme.
public enum PawelOlekMan {
  public enum Ears: String, CaseIterable, Sendable {
    case big
    case biten
    case ringEarring
    case small
    case standard
    case studEarrings
  }

  public enum Eyes: String, CaseIterable, Sendable {
    case big
    case happy
    case small
    case standard
    case eyelashes
    case eyelids
  }

  public enum FaceDetails: String, CaseIterable, Sendable {
    case chinDimple1
    case chinDimple2
    case chinDimple3
    case chinDimple4
    case `none`
  }

  public enum Glasses: String, CaseIterable, Sendable {
    case brow
    case patch
    case round
    case square
    case stylish
    case `none`
  }

  public enum Hair: String, CaseIterable, Sendable {
    case bald
    case curly
    case elvis
    case mediumTopknot
    case messy
    case shortTopknot
    case stylish
    case beanie
  }

  public enum Head: String, CaseIterable, Sendable {
    case beardMustache
    case beardSharp
    case beardSlim
    case beardStandard
    case bristle
    case bristleMustache
    case chin
    case sharp
    case standard
  }

  public enum Mouth: String, CaseIterable, Sendable {
    case chin
    case philtrum1
    case philtrum2
    case sad
    case small
    case smile
    case tongue1
    case tongue2
    case vampire
  }

  public enum Nose: String, CaseIterable, Sendable {
    case big
    case bigWide
    case small
    case standard
    case wide
  }
}
