// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

/// Namespace for the pawel-olek-man theme's generated data.
public enum PawelOlekManTheme {}

extension AvatuneTheme {
  /// The pawel-olek-man theme, generated from @avatune/pawel-olek-man-theme@3.1.1.
  public static let pawelOlekMan: AvatuneTheme = AvatuneTheme(
    name: "pawel-olek-man",
    style: AvatuneTheme.Style(size: 400, borderColor: .hex(0x2B2B2B), borderWidth: 2, borderRadius: .percent(100)),
    backgroundPalette: [.hex(0xFFFFFF)],
    categories: [
      AvatuneTheme.Category(
        category: .ears,
        palette: [.hex(0xFFFFFF), .hex(0xBCBCBC)],
        items: PawelOlekManTheme.earsItems
      ),
      AvatuneTheme.Category(
        category: .eyes,
        palette: [.hex(0x2B2B2B)],
        items: PawelOlekManTheme.eyesItems
      ),
      AvatuneTheme.Category(
        category: .faceDetails,
        palette: [.hex(0x2B2B2B)],
        items: PawelOlekManTheme.faceDetailsItems
      ),
      AvatuneTheme.Category(
        category: .glasses,
        palette: [.hex(0x2B2B2B)],
        items: PawelOlekManTheme.glassesItems
      ),
      AvatuneTheme.Category(
        category: .hair,
        palette: [.hex(0x2B2B2B)],
        items: PawelOlekManTheme.hairItems
      ),
      AvatuneTheme.Category(
        category: .head,
        palette: [.hex(0xFFFFFF), .hex(0xBCBCBC)],
        items: PawelOlekManTheme.headItems
      ),
      AvatuneTheme.Category(
        category: .mouth,
        palette: [.hex(0x2B2B2B)],
        items: PawelOlekManTheme.mouthItems
      ),
      AvatuneTheme.Category(
        category: .nose,
        palette: [.hex(0x2B2B2B)],
        items: PawelOlekManTheme.noseItems
      )
    ],
    connectedColors: [],
    predictorMappings: AvatuneTheme.PredictorMappings(
      hair: ["long": ["messy", "beanie"], "medium": ["medium", "curly"], "short": ["bald", "elvis", "mediumTopknot", "shortTopknot", "stylish"]]
    )
  )
}
