/**
 * Emits a theme's Swift sources from its IR.
 *
 * Output is deterministic — no timestamps, no hashes, no iteration over
 * unordered maps — because the generated files are committed and a pre-commit
 * hook fails the build when regenerating produces a diff.
 */

import { toPascalCase } from '../../shared'
import type {
  CategoryIR,
  ColorSlotIR,
  EffectIR,
  FragmentIR,
  ItemIR,
  ThemeIR,
} from '../avatune-ir/types'

const HEADER = `// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run \`bun run generate:swift\` (or \`bun run generate\`) to refresh.
`

/** `ashley-seo` -> `AshleySeo`. */
export const moduleSuffix = (theme: string) => toPascalCase(theme)

/** `ashley-seo` -> `ashleySeo`, usable as a Swift property name. */
export const themeProperty = (theme: string) => {
  const pascal = toPascalCase(theme)
  return pascal.charAt(0).toLowerCase() + pascal.slice(1)
}

/**
 * Wraps a string as a Swift raw literal, choosing enough pound signs that the
 * content cannot terminate it early.
 *
 * SVG makes this necessary rather than decorative: a segment ending an attribute
 * before a colour slot leaves a trailing `="`, and static colours contain `"#`,
 * which would close a single-pound literal mid-string.
 */
export function rawStringLiteral(value: string): string {
  let pounds = 1
  while (value.includes(`"${'#'.repeat(pounds)}`)) pounds += 1
  const fence = '#'.repeat(pounds)
  return `${fence}"${value}"${fence}`
}

const number = (value: number) =>
  Number.isInteger(value) ? `${value}` : `${value}`

function swiftColor(hex: string): string {
  const digits = hex.replace('#', '').toLowerCase()
  const expanded =
    digits.length === 3
      ? [...digits].map((d) => d + d).join('')
      : digits.slice(0, 6)
  return `.hex(0x${expanded.toUpperCase()})`
}

const swiftColors = (colors: string[]) =>
  colors.length === 0 ? '[]' : `[${colors.map(swiftColor).join(', ')}]`

function swiftSlot(slot: ColorSlotIR): string {
  if (slot.kind === 'themeColor') return '.themeColor'
  const ops = slot.ops.map((o) => `.${o.op}(${number(o.amount)})`).join(', ')
  return `.derived([${ops}])`
}

function swiftEffect(effect: EffectIR): string {
  switch (effect.kind) {
    case 'blend':
      return `.blend(.${effect.mode})`
    case 'blur':
      return `.blur(stdDeviation: ${number(effect.stdDeviation)})`
    case 'dropShadow': {
      const [r, g, b, a] = effect.color
      const channel = (v: number) => number(Math.round(v * 255 * 1e6) / 1e6)
      return (
        `.dropShadow(dx: ${number(effect.dx)}, dy: ${number(effect.dy)}, ` +
        `stdDeviation: ${number(effect.stdDeviation)}, ` +
        `color: AvatuneColor(red: ${channel(r)}, green: ${channel(g)}, ` +
        `blue: ${channel(b)}, alpha: ${number(a)}))`
      )
    }
  }
}

function swiftFragment(fragment: FragmentIR, indent: string): string {
  const segments = fragment.segments
    .map((segment) => `${indent}    ${rawStringLiteral(segment)},`)
    .join('\n')
  const slots =
    fragment.slots.length === 0
      ? '[]'
      : `[${fragment.slots.map(swiftSlot).join(', ')}]`
  const effects =
    fragment.effects.length === 0
      ? ''
      : `\n${indent}  effects: [${fragment.effects.map(swiftEffect).join(', ')}],`

  return `${indent}Fragment(
${indent}  segments: [
${segments}
${indent}  ],
${indent}  slots: ${slots},${effects}
${indent})`
}

function swiftItem(item: ItemIR, indent: string): string {
  const { xAbs, xRatio, yAbs, yRatio } = item.position
  const fragments =
    item.fragments.length === 0
      ? '[]'
      : `[\n${item.fragments
          .map((fragment) => swiftFragment(fragment, `${indent}    `))
          .join(',\n')}\n${indent}  ]`

  return `${indent}ItemDescriptor(
${indent}  key: ${JSON.stringify(item.key)},
${indent}  layer: ${item.layer},
${indent}  position: ItemPosition(xAbs: ${number(xAbs)}, xRatio: ${number(xRatio)}, yAbs: ${number(yAbs)}, yRatio: ${number(yRatio)}),
${indent}  width: ${number(item.width)},
${indent}  height: ${number(item.height)},
${indent}  fragments: ${fragments}
${indent})`
}

/**
 * One file per category. Splitting keeps each Swift expression small: a single
 * literal holding every item in a theme is slow for the type checker, and the
 * heaviest themes carry hundreds of kilobytes of path data.
 */
export function emitCategory(theme: ThemeIR, category: CategoryIR): string {
  const suffix = moduleSuffix(theme.theme)
  const items =
    category.items.length === 0
      ? '[]'
      : `[\n${category.items
          .map((item) => swiftItem(item, '    '))
          .join(',\n')}\n  ]`

  return `${HEADER}
import AvatuneCore

extension ${suffix}Theme {
  static let ${category.category}Items: [ItemDescriptor] = ${items}
}
`
}

export function emitTheme(theme: ThemeIR): string {
  const suffix = moduleSuffix(theme.theme)
  const style = theme.style

  const styleArguments = [`size: ${number(style.size)}`]
  if (style.backgroundColor)
    styleArguments.push(`backgroundColor: ${swiftColor(style.backgroundColor)}`)
  if (style.borderColor)
    styleArguments.push(`borderColor: ${swiftColor(style.borderColor)}`)
  if (style.borderWidth !== undefined)
    styleArguments.push(`borderWidth: ${number(style.borderWidth)}`)
  if (style.borderRadius) {
    styleArguments.push(
      `borderRadius: .${style.borderRadius.unit === 'percent' ? 'percent' : 'points'}(${number(style.borderRadius.value)})`,
    )
  }

  const categories = theme.categories
    .map(
      (category) =>
        `      AvatuneTheme.Category(\n` +
        `        category: .${category.category},\n` +
        `        palette: ${swiftColors(category.palette)},\n` +
        `        items: ${suffix}Theme.${category.category}Items\n` +
        `      )`,
    )
    .join(',\n')

  const connected = theme.connectedColors
    .map(
      ([dependent, source]) =>
        `ConnectedColor(dependent: .${dependent}, source: .${source})`,
    )
    .join(', ')

  const mappings = theme.predictorMappings
  const mappingArguments: string[] = []
  if (mappings?.hair)
    mappingArguments.push(`hair: ${swiftStringMap(mappings.hair)}`)
  if (mappings?.faceHair)
    mappingArguments.push(`faceHair: ${swiftStringMap(mappings.faceHair)}`)
  if (mappings?.hairColor)
    mappingArguments.push(`hairColor: ${swiftColorMap(mappings.hairColor)}`)
  if (mappings?.skinTone)
    mappingArguments.push(`skinTone: ${swiftColorMap(mappings.skinTone)}`)

  const predictors =
    mappingArguments.length === 0
      ? 'nil'
      : `AvatuneTheme.PredictorMappings(\n      ${mappingArguments.join(',\n      ')}\n    )`

  return `${HEADER}
import AvatuneCore

/// Namespace for the ${theme.theme} theme's generated data.
public enum ${suffix}Theme {}

extension AvatuneTheme {
  /// The ${theme.theme} theme, generated from @avatune/${theme.packageName}@${theme.npmVersion}.
  public static let ${themeProperty(theme.theme)}: AvatuneTheme = AvatuneTheme(
    name: ${JSON.stringify(theme.theme)},
    style: AvatuneTheme.Style(${styleArguments.join(', ')}),
    backgroundPalette: ${swiftColors(theme.backgroundPalette)},
    categories: [
${categories}
    ],
    connectedColors: [${connected}],
    predictorMappings: ${predictors}
  )
}
`
}

function swiftStringMap(map: Record<string, string[]>): string {
  const entries = Object.entries(map)
    .map(
      ([key, values]) =>
        `"${key}": [${values.map((v) => JSON.stringify(v)).join(', ')}]`,
    )
    .sort()
  return entries.length === 0 ? '[:]' : `[${entries.join(', ')}]`
}

function swiftColorMap(map: Record<string, string[]>): string {
  const entries = Object.entries(map)
    .map(([key, values]) => `"${key}": ${swiftColors(values)}`)
    .sort()
  return entries.length === 0 ? '[:]' : `[${entries.join(', ')}]`
}

/**
 * Per-theme identifier enums, so a caller writes `.bob` and a typo fails to
 * compile rather than silently falling through to seeded selection.
 */
export function emitIdentifiers(theme: ThemeIR): string {
  const suffix = moduleSuffix(theme.theme)

  const enums = theme.categories
    .filter((category) => category.items.length > 0)
    .map((category) => {
      const name = toPascalCase(category.category)
      const cases = category.items
        .map((item) => `    case ${swiftCaseName(item.key)}`)
        .join('\n')
      return `  public enum ${name}: String, CaseIterable, Sendable {\n${cases}\n  }`
    })
    .join('\n\n')

  return `${HEADER}
/// Item identifiers for the ${theme.theme} theme.
public enum ${suffix} {
${enums}
}
`
}

/** Swift keywords that cannot be bare enum case names. */
const RESERVED = new Set([
  'none',
  'default',
  'class',
  'struct',
  'enum',
  'protocol',
  'extension',
  'func',
  'var',
  'let',
  'return',
  'public',
  'private',
  'internal',
  'static',
  'super',
  'self',
  'Self',
  'true',
  'false',
  'nil',
  'in',
  'is',
  'as',
  'if',
  'else',
  'for',
  'while',
  'repeat',
  'switch',
  'case',
  'break',
  'continue',
  'operator',
  'open',
])

function swiftCaseName(key: string): string {
  const safe = /^[A-Za-z_][A-Za-z0-9_]*$/.test(key)
    ? key
    : `_${key.replace(/\W/g, '_')}`
  // `none` is a legal case name but shadows Optional.none at call sites, so it
  // is escaped rather than renamed — the raw value still has to match the theme.
  return RESERVED.has(safe) ? `\`${safe}\`` : safe
}
