/**
 * Emits the typed builder façade for a theme.
 *
 * The string-keyed `AvatarConfiguration` stays the escape hatch for
 * server-driven identifiers, but it cannot tell you that `kyute` has no hats or
 * that `bob` is a hair and not a mouth. The generated builder can: a theme only
 * gets methods for the categories it actually has, and each takes that
 * category's own enum, so a wrong identifier fails to compile instead of
 * silently falling back to seeded selection.
 */

import { toPascalCase } from '../../shared'
import type { ThemeIR } from '../avatune-ir/types'
import { moduleSuffix, themeProperty } from './emit-theme'

const HEADER = `// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run \`bun run generate:swift\` (or \`bun run generate\`) to refresh.
`

export function emitBuilder(theme: ThemeIR): string {
  const suffix = moduleSuffix(theme.theme)
  const type = `${suffix}Avatar`

  const withItems = theme.categories.filter(
    (category) => category.items.length > 0,
  )

  const itemMethods = withItems
    .map((category) => {
      const name = category.category
      const enumName = `${suffix}.${toPascalCase(name)}`
      return `  /// Pins the ${name} item, optionally overriding its colour.
  public func ${name}(_ id: ${enumName}, color: AvatuneColor? = nil) -> Self {
    var copy = self
    copy.configuration[.${name}] = id.rawValue
    if let color { copy.configuration[color: .${name}] = color }
    return copy
  }`
    })
    .join('\n\n')

  // Every palette category gets a colour setter, including ones with no
  // artwork: a theme can colour a category it has no items for.
  const colorMethods = theme.categories
    .map((category) => {
      const name = category.category
      return `  /// Overrides the ${name} colour.
  public func ${name}Color(_ color: AvatuneColor) -> Self {
    var copy = self
    copy.configuration[color: .${name}] = color
    return copy
  }`
    })
    .join('\n\n')

  return `${HEADER}
import AvatuneCore

/// A typed way to describe a ${theme.theme} avatar.
///
/// Each method returns a copy, so calls chain the way SwiftUI modifiers do.
public struct ${type}: AvatarSpecifying, Hashable, Sendable {
  public var configuration: AvatarConfiguration
  public var predictions: Predictions?

  public var theme: AvatuneTheme { .${themeProperty(theme.theme)} }

  public init(seed: AvatuneSeed? = nil) {
    self.configuration = AvatarConfiguration(seed: seed)
  }

  public init(configuration: AvatarConfiguration, predictions: Predictions? = nil) {
    self.configuration = configuration
    self.predictions = predictions
  }

${itemMethods}

${colorMethods}

  /// Sets the background behind the avatar.
  public func background(_ color: AvatuneColor) -> Self {
    var copy = self
    copy.configuration.backgroundColor = color
    return copy
  }

  /// Rounds the avatar's corners. Percentages resolve against the rendered size.
  public func cornerRadius(_ length: AvatuneLength) -> Self {
    var copy = self
    copy.configuration.cornerRadius = length
    return copy
  }

  /// Steers selection from predictor output. Supplying predictions replaces the
  /// seed entirely, matching the web renderers.
  public func predictions(_ predictions: Predictions) -> Self {
    var copy = self
    copy.predictions = predictions
    return copy
  }

  public func seed(_ seed: AvatuneSeed) -> Self {
    var copy = self
    copy.configuration.seed = seed
    return copy
  }
}
`
}
