/**
 * Writes the generated Swift package sources.
 *
 * Files are written only when their content changes, so an unrelated asset
 * rebuild leaves no diff and the pre-commit freshness check stays quiet.
 * Anything under a theme module that is no longer generated is removed, so a
 * renamed or deleted item cannot linger as a stale file that still compiles.
 */

import {
  existsSync,
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from 'node:fs'
import { join } from 'node:path'
import type { ThemeIR } from '../avatune-ir/types'
import { emitBuilder } from './emit-builder'
import {
  emitCategory,
  emitIdentifiers,
  emitTheme,
  moduleSuffix,
  themeProperty,
} from './emit-theme'

export interface EmitResult {
  written: number
  removed: number
  bytes: number
}

function writeIfChanged(path: string, content: string): boolean {
  if (existsSync(path) && readFileSync(path, 'utf-8') === content) return false
  writeFileSync(path, content, 'utf-8')
  return true
}

function pruneStale(directory: string, expected: Set<string>): number {
  if (!existsSync(directory)) return 0
  let removed = 0
  for (const entry of readdirSync(directory, { withFileTypes: true })) {
    const path = join(directory, entry.name)
    if (entry.isDirectory()) continue
    if (!expected.has(path)) {
      rmSync(path)
      removed += 1
    }
  }
  return removed
}

export function emitSwiftSources(
  themes: ThemeIR[],
  swiftDir: string,
): EmitResult {
  const sourcesDir = join(swiftDir, 'Sources')
  let written = 0
  let removed = 0
  let bytes = 0

  for (const theme of themes) {
    const suffix = moduleSuffix(theme.theme)
    const moduleDir = join(sourcesDir, `Avatune${suffix}`)
    const itemsDir = join(moduleDir, 'Items')
    mkdirSync(itemsDir, { recursive: true })

    const files = new Map<string, string>([
      [join(moduleDir, `${suffix}+Theme.swift`), emitTheme(theme)],
      [join(moduleDir, `${suffix}+Identifiers.swift`), emitIdentifiers(theme)],
      [join(moduleDir, `${suffix}Avatar.swift`), emitBuilder(theme)],
    ])

    for (const category of theme.categories) {
      files.set(
        join(itemsDir, `${suffix}+${category.category}.swift`),
        emitCategory(theme, category),
      )
    }

    for (const [path, content] of files) {
      if (writeIfChanged(path, content)) written += 1
      bytes += Buffer.byteLength(content)
    }

    removed += pruneStale(moduleDir, new Set(files.keys()))
    removed += pruneStale(itemsDir, new Set(files.keys()))
  }

  // One shared internal target rather than a copy per consumer. It is not a
  // product, so nothing outside the package can depend on every theme at once.
  const registryDir = join(sourcesDir, 'AvatuneAllThemes')
  mkdirSync(registryDir, { recursive: true })
  if (
    writeIfChanged(
      join(registryDir, 'Registry.generated.swift'),
      emitRegistry(themes),
    )
  ) {
    written += 1
  }

  const packagePath = join(swiftDir, 'Package.swift')
  if (writeIfChanged(packagePath, emitPackage(themes, packagePath)))
    written += 1

  return { written, removed, bytes }
}

/**
 * Index of every generated theme, for the tools that need all of them.
 *
 * Consumers import one theme module and pay for one theme, so no shipped product
 * references them all. The parity suite, the snapshot renderer and the gallery
 * do, and generating the list keeps them from silently skipping a theme that was
 * added but never wired in.
 */
function emitRegistry(themes: ThemeIR[]): string {
  const sorted = [...themes].sort((a, b) => a.theme.localeCompare(b.theme))
  const imports = sorted
    .map((theme) => `import Avatune${moduleSuffix(theme.theme)}`)
    .join('\n')
  const entries = sorted
    .map((theme) => `  "${theme.theme}": .${themeProperty(theme.theme)},`)
    .join('\n')

  return `// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run \`bun run generate:swift\` (or \`bun run generate\`) to refresh.

import AvatuneCore
${imports}

/// Every generated theme, keyed by its short name.
public let allThemes: [String: AvatuneTheme] = [
${entries}
]
`
}

/**
 * Rewrites only the generated theme list inside Package.swift, leaving the
 * hand-written targets and platform floors alone.
 */
function emitPackage(themes: ThemeIR[], packagePath: string): string {
  const existing = readFileSync(packagePath, 'utf-8')
  // Sorted rather than discovery-ordered: directory listing order is not
  // guaranteed across machines, and this file is committed.
  const list = themes
    .map((theme) => `"${moduleSuffix(theme.theme)}"`)
    .sort()
    .join(', ')

  const begin = '// AUTO-GENERATED THEMES BEGIN'
  const end = '// AUTO-GENERATED THEMES END'
  const block = `${begin}\nlet themes = [${list}]\n${end}`

  const pattern = new RegExp(`${begin}[\\s\\S]*?${end}`)
  if (!pattern.test(existing)) {
    throw new Error(
      `${packagePath} has no '${begin}' / '${end}' block for the generated theme list.`,
    )
  }
  return existing.replace(pattern, block)
}
