#!/usr/bin/env bun
/**
 * Generates the website's React and avatar API theme registries from the
 * discovered theme packages and keeps workspace dependencies in sync.
 *
 * Every current and future theme automatically appears in the home-page hero
 * playground, documentation navigation, and SVG/PNG API routes.
 *
 * Usage: bun scripts/generate-website-themes.ts
 */

import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { discoverThemes, kebabToCamelCase } from './shared'

interface ThemeEntry {
  id: string
  binding: string
  npmName: string
  assetsNpmName: string
  label: string
  reactPath: string
  vanillaPath: string
  slug: string
  previewId: string
}

const websiteDir = join(process.cwd(), 'apps', 'website')
const registryPath = join(
  websiteDir,
  'src',
  'lib',
  'theme-registry.generated.ts',
)
const avatarApiRegistryPath = join(
  websiteDir,
  'src',
  'lib',
  'avatar-api-themes.generated.ts',
)
const themeDocsPath = join(websiteDir, 'src', 'lib', 'theme-docs.generated.ts')
const packageJsonPath = join(websiteDir, 'package.json')
const apiClientThemeNamesPath = join(
  process.cwd(),
  'packages',
  'core',
  'api-client',
  'src',
  'theme-names.generated.ts',
)

/**
 * Builds the generated registry source from the theme entries.
 */
function buildRegistrySource(entries: ThemeEntry[]): string {
  const moduleOf = (line: string) => line.match(/from '([^']+)'/)?.[1] ?? ''
  const imports = [
    ...entries.map((e) => `import ${e.binding} from '${e.reactPath}'`),
    "import type { ReactTheme } from '@avatune/types'",
  ].sort((a, b) => moduleOf(a).localeCompare(moduleOf(b)))

  const themeIdUnion = entries.map((e) => `  | '${e.id}'`).join('\n')
  const themeMapEntries = entries
    .map((e) => `  ${e.id}: ${e.binding},`)
    .join('\n')
  const themeInfoEntries = entries
    .map(
      (e) =>
        `  { id: '${e.id}', label: '${e.label}', packageName: '${e.npmName}' },`,
    )
    .join('\n')
  const themeMapBySlugEntries = entries
    .map((e) => `  '${e.previewId}': ${e.binding},`)
    .join('\n')

  return `// AUTO-GENERATED by scripts/generate-website-themes.ts. Do not edit by hand.
// Run \`bun run generate:website-themes\` (or \`bun run generate\`) to refresh.
${imports.join('\n')}

export type ThemeId =
${themeIdUnion}

export interface ThemeInfo {
  id: ThemeId
  label: string
  packageName: string
}

export const themeMap: Record<string, ReactTheme> = {
${themeMapEntries}
}

/** Keyed by the theme's doc slug (kebab-case, e.g. \`retro-cartoon\`). */
export const themeMapBySlug: Record<string, ReactTheme> = {
${themeMapBySlugEntries}
}

export const themeInfos: ThemeInfo[] = [
${themeInfoEntries}
]
`
}

function buildAvatarApiRegistrySource(entries: ThemeEntry[]): string {
  const imports = [
    ...entries.map(
      (entry) => `import ${entry.binding} from '${entry.vanillaPath}'`,
    ),
    "import type { VanillaTheme } from '@avatune/types'",
  ].sort()
  const themeMapEntries = entries
    .map((entry) => {
      const key = /^[A-Za-z_$][\w$]*$/.test(entry.previewId)
        ? entry.previewId
        : `'${entry.previewId}'`
      return `  ${key}: ${entry.binding},`
    })
    .join('\n')

  return `// AUTO-GENERATED by scripts/generate-website-themes.ts. Do not edit by hand.
// Run \`bun run generate:website-themes\` (or \`bun run generate\`) to refresh.
${imports.join('\n')}

export const avatarApiThemes = {
${themeMapEntries}
} satisfies Record<string, VanillaTheme>

export type AvatarApiThemeName = keyof typeof avatarApiThemes

export const avatarApiThemeNames = Object.keys(
  avatarApiThemes,
) as AvatarApiThemeName[]
`
}

function buildApiClientThemeNamesSource(entries: ThemeEntry[]): string {
  const themeNames = entries
    .map((entry) => `  '${entry.previewId}',`)
    .join('\n')

  return `// AUTO-GENERATED by scripts/generate-website-themes.ts. Do not edit by hand.
// Run \`bun run generate:website-themes\` (or \`bun run generate\`) to refresh.

export const themeNames = [
${themeNames}
] as const

export type ThemeName = (typeof themeNames)[number]
`
}

/**
 * Builds the Fumadocs "Themes" navigation items without importing theme
 * component bundles.
 */
function buildThemeDocsSource(entries: ThemeEntry[]): string {
  const items = entries
    .map(
      (entry) =>
        `  { label: '${entry.label}', previewId: '${entry.previewId}', slugs: ['packages', '${entry.slug.replace('packages/', '')}'] },`,
    )
    .join('\n')

  return `// AUTO-GENERATED by scripts/generate-website-themes.ts. Do not edit by hand.
// Run \`bun run generate:website-themes\` (or \`bun run generate\`) to refresh.

export interface ThemeDocItem {
  label: string
  previewId: string
  slugs: string[]
}

export const themeDocItems: ThemeDocItem[] = [
${items}
]
`
}

/**
 * Ensures every theme (and its assets package) is a website dependency,
 * inserting missing ones next to the existing `@avatune/*` deps.
 * @returns the list of added dependency names
 */
function ensureWebsiteDeps(entries: ThemeEntry[]): string[] {
  const pkg = JSON.parse(readFileSync(packageJsonPath, 'utf-8'))
  const deps: Record<string, string> = pkg.dependencies ?? {}

  const required = new Set<string>()
  for (const e of entries) {
    required.add(e.npmName)
    required.add(e.assetsNpmName)
  }

  const missing = [...required].filter((name) => !deps[name]).sort()
  if (missing.length === 0) {
    return []
  }

  const keys = Object.keys(deps)
  const lastAvatuneIdx = keys.reduce(
    (acc, key, index) => (key.startsWith('@avatune/') ? index : acc),
    keys.length - 1,
  )
  keys.splice(lastAvatuneIdx + 1, 0, ...missing)

  const rebuilt: Record<string, string> = {}
  for (const key of keys) {
    rebuilt[key] = deps[key] ?? 'workspace:*'
  }
  pkg.dependencies = rebuilt

  writeFileSync(packageJsonPath, `${JSON.stringify(pkg, null, 2)}\n`, 'utf-8')
  return missing
}

function main() {
  const entries: ThemeEntry[] = discoverThemes()
    .map((theme) => {
      const id = kebabToCamelCase(theme.name)
      return {
        id,
        binding: `${id}Theme`,
        npmName: `@avatune/${theme.packageName}`,
        assetsNpmName: `@avatune/${theme.assetsPackageName}`,
        label: theme.displayName,
        reactPath: `@avatune/${theme.packageName}/react`,
        vanillaPath: `@avatune/${theme.packageName}/vanilla`,
        slug: `packages/${theme.packageName}`,
        previewId: theme.name,
      }
    })
    .sort((a, b) => a.npmName.localeCompare(b.npmName))

  writeFileSync(registryPath, buildRegistrySource(entries), 'utf-8')
  writeFileSync(
    avatarApiRegistryPath,
    buildAvatarApiRegistrySource(entries),
    'utf-8',
  )
  writeFileSync(themeDocsPath, buildThemeDocsSource(entries), 'utf-8')
  writeFileSync(
    apiClientThemeNamesPath,
    buildApiClientThemeNamesSource(entries),
    'utf-8',
  )
  console.log(
    `✓ Generated website and API registries for ${entries.length} theme(s)`,
  )

  const added = ensureWebsiteDeps(entries)
  if (added.length > 0) {
    console.log(`✓ Added website deps: ${added.join(', ')}`)
    console.log('  Installing to link new workspace deps...')
    const install = Bun.spawnSync(['bun', 'install'], {
      cwd: process.cwd(),
      stdout: 'inherit',
      stderr: 'inherit',
    })
    if (!install.success) {
      console.error('bun install failed — run it manually to link new deps.')
      process.exit(1)
    }
  }

  console.log('\n✨ Website hero themes synced!')
}

main()
