// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

/// Namespace for the vampire-skin theme's generated data.
public enum VampireSkinTheme {}

extension AvatuneTheme {
  /// The vampire-skin theme, generated from @avatune/vampire-skin-theme@1.0.0.
  public static let vampireSkin: AvatuneTheme = AvatuneTheme(
    name: "vampire-skin",
    style: AvatuneTheme.Style(size: 560, borderRadius: .percent(50)),
    backgroundPalette: [.hex(0xFFEDEF)],
    categories: [
      AvatuneTheme.Category(
        category: .accessories,
        palette: [.hex(0x000000), .hex(0xFFFFFF), .hex(0x9287FF), .hex(0x6BD9E9), .hex(0xFC909F), .hex(0xF4D150)],
        items: VampireSkinTheme.accessoriesItems
      ),
      AvatuneTheme.Category(
        category: .body,
        palette: [.hex(0x262626), .hex(0xE24B4B), .hex(0x8B4FA1), .hex(0x9ED1DB), .hex(0x3D587B)],
        items: VampireSkinTheme.bodyItems
      ),
      AvatuneTheme.Category(
        category: .eyebrows,
        palette: [.hex(0x000000), .hex(0xFFFFFF), .hex(0x9287FF), .hex(0x6BD9E9), .hex(0xFC909F), .hex(0xF4D150)],
        items: VampireSkinTheme.eyebrowsItems
      ),
      AvatuneTheme.Category(
        category: .eyes,
        palette: [.hex(0x000000), .hex(0xFFFFFF), .hex(0x9287FF), .hex(0x6BD9E9), .hex(0xFC909F), .hex(0xF4D150)],
        items: VampireSkinTheme.eyesItems
      ),
      AvatuneTheme.Category(
        category: .hair,
        palette: [.hex(0x3B3065), .hex(0xC2C2C2), .hex(0xFFEB6B), .hex(0xF1681E)],
        items: VampireSkinTheme.hairItems
      ),
      AvatuneTheme.Category(
        category: .hats,
        palette: [.hex(0x262626), .hex(0xE24B4B), .hex(0x8B4FA1), .hex(0x9ED1DB), .hex(0x3D587B)],
        items: VampireSkinTheme.hatsItems
      ),
      AvatuneTheme.Category(
        category: .head,
        palette: [.hex(0xEBECF3), .hex(0x91593B)],
        items: VampireSkinTheme.headItems
      ),
      AvatuneTheme.Category(
        category: .mouth,
        palette: [.hex(0x000000), .hex(0xFFFFFF), .hex(0x9287FF), .hex(0x6BD9E9), .hex(0xFC909F), .hex(0xF4D150)],
        items: VampireSkinTheme.mouthItems
      ),
      AvatuneTheme.Category(
        category: .nose,
        palette: [.hex(0x000000), .hex(0xFFFFFF), .hex(0x9287FF), .hex(0x6BD9E9), .hex(0xFC909F), .hex(0xF4D150)],
        items: VampireSkinTheme.noseItems
      )
    ],
    connectedColors: [],
    predictorMappings: AvatuneTheme.PredictorMappings(
      hair: ["long": ["pigtails", "longWavy", "longStraight"], "medium": ["bobBangs", "shaggy"], "short": ["spiky", "widowsPeak"]],
      skinTone: ["dark": [.hex(0xEBECF3)], "light": [.hex(0xEBECF3)], "medium": [.hex(0xEBECF3)]]
    )
  )
}
