// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

/// Item identifiers for the vampire-skin theme.
public enum VampireSkin {
  public enum Accessories: String, CaseIterable, Sendable {
    case horns
    case heartGlasses
    case mask
    case bats
    case hoopEarring
    case monocle
    case `none`
  }

  public enum Body: String, CaseIterable, Sendable {
    case cloak
    case ruffleShirt
    case corset
    case tailcoat
    case batCape
    case bikerJacket
    case denimVest
  }

  public enum Eyebrows: String, CaseIterable, Sendable {
    case stern
    case curved
    case thin
    case straight
  }

  public enum Eyes: String, CaseIterable, Sendable {
    case closed
    case glare
    case dot
    case wide
    case droopy
    case happy
    case lidded
    case arched
  }

  public enum Hair: String, CaseIterable, Sendable {
    case longStraight
    case widowsPeak
    case bobBangs
    case longWavy
    case shaggy
    case spiky
    case slickedBack
    case pigtails
    case wavyBob
  }

  public enum Hats: String, CaseIterable, Sendable {
    case beanie
    case topHat
    case `none`
  }

  public enum Head: String, CaseIterable, Sendable {
    case standard
  }

  public enum Mouth: String, CaseIterable, Sendable {
    case fangGrin
    case smile
    case flat
    case smirk
    case hiss
    case laugh
  }

  public enum Nose: String, CaseIterable, Sendable {
    case wide
    case nostrils
  }
}
