import Foundation
import XCTest

@testable import AvatuneCore

/// Loads the JSON fixtures generated by `bun scripts/generate-swift.ts`.
///
/// Expected values in these files are produced by the same JavaScript the web
/// renderers run, so a failure here means the Swift port diverges from shipped
/// behaviour — not that a rule was written down incorrectly.
enum Fixtures {
    static func load<T: Decodable>(_ type: T.Type, named name: String) throws -> T {
        guard let url = Bundle.module.url(forResource: name, withExtension: "json") else {
            throw FixtureError.missing(name)
        }
        do {
            return try JSONDecoder().decode(T.self, from: Data(contentsOf: url))
        } catch {
            throw FixtureError.undecodable(name, underlying: error)
        }
    }

    /// Loads once per suite, keeping the failure reason rather than discarding
    /// it — a swallowed decoding error reads as "fixture not generated", which
    /// sends you to rerun a generator that already worked.
    static func cached<T: Decodable>(_ type: T.Type, named name: String) -> Result<T, Error> {
        Result { try load(type, named: name) }
    }
}

// MARK: - colors.json

struct ColorFixture: Decodable {
    struct Chain: Decodable {
        let id: String
        let ops: [ColorOperation]
    }

    struct Conversion: Decodable {
        struct HSL: Decodable {
            let h: Double
            let s: Double
            let l: Double
        }

        let input: String
        let hsl: HSL
        let hue: Double
        let hex: String
    }

    let inputs: [String]
    let chains: [Chain]
    /// `[inputIndex, chainIndex, expectedHex]`, encoded positionally to keep the
    /// ~15k-row cross product from dominating the repository diff.
    let rows: [ColorRow]
    let conversions: [Conversion]

    struct ColorRow: Decodable {
        let inputIndex: Int
        let chainIndex: Int
        let expected: String

        init(from decoder: Decoder) throws {
            var container = try decoder.unkeyedContainer()
            inputIndex = try container.decode(Int.self)
            chainIndex = try container.decode(Int.self)
            expected = try container.decode(String.self)
        }
    }
}

// MARK: - random.json

struct RandomFixture: Decodable {
    struct Row: Decodable {
        let input: String
        let hash: Int64
        let values: [Double]
        let note: String?
    }

    struct NumberRow: Decodable {
        let value: Double
        let text: String
        let note: String?
    }

    let rows: [Row]
    let numbers: [NumberRow]
}

// MARK: - selection.json

struct SelectionFixture: Decodable {
    struct Style: Decodable {
        let size: Double
        let backgroundColor: String?
        let borderColor: String?
        let borderWidth: Double?
        let borderRadius: AvatuneLength?
    }

    struct Item: Decodable {
        struct Position: Decodable {
            let xAbs: Double
            let xRatio: Double
            let yAbs: Double
            let yRatio: Double
        }

        let key: String
        let layer: Int
        let position: Position
    }

    struct Category: Decodable {
        let category: String
        let palette: [String]
        let items: [Item]
    }

    struct Theme: Decodable {
        let name: String
        let style: Style
        let backgroundPalette: [String]
        let categories: [Category]
        let connectedColors: [[String]]
        let predictorMappings: [String: [String: [String]]]?
    }

    struct Case: Decodable {
        struct Expectation: Decodable {
            struct Style: Decodable {
                let backgroundColor: String?
                let borderRadius: AvatuneLength?
            }

            let identifiers: [String: String]
            let colors: [String: String]
            let style: Style
        }

        let theme: String
        let label: String
        let config: AvatarConfiguration
        let predictions: Predictions?
        let predictionsSeed: String?
        let expect: Expectation
    }

    let themes: [Theme]
    let cases: [Case]
}

extension SelectionFixture.Theme {
    /// Rebuilds a runtime theme. Category order is preserved exactly, since
    /// selection depends on it.
    func makeTheme() throws -> AvatuneTheme {
        func color(_ hex: String) throws -> AvatuneColor {
            guard let parsed = AvatuneColor(hex: hex) else {
                throw FixtureError.badColor(hex, theme: name)
            }
            return parsed
        }

        func category(_ raw: String) throws -> AvatarPartCategory {
            guard let parsed = AvatarPartCategory(rawValue: raw) else {
                throw FixtureError.unknownCategory(raw, theme: name)
            }
            return parsed
        }

        let style = AvatuneTheme.Style(
            size: style.size,
            backgroundColor: try style.backgroundColor.map(color),
            borderColor: try style.borderColor.map(color),
            borderWidth: style.borderWidth ?? 0,
            borderRadius: style.borderRadius
        )

        let categories = try self.categories.map { entry in
            AvatuneTheme.Category(
                category: try category(entry.category),
                palette: try entry.palette.map(color),
                items: entry.items.map { item in
                    ItemDescriptor(
                        key: item.key,
                        layer: item.layer,
                        position: ItemPosition(
                            xAbs: item.position.xAbs,
                            xRatio: item.position.xRatio,
                            yAbs: item.position.yAbs,
                            yRatio: item.position.yRatio
                        )
                    )
                }
            )
        }

        let connected = try connectedColors.compactMap { pair -> ConnectedColor? in
            guard pair.count == 2 else { return nil }
            return ConnectedColor(
                dependent: try category(pair[0]),
                source: try category(pair[1])
            )
        }

        var mappings: AvatuneTheme.PredictorMappings?
        if let raw = predictorMappings {
            mappings = AvatuneTheme.PredictorMappings(
                hair: raw["hair"] ?? [:],
                faceHair: raw["faceHair"] ?? [:],
                hairColor: try (raw["hairColor"] ?? [:]).mapValues { try $0.map(color) },
                skinTone: try (raw["skinTone"] ?? [:]).mapValues { try $0.map(color) }
            )
        }

        return AvatuneTheme(
            name: name,
            style: style,
            backgroundPalette: try backgroundPalette.map(color),
            categories: categories,
            connectedColors: connected,
            predictorMappings: mappings
        )
    }
}

enum FixtureError: Error, CustomStringConvertible {
    case missing(String)
    case undecodable(String, underlying: Error)
    case badColor(String, theme: String)
    case unknownCategory(String, theme: String)

    var description: String {
        switch self {
        case .missing(let name):
            return
                "Missing fixture \(name).json. Run 'bun run build && bun scripts/generate-swift.ts'."
        case .undecodable(let name, let underlying):
            return "Cannot decode \(name).json: \(underlying)"
        case .badColor(let hex, let theme):
            return "\(theme): cannot parse colour '\(hex)'"
        case .unknownCategory(let raw, let theme):
            return "\(theme): unknown category '\(raw)'"
        }
    }
}
