// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

extension ToonFlatTheme {
  static let mouthItems: [ItemDescriptor] = [
    ItemDescriptor(
      key: "smile",
      layer: 20,
      position: ItemPosition(xAbs: 0, xRatio: 0.35229999999999995, yAbs: 0, yRatio: 0.5227999999999999),
      width: 55.002,
      height: 23.457,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="55.002" height="23.457" fill="none" viewBox="0 0 68 29"><path fill="#0C0C0C" d="M64.74.09 67.52 0C68.4 10.37 2.43 18.65 0 5.33 18.64 12.77 50.69 8.34 64.74.09M11.24 24.03c8.29.76 18.04 1.28 25.83.2-2.16 5.01-21.77 5.23-25.83-.2"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "flat",
      layer: 20,
      position: ItemPosition(xAbs: 0, xRatio: 0.35309999999999997, yAbs: 0, yRatio: 0.5196),
      width: 66.216,
      height: 22.921,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="66.216" height="22.921" fill="none" viewBox="0 0 52 18"><path fill="#0C0C0C" d="M.55.06c7.64.38 47.05-.81 50.1.87 1.68.93.34 2.4-.32 2.59-15.41-.77-33.4-1.14-49-.98C-.14 1.68-.38 1.86.55.06M13.141 14.558c6.24-.15 14.02.09 19.19.8-2.39 2.4-21.48 4.16-19.19-.8"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "laugh",
      layer: 20,
      position: ItemPosition(xAbs: 0, xRatio: 0.33979999999999994, yAbs: 0, yRatio: 0.5016),
      width: 72.624,
      height: 42.14,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="72.624" height="42.14" fill="none" viewBox="0 0 81 47"><path fill="#0C0C0C" d="M78.447 0c5.21 3.98-3.08 18.51-5.01 21.63-6.26 10.14-18.07 21.6-32.95 23.86-27.87 4.22-30.06-13.3-37.01-31.74-.24-.65-4.74-7.89-3.13-9.5 26.01 3.38 53.55-2.91 78.1-4.25"/><path fill="#FEFEFD" d="M76.097 3v3.97c-2.58 9.61-64.16 15.95-67.98 4.6-.15-.46-.65-3.88-.62-3.91 24.92.58 45.82-3.03 68.6-4.66"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "smirk",
      layer: 20,
      position: ItemPosition(xAbs: 0, xRatio: 0.35379999999999995, yAbs: 0, yRatio: 0.5207999999999999),
      width: 63.546,
      height: 15.196,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="63.546" height="15.196" fill="none" viewBox="0 0 46 11"><path fill="#0C0C0C" d="M44.41 0C52.53 6.76.87 16.58 0 6.82 16.31 10.07 34.14 6.17 44.41 0"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "openSmile",
      layer: 20,
      position: ItemPosition(xAbs: 0, xRatio: 0.37089999999999995, yAbs: 0, yRatio: 0.522),
      width: 28.836,
      height: 21.421,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="28.836" height="21.421" fill="none" viewBox="0 0 35 26"><path fill="#0C0C0C" d="M33.61 11.36c-5.5-.64-28.8.2-31.51-1.61C-10.76-6.93 39.92.63 33.61 11.36M5.98 22.29c.8-.21 19.95.59 20.12.66-3.55 3.96-16.76 3.61-20.12-.66"/><path fill="#FEFEFD" d="M23.39 8.931c-.19.02-16.85-.63-17.04-.68-1.76-.52-1.26-3.2.03-4.21 5.65-4.39 32.64 3.47 17.01 4.89"/></svg>"##,
          ],
          slots: [],
        )
      ]
    )
  ]
}
