// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

extension ToonFlatTheme {
  static let noseItems: [ItemDescriptor] = [
    ItemDescriptor(
      key: "curve",
      layer: 21,
      position: ItemPosition(xAbs: 0, xRatio: 0.36219999999999997, yAbs: 0, yRatio: 0.4285),
      width: 23.496,
      height: 23.496,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="23.496" height="23.496" fill="none" viewBox="0 0 35 35"><path fill="#0C0C0C" d="M14.669 0c-.7 5.43-10.24 14.01-10.96 17.92-3.42 18.66 28.88 10.09 30.5 11.38.01.01 0 1.58 0 1.58C-2.841 42.9-10.492 18.77 14.669 0"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "flat",
      layer: 21,
      position: ItemPosition(xAbs: 0, xRatio: 0.3645, yAbs: 0, yRatio: 0.448),
      width: 23.496,
      height: 7.476,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="23.496" height="7.476" fill="none" viewBox="0 0 22 7"><path fill="#0C0C0C" d="M.97.007c1.09.08 3.46 1.92 4.86 2.15 1.27.21 15.57-.82 15.77-.65.01.01 0 1.52 0 1.52-.36.82-6.26 1.53-7.49 1.97-1.01.36-.16 1.93-3.69 2.01-4.96.11-13.26-7.27-9.45-7"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "thin",
      layer: 21,
      position: ItemPosition(xAbs: 0, xRatio: 0.353, yAbs: 0, yRatio: 0.4222),
      width: 20.826,
      height: 26.872,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="20.826" height="26.872" fill="none" viewBox="0 0 31 40"><path fill="#0C0C0C" d="M12.768 0c1.96 5.36-4.54 12.18-6.69 16.87-8.48 18.41 12.27 18.58 14.28 21 2.62 3.15-8.04 1.04-8.76.82-23.82-10.8-4.48-24.95 1.17-38.69"/><path fill="#0C0C0C" d="M30.688 33.718v1.33c-.73 1.04-13.43.15-10.67-1.68 1.15-.76 9.65-1.12 10.67.35"/></svg>"##,
          ],
          slots: [],
        )
      ]
    )
  ]
}
