// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

extension ToonFlatTheme {
  static let eyesItems: [ItemDescriptor] = [
    ItemDescriptor(
      key: "big",
      layer: 20,
      position: ItemPosition(xAbs: 0, xRatio: 0.32199999999999995, yAbs: 0, yRatio: 0.3519),
      width: 81.168,
      height: 24.194,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="81.168" height="24.194" fill="none" viewBox="0 0 104 31"><path fill="#0C0C0C" d="M81.648 8.847c9.37 2.62 8.45 24.71-5.3 21.92-9.91-2.01-8.66-25.83 5.3-21.92"/><path fill="#FEFEFD" d="M79.968 13.267c3.01-.72 4.09 5.07 1.73 6-4.05 1.59-4.22-5.4-1.73-6"/><path fill="#0C0C0C" d="M23.398 22.155c-1.6 12.87-16.59 10.97-15.63-3.27.96-14.17 17.5-11.79 15.63 3.27"/><path fill="#FEFEFD" d="M17.778 14.264c1.21.46 2.65 6.46-1.44 5.58-2.38-.52-1.99-6.87 1.44-5.58"/><path fill="#0C0C0C" d="M91.148 1.846c3.98 1.56 15.76 11.89 10.78 18.09-4.61-19.54-32.37-22.43-38.14-1.58-2.6-13.94 13.12-22.27 27.36-16.51M29.328 19.016c-4.85-16.18-24.24-19.09-28.31-.21-.69 1.17-.36.58-.87-.29-2.61-22.35 30.29-21.99 29.18.5"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "almond",
      layer: 20,
      position: ItemPosition(xAbs: 0, xRatio: 0.3176, yAbs: 0, yRatio: 0.3592),
      width: 89.712,
      height: 18.445,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="89.712" height="18.445" fill="none" viewBox="0 0 107 22"><path fill="#0C0C0C" d="M106.2 14.11c-4.87-4.15-11.16-7.75-18.68-9.02 4.69 18.42-18.63 18.62-15.35 1.82-3.64-.78-6.79 3.92-9.21 5.82 3.17-19.74 41.32-14.35 43.24 1.38"/><path fill="#FEFEFD" d="M83.26 6.592c2.81 1.11.24 7.02-2.48 4.18-1.78-1.85-.2-5.24 2.48-4.18"/><path fill="#0C0C0C" d="M28.96 14.59c-2.02.93-5.21-5.79-7-4 1.03 16.81-17.6 11.94-13.17-3-2-2-8.33 8.06-8.79 5.24C2.39-3.46 26.8 1.72 28.96 14.59"/><path fill="#FEFEFD" d="m18.96 12.44-2 1.8-2-1.8c-1.44-4.35 5.44-4.35 4 0"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "narrow",
      layer: 20,
      position: ItemPosition(xAbs: 0, xRatio: 0.31449999999999995, yAbs: 0, yRatio: 0.359),
      width: 83.838,
      height: 13.688,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="83.838" height="13.688" fill="none" viewBox="0 0 98 16"><path fill="#0C0C0C" d="M97.652 8.81c1.17 4.02-7.6-3.52-9-2.12.86 14.67-19.69 9.61-15.49-3-5.28-.69-7.08 1.79-10.01 3.5.48-4.74-1.41-.49-1-4.28 10.58-6.38 29.96-1.3 35.5 5.9"/><path fill="#FEFEFD" d="M81.692 4.69c1.95-.81 2.88 2.23 2.46 3.3-1.45 3.69-5.06-2.22-2.46-3.3"/><path fill="#0C0C0C" d="M25.722 8.78c.1 1.75-2.23-1.47-2.94-.59-.18 12.58-16.5 8.07-14.26-3.61C6.352 3.82.592 8.09.062 5.8c-1.51-6.5 25.15-6.16 25.66 2.98"/><path fill="#FEFEFD" d="M19.782 8.27c-.55 2.86-4.18.03-3.13-1.91s3.51-.09 3.13 1.91"/></svg>"##,
          ],
          slots: [],
        )
      ]
    )
  ]
}
