// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

/// Namespace for the nevmstas theme's generated data.
public enum NevmstasTheme {}

extension AvatuneTheme {
  /// The nevmstas theme, generated from @avatune/nevmstas-theme@3.2.2.
  public static let nevmstas: AvatuneTheme = AvatuneTheme(
    name: "nevmstas",
    style: AvatuneTheme.Style(size: 164, borderRadius: .percent(100)),
    backgroundPalette: [.hex(0xA7C957), .hex(0x90D5FF), .hex(0xFFB3C1), .hex(0xC8B6FF), .hex(0xFFBE98), .hex(0xB8E0D2)],
    categories: [
      AvatuneTheme.Category(
        category: .hats,
        palette: [.hex(0xF06E82)],
        items: NevmstasTheme.hatsItems
      ),
      AvatuneTheme.Category(
        category: .accessories,
        palette: [.hex(0xF06E82)],
        items: NevmstasTheme.accessoriesItems
      ),
      AvatuneTheme.Category(
        category: .hair,
        palette: [.hex(0x1C1C1C), .hex(0x4A2E2A), .hex(0x7A4B34), .hex(0xA87555), .hex(0xE8C16A), .hex(0xF2EAD8), .hex(0xD8693D), .hex(0xB3362D), .hex(0x6C6C6C), .hex(0xA9A9A9), .hex(0xFFFFFF), .hex(0xFF7EBE), .hex(0xFF3FAF), .hex(0xA77BFF), .hex(0xC7B9FF), .hex(0x5AA5FF), .hex(0x9FD6FF), .hex(0x3CBFBA), .hex(0x67D36F), .hex(0xC6FF5E), .hex(0xFFE55E), .hex(0xFF9B4A)],
        items: NevmstasTheme.hairItems
      ),
      AvatuneTheme.Category(
        category: .head,
        palette: [.hex(0x80502E), .hex(0xC78A5C), .hex(0xFCBE93), .hex(0xFDCDAC), .hex(0xF5D0C5), .hex(0xC4DB64)],
        items: NevmstasTheme.headItems
      ),
      AvatuneTheme.Category(
        category: .body,
        palette: [.hex(0x1C1C1C), .hex(0xFFFFFF), .hex(0x5AA5FF), .hex(0x9FD6FF), .hex(0xFF7EBE), .hex(0xFF3FAF), .hex(0xB3362D), .hex(0xFF9B4A), .hex(0xFFE55E), .hex(0x67D36F), .hex(0xC6FF5E), .hex(0x7A4B34)],
        items: NevmstasTheme.bodyItems
      ),
      AvatuneTheme.Category(
        category: .ears,
        palette: [.hex(0xFCBE93), .hex(0xFDCDAC)],
        items: NevmstasTheme.earsItems
      ),
      AvatuneTheme.Category(
        category: .eyebrows,
        palette: [.hex(0x1C1C1C), .hex(0x4A2E2A), .hex(0x7A4B34)],
        items: NevmstasTheme.eyebrowsItems
      ),
      AvatuneTheme.Category(
        category: .eyes,
        palette: [.hex(0x000000)],
        items: NevmstasTheme.eyesItems
      ),
      AvatuneTheme.Category(
        category: .mouth,
        palette: [.hex(0xF06E82)],
        items: NevmstasTheme.mouthItems
      ),
      AvatuneTheme.Category(
        category: .nose,
        palette: [.hex(0xFF9C8D)],
        items: NevmstasTheme.noseItems
      ),
      AvatuneTheme.Category(
        category: .faceHair,
        palette: [.hex(0x1C1C1C), .hex(0x4A2E2A), .hex(0x7A4B34), .hex(0xA87555), .hex(0xE8C16A), .hex(0xD8693D), .hex(0x6C6C6C), .hex(0xA9A9A9), .hex(0xFFFFFF)],
        items: NevmstasTheme.faceHairItems
      )
    ],
    connectedColors: [ConnectedColor(dependent: .ears, source: .head), ConnectedColor(dependent: .eyebrows, source: .hair), ConnectedColor(dependent: .faceHair, source: .hair)],
    predictorMappings: AvatuneTheme.PredictorMappings(
      hair: ["long": ["long", "bobRounded", "bobStraight"], "medium": ["medium"], "short": ["short"]],
      faceHair: ["beard": ["beard"], "none": []],
      hairColor: ["black": [.hex(0x1C1C1C), .hex(0x4A2E2A)], "blond": [.hex(0xE8C16A), .hex(0xF2EAD8)], "brown": [.hex(0x7A4B34), .hex(0xA87555)], "gray": [.hex(0x6C6C6C), .hex(0xA9A9A9), .hex(0xFFFFFF)]],
      skinTone: ["dark": [.hex(0x80502E)], "light": [.hex(0xFCBE93), .hex(0xFDCDAC)], "medium": [.hex(0xC78A5C)]]
    )
  )
}
