// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

/// Item identifiers for the nevmstas theme.
public enum Nevmstas {
  public enum Hats: String, CaseIterable, Sendable {
    case santa
    case `none`
  }

  public enum Accessories: String, CaseIterable, Sendable {
    case horns
    case `none`
  }

  public enum Hair: String, CaseIterable, Sendable {
    case bobRounded
    case bobStraight
    case short
    case long
    case medium
  }

  public enum Head: String, CaseIterable, Sendable {
    case oval
  }

  public enum Body: String, CaseIterable, Sendable {
    case santa
    case shirt
    case sweater
    case tshirt
    case turtleneck
  }

  public enum Ears: String, CaseIterable, Sendable {
    case standard
  }

  public enum Eyebrows: String, CaseIterable, Sendable {
    case angry
    case small
    case standard
  }

  public enum Eyes: String, CaseIterable, Sendable {
    case boring
    case dots
    case openCircle
    case openRounded
  }

  public enum Mouth: String, CaseIterable, Sendable {
    case bigSmile
    case flat
    case frown
    case halfOpen
    case laugh
    case smile
    case nervous
  }

  public enum Nose: String, CaseIterable, Sendable {
    case big
    case curve
    case dots
    case halfOval
  }

  public enum FaceHair: String, CaseIterable, Sendable {
    case beard
    case `none`
  }
}
