import Foundation

/// Loads the artwork fixture generated by `bun scripts/generate-swift.ts`.
enum Fixtures {
    static func load<T: Decodable>(_ type: T.Type, named name: String) throws -> T {
        guard let url = Bundle.module.url(forResource: name, withExtension: "json") else {
            throw FixtureError.missing(name)
        }
        do {
            return try JSONDecoder().decode(T.self, from: Data(contentsOf: url))
        } catch {
            throw FixtureError.undecodable(name, underlying: error)
        }
    }

    /// Loads once per suite, keeping the failure reason rather than discarding
    /// it — a swallowed decoding error reads as "fixture not generated", which
    /// sends you to rerun a generator that already worked.
    static func cached<T: Decodable>(_ type: T.Type, named name: String) -> Result<T, Error> {
        Result { try load(type, named: name) }
    }
}

enum FixtureError: Error, CustomStringConvertible {
    case missing(String)
    case undecodable(String, underlying: Error)

    var description: String {
        switch self {
        case .missing(let name):
            return
                "Missing fixture \(name).json. Run 'bun run build && bun scripts/generate-swift.ts'."
        case .undecodable(let name, let underlying):
            return "Cannot decode \(name).json: \(underlying)"
        }
    }
}

struct ArtworkFixture: Decodable {
    struct FragmentDigest: Decodable {
        let length: Int
        let hash: Int64
    }

    struct Row: Decodable {
        let theme: String
        let category: String
        let key: String
        let fragments: [FragmentDigest]
    }

    struct Sample: Decodable {
        let theme: String
        let category: String
        let key: String
        let svgs: [String]
        let why: String
    }

    /// The colour every recorded SVG was rebuilt at.
    let color: String
    let rows: [Row]
    let samples: [Sample]
}
