import {
  AccessoriesBeautyMark,
  AccessoriesCap,
  AccessoriesEarpieceLeft,
  AccessoriesEarringRight,
  AccessoriesGlassesRound,
  AccessoriesGlassesSquare,
  AccessoriesHeadsetMic,
  AccessoriesMask,
  AccessoriesVisorGlasses,
  BodyHoodie,
  BodyJacket,
  BodyScarfTop,
  BodyShirtTie,
  BodyStripedOverall,
  BodySuit,
  BodyTurtleneck,
  EyebrowsBrowAngled,
  EyebrowsBrowFlat,
  EyebrowsBrowRaised,
  EyebrowsBrowSoft,
  EyebrowsBrowThick,
  EyebrowsBrowThin,
  EyesFocused,
  EyesHappy,
  EyesNeutral,
  EyesSurprised,
  EyesWide,
  FaceHairBeard,
  FaceHairMustache,
  HairCurlyPuff,
  HairCurlyTop,
  HairCurvedLong,
  HairDoubleBuns,
  HairLongBraid,
  HairLongStraight,
  HairLongWave,
  HairLowBun,
  HairShortCurly,
  HairShortFlip,
  HairShortMessy,
  HairShortWave,
  HairSidePonytail,
  HairSideSweep,
  HairSpiky,
  HairTightCurls,
  HairVolumized,
  HeadDiamond,
  HeadHeart,
  HeadOval,
  HeadPear,
  HeadRound,
  HeadSquare,
  HeadThin,
  HeadTriangle,
  HeadWide,
  MouthNeutralLine,
  MouthSmileSmall,
  MouthSmileSoft,
  MouthSmirkLeft,
  MouthSmirkRight,
  MouthTinyDot,
  NoseCurve,
  NoseLong,
  NosePointy,
  NoseRound,
  NoseSmall,
  NoseSoft,
} from '@avatune/fatin-verse-assets/svelte'
import type { SvelteAvatarItem } from '@avatune/types'
import shared from './shared'

export default shared
  .toFramework<SvelteAvatarItem>()
  .withComponents('accessories', {
    beautyMark: { Component: AccessoriesBeautyMark },
    cap: { Component: AccessoriesCap },
    earpieceLeft: { Component: AccessoriesEarpieceLeft },
    earringRight: { Component: AccessoriesEarringRight },
    headsetMic: { Component: AccessoriesHeadsetMic },
    mask: { Component: AccessoriesMask },
  })
  .withComponents('glasses', {
    glassesRound: { Component: AccessoriesGlassesRound },
    glassesSquare: { Component: AccessoriesGlassesSquare },
    visorGlasses: { Component: AccessoriesVisorGlasses },
  })
  .withComponents('hair', {
    curlyPuff: { Component: HairCurlyPuff },
    curlyTop: { Component: HairCurlyTop },
    curvedLong: { Component: HairCurvedLong },
    doubleBuns: { Component: HairDoubleBuns },
    longBraid: { Component: HairLongBraid },
    longStraight: { Component: HairLongStraight },
    longWave: { Component: HairLongWave },
    lowBun: { Component: HairLowBun },
    shortCurly: { Component: HairShortCurly },
    shortFlip: { Component: HairShortFlip },
    shortMessy: { Component: HairShortMessy },
    shortWave: { Component: HairShortWave },
    sidePonytail: { Component: HairSidePonytail },
    sideSweep: { Component: HairSideSweep },
    spiky: { Component: HairSpiky },
    tightCurls: { Component: HairTightCurls },
    volumized: { Component: HairVolumized },
  })
  .withComponents('body', {
    hoodie: { Component: BodyHoodie },
    jacket: { Component: BodyJacket },
    scarfTop: { Component: BodyScarfTop },
    shirtTie: { Component: BodyShirtTie },
    stripedOverall: { Component: BodyStripedOverall },
    suit: { Component: BodySuit },
    turtleneck: { Component: BodyTurtleneck },
  })
  .withComponents('eyes', {
    eyesFocused: { Component: EyesFocused },
    eyesHappy: { Component: EyesHappy },
    eyesNeutral: { Component: EyesNeutral },
    eyesSurprised: { Component: EyesSurprised },
    eyesWide: { Component: EyesWide },
  })
  .withComponents('eyebrows', {
    browAngled: { Component: EyebrowsBrowAngled },
    browFlat: { Component: EyebrowsBrowFlat },
    browRaised: { Component: EyebrowsBrowRaised },
    browSoft: { Component: EyebrowsBrowSoft },
    browThick: { Component: EyebrowsBrowThick },
    browThin: { Component: EyebrowsBrowThin },
  })
  .withComponents('faceHair', {
    beard: { Component: FaceHairBeard },
    mustache: { Component: FaceHairMustache },
  })
  .withComponents('head', {
    diamond: { Component: HeadDiamond },
    heart: { Component: HeadHeart },
    oval: { Component: HeadOval },
    pear: { Component: HeadPear },
    round: { Component: HeadRound },
    square: { Component: HeadSquare },
    thin: { Component: HeadThin },
    triangle: { Component: HeadTriangle },
    wide: { Component: HeadWide },
  })
  .withComponents('mouth', {
    neutralLine: { Component: MouthNeutralLine },
    smileSmall: { Component: MouthSmileSmall },
    smileSoft: { Component: MouthSmileSoft },
    smirkLeft: { Component: MouthSmirkLeft },
    smirkRight: { Component: MouthSmirkRight },
    tinyDot: { Component: MouthTinyDot },
  })
  .withComponents('nose', {
    noseCurve: { Component: NoseCurve },
    noseLong: { Component: NoseLong },
    nosePointy: { Component: NosePointy },
    noseRound: { Component: NoseRound },
    noseSmall: { Component: NoseSmall },
    noseSoft: { Component: NoseSoft },
  })
  .build()
