// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

extension RetroCartoonTheme {
  static let noseItems: [ItemDescriptor] = [
    ItemDescriptor(
      key: "curve",
      layer: 21,
      position: ItemPosition(xAbs: 0, xRatio: 0.47679999999999995, yAbs: 0, yRatio: 0.43360000000000004),
      width: 28,
      height: 25.667,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="28" height="25.667" fill="none" viewBox="0 0 24 22"><path fill="#201814" d="M5.19 5.756c-7.28 11.7 8.08 14.28 18.73 11.11-.52 5.08-8.53 4.06-14.09 4.14-26.58-7.89 10.9-31.91-4.64-15.25"/></svg>"##,
          ],
          slots: [],
        )
      ]
    )
  ]
}
