// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

extension RetroCartoonTheme {
  static let eyebrowsItems: [ItemDescriptor] = [
    ItemDescriptor(
      key: "soft",
      layer: 22,
      position: ItemPosition(xAbs: 0, xRatio: 0.36819999999999997, yAbs: 0, yRatio: 0.30770000000000003),
      width: 145.6,
      height: 18.314,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="145.6" height="18.314" fill="none" viewBox="0 0 159 20"><path fill="#201814" d="M158.131 18.205c-1.06 1.06-8.34-3.31-9.25-3.64-10.08-3.7-21.62-5.6-34.59-2.41-3.17.78-11.29 5.74-12.66.74-.12-.43 0-3.98 0-3.98 12.24-15.45 52.96-9.84 56.5 9.29M33.88 11.505l-6.25.05c-8.08.13-15.62 2.9-20.75 5.11-1.05.45-6.62 5.5-6.88 1.49 5.86-16.11 36.25-22.68 52.97-12.02 3.52 2.97 4.8 6.94.82 10.24-6.35-1.92-11.8-4.61-19.91-4.87"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "thick",
      layer: 22,
      position: ItemPosition(xAbs: 0, xRatio: 0.37639999999999996, yAbs: 0, yRatio: 0.316),
      width: 134.4,
      height: 15.093,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="134.4" height="15.093" fill="none" viewBox="0 0 187 21"><path fill="#201814" d="M75.464 3.642c.34.51 2.4 11.73 1.76 12.94-23.5 2.68-51.91 1.26-75.65 3.65-4.97-1.45 2.81-13.83 9.74-16.17 4.73-1.6 62.14-3.48 64.15-.42M121.325 16.981c-1.27-.15-6.39.56-8.42 0-3.94-1.08-.74-14.31 1.38-15.7 1.05-.51 52.88-1.67 57.54-1.15 9.53 1.05 15.17 6.37 15 15.73l-54.5.88z"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "angled",
      layer: 22,
      position: ItemPosition(xAbs: 0, xRatio: 0.36819999999999997, yAbs: 0, yRatio: 0.29910000000000003),
      width: 145.6,
      height: 27.773,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="145.6" height="27.773" fill="none" viewBox="0 0 173 33"><path fill="#201814" d="M157.298.028c3.12.5 17.86 11.8 15.2 15.12-4.59-1.98-10.67-3.15-16.33-2.15-7.14 1.27-48.33 19.69-48.65 19.61-1.23-1.2-6.7-8.15-5.52-11.06.54-1.33 49.7-22.42 55.3-21.52M15.2 3.029c8.47-.26 53.96 14.79 54.8 17.39.64 1.99-3.59 10.14-4.91 10.3-3.19.37-44.92-17.37-57.85-14.29-.78.19-6.56 3.28-7.24 2.6-.03-5.41 11.38-15.39 15.2-16"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "flat",
      layer: 22,
      position: ItemPosition(xAbs: 0, xRatio: 0.3782, yAbs: 0, yRatio: 0.3211),
      width: 134.4,
      height: 11.263,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="134.4" height="11.263" fill="none" viewBox="0 0 179 15"><path fill="#201814" d="M154.28 12.93c-3.67.06-45.88 1.28-45.88 1.28-2.33-.68-1.95-10.97.6-12.24C111.91.52 161.17.54 168.82 0c3.74.69 11.07 8.11 9.24 12.78h-10.78zM39.779.24l4.5.29c1.36.08 23.38.71 23.43.73 3.16.94 2.44 7.9 2.07 11.64l-69.75.26C-.391 6.6 3.869 3 7.279.9c9.59-.37 22.57-1.1 32.5-.66"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "raised",
      layer: 22,
      position: ItemPosition(xAbs: 0, xRatio: 0.38139999999999996, yAbs: 0, yRatio: 0.2885),
      width: 128.8,
      height: 33.799,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="128.8" height="33.799" fill="none" viewBox="0 0 141 37"><path fill="#201814" d="M28.762 4.275c20.7-2.68 21.32 15.08 15.95 16.11-19.45-7.2-35.84 4.28-43.23 15.88H.012c-.51-15.63 15.89-30.32 28.75-31.99M101.76.276c20.65-2.48 36.45 12.13 38.75 28.99h-1.42c-7.97-11.24-26.59-21.72-44.53-12.78-7.9-5.64 1.43-14.71 7.2-16.21"/></svg>"##,
          ],
          slots: [],
        )
      ]
    )
  ]
}
