// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

extension KyuteTheme {
  static let faceDetailsItems: [ItemDescriptor] = [
    ItemDescriptor(
      key: "blushes",
      layer: 25,
      position: ItemPosition(xAbs: 0, xRatio: 0.295, yAbs: 0, yRatio: 0.545),
      width: 194,
      height: 25,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="194" height="25" fill="none" viewBox="0 0 194 25"><ellipse cx="177.5" cy="12.5" fill=""#,
            #"" rx="16.5" ry="12.5"/><ellipse cx="16.5" cy="12.5" fill=""#,
            #"" rx="16.5" ry="12.5"/></svg>"#,
          ],
          slots: [.themeColor, .themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "freckles",
      layer: 25,
      position: ItemPosition(xAbs: 0, xRatio: 0.295, yAbs: 0, yRatio: 0.58),
      width: 187,
      height: 18,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="187" height="18" fill="none" viewBox="0 0 187 18"><circle cx="3.5" cy="3.5" r="3.5" fill="#9c6457" fill-opacity=".5"/></svg>"##,
          ],
          slots: [],
          effects: [.blend(.multiply)],
        ),
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="187" height="18" fill="none" viewBox="0 0 187 18"><circle cx="10.5" cy="14.5" r="3.5" fill="#9c6457" fill-opacity=".5"/></svg>"##,
          ],
          slots: [],
          effects: [.blend(.multiply)],
        ),
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="187" height="18" fill="none" viewBox="0 0 187 18"><circle cx="22.5" cy="3.5" r="3.5" fill="#9c6457" fill-opacity=".5"/></svg>"##,
          ],
          slots: [],
          effects: [.blend(.multiply)],
        ),
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="187" height="18" fill="none" viewBox="0 0 187 18"><circle cx="3.5" cy="3.5" r="3.5" fill="#9c6457" fill-opacity=".5" transform="matrix(-1 0 0 1 187 0)"/></svg>"##,
          ],
          slots: [],
          effects: [.blend(.multiply)],
        ),
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="187" height="18" fill="none" viewBox="0 0 187 18"><circle cx="3.5" cy="3.5" r="3.5" fill="#9c6457" fill-opacity=".5" transform="matrix(-1 0 0 1 180 11)"/></svg>"##,
          ],
          slots: [],
          effects: [.blend(.multiply)],
        ),
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="187" height="18" fill="none" viewBox="0 0 187 18"><circle cx="3.5" cy="3.5" r="3.5" fill="#9c6457" fill-opacity=".5" transform="matrix(-1 0 0 1 168 0)"/></svg>"##,
          ],
          slots: [],
          effects: [.blend(.multiply)],
        )
      ]
    ),
    ItemDescriptor(
      key: "none",
      layer: 0,
      position: ItemPosition(xAbs: 0, xRatio: 0, yAbs: 0, yRatio: 0),
      width: 0,
      height: 0,
      fragments: []
    )
  ]
}
