// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

extension KyuteTheme {
  static let glassesItems: [ItemDescriptor] = [
    ItemDescriptor(
      key: "aviator",
      layer: 32,
      position: ItemPosition(xAbs: 0, xRatio: 0.21, yAbs: 0, yRatio: 0.42),
      width: 277,
      height: 96,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="277" height="96" fill="none" viewBox="0 0 277 96"><path stroke=""#,
            #"" stroke-width="7" d="M89.581 9.72C71.12 2.619 47.85 1.777 27.478 6.286 12.186 9.67 2.944 25.017 5.776 40.874c2.863 16.024 8.417 28.94 16.672 37.805C30.615 87.449 41.647 92.5 56.11 92.5c22.596 0 35.48-10.023 42.415-22.902 7.083-13.154 8.118-29.632 5.996-42.287-1.344-8.013-7.114-14.58-14.94-17.59ZM187.419 9.72c18.462-7.102 41.732-7.944 62.102-3.435 15.293 3.385 24.535 18.732 21.703 34.589-2.863 16.024-8.417 28.94-16.672 37.805-8.167 8.77-19.199 13.821-33.662 13.821-22.596 0-35.48-10.023-42.415-22.902-7.083-13.154-8.118-29.632-5.996-42.287 1.344-8.013 7.114-14.58 14.94-17.59Z"/><path stroke=""#,
            #"" stroke-width="7" d="M101 20c28.809-5.288 46.942-5.378 74 0"/></svg>"#,
          ],
          slots: [.themeColor, .themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "harry",
      layer: 32,
      position: ItemPosition(xAbs: 0, xRatio: 0.215, yAbs: 0, yRatio: 0.42),
      width: 269,
      height: 97,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="269" height="97" fill="none" viewBox="0 0 269 97"><path stroke=""#,
            #"" stroke-width="7" d="M183.395 9.158c19.116-7.668 40.75-7.305 60.092-.344 9.523 3.428 16.728 11.504 19.324 21.375 4.902 18.645 3.074 34.962-5.216 46.065-8.193 10.973-23.396 17.765-47.35 15.955-22.04-2.935-33.374-13.433-38.939-25.621-5.697-12.475-5.556-27.202-3.53-38.526 1.531-8.556 7.459-15.631 15.619-18.904ZM85.606 9.158c-19.117-7.668-40.75-7.305-60.093-.344C15.99 12.242 8.785 20.318 6.189 30.19 1.287 48.834 3.115 65.15 11.405 76.254c8.193 10.973 23.396 17.765 47.35 15.955 22.04-2.935 33.374-13.433 38.94-25.621 5.696-12.475 5.555-27.202 3.529-38.526-1.531-8.556-7.459-15.631-15.618-18.904Z"/><path stroke=""#,
            #"" stroke-width="7" d="M97 18.956c30.509-8.433 46.41-8.051 75 2.044"/></svg>"#,
          ],
          slots: [.themeColor, .themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "round",
      layer: 32,
      position: ItemPosition(xAbs: 0, xRatio: 0.21, yAbs: 0, yRatio: 0.41),
      width: 277,
      height: 111,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="277" height="111" fill="none" viewBox="0 0 277 111"><circle cx="55" cy="56" r="52" stroke=""#,
            #"" stroke-width="6"/><circle cx="222" cy="55" r="52" stroke=""#,
            #"" stroke-width="6"/><path stroke=""#,
            #"" stroke-width="6" d="M104 41h67"/></svg>"#,
          ],
          slots: [.themeColor, .themeColor, .themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "standard",
      layer: 32,
      position: ItemPosition(xAbs: 0, xRatio: 0.215, yAbs: 0, yRatio: 0.42),
      width: 269,
      height: 100,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="269" height="100" fill="none" viewBox="0 0 269 100"><path stroke=""#,
            #"" stroke-width="3" d="M201.43 2.585c10.786-1.728 21.619-1.458 33.15 1.288 17.624 4.197 31.368 18.911 32.686 36.84.727 9.902-.243 19.887-2.862 29.166-4.268 15.127-18.18 25.462-33.968 27.647-9.978 1.382-20.416 1.382-31.351-.573-18.037-3.224-32.588-17.458-35.45-35.493a92 92 0 0 1-1.112-12.445c-.497-22.693 16.476-42.837 38.907-46.43ZM67.57 2.585C56.784.857 45.951 1.127 34.42 3.873 16.796 8.07 3.052 22.784 1.734 40.713c-.727 9.902.243 19.887 2.862 29.166 4.268 15.127 18.18 25.462 33.969 27.647 9.977 1.382 20.415 1.382 31.35-.573 18.037-3.224 32.588-17.458 35.45-35.493a92 92 0 0 0 1.112-12.445c.497-22.693-16.476-42.837-38.907-46.43Z"/><path stroke=""#,
            #"" stroke-width="3" d="M95 17s19.462-6 39.591-6S173 19 173 19"/></svg>"#,
          ],
          slots: [.themeColor, .themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "none",
      layer: 0,
      position: ItemPosition(xAbs: 0, xRatio: 0, yAbs: 0, yRatio: 0),
      width: 0,
      height: 0,
      fragments: []
    )
  ]
}
