// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

extension KyuteTheme {
  static let eyesItems: [ItemDescriptor] = [
    ItemDescriptor(
      key: "big",
      layer: 20,
      position: ItemPosition(xAbs: 0, xRatio: 0.29, yAbs: 0, yRatio: 0.49),
      width: 198,
      height: 38,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="198" height="38" fill="none" viewBox="0 0 198 38"><circle cx="179" cy="19" r="19" fill="#150c0c"/><circle cx="19" cy="19" r="19" fill="#150c0c"/><circle cx="23" cy="13" r="3" fill="#fff" fill-opacity=".9"/><circle cx="184" cy="13" r="3" fill="#fff" fill-opacity=".9"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "huge",
      layer: 20,
      position: ItemPosition(xAbs: 0, xRatio: 0.28, yAbs: 0, yRatio: 0.48),
      width: 204,
      height: 44,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="204" height="44" fill="none" viewBox="0 0 204 44"><circle cx="182" cy="22" r="22" fill="#150c0c"/><circle cx="22" cy="22" r="22" fill="#150c0c"/><circle cx="30" cy="18" r="4" fill="#fff" fill-opacity=".9"/><circle cx="191" cy="18" r="4" fill="#fff" fill-opacity=".9"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "medium",
      layer: 20,
      position: ItemPosition(xAbs: 0, xRatio: 0.295, yAbs: 0, yRatio: 0.49),
      width: 191,
      height: 32,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="191" height="32" fill="none" viewBox="0 0 191 32"><path fill="#150c0c" d="M36 16c0 6.55-8.059 16-18 16S0 24.837 0 16 8.059 0 18 0s18 9.45 18 16M155 16c0 6.55 8.059 16 18 16s18-7.163 18-16-8.059-16-18-16-18 9.45-18 16"/><ellipse cx="170" cy="10" fill="#fff" fill-opacity=".9" rx="4" ry="3"/><ellipse cx="12" cy="10" fill="#fff" fill-opacity=".9" rx="4" ry="3"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "oval",
      layer: 20,
      position: ItemPosition(xAbs: 0, xRatio: 0.29, yAbs: 0, yRatio: 0.49),
      width: 193,
      height: 38,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="193" height="38" fill="none" viewBox="0 0 193 38"><ellipse cx="16" cy="18.5" fill="#150c0c" rx="16" ry="18.5"/><circle cx="17" cy="12" r="3" fill="#fff" fill-opacity=".9"/><ellipse cx="176.5" cy="19" fill="#150c0c" rx="16.5" ry="19"/><circle cx="178" cy="12" r="3" fill="#fff" fill-opacity=".9"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "standard",
      layer: 20,
      position: ItemPosition(xAbs: 0, xRatio: 0.29, yAbs: 0, yRatio: 0.49),
      width: 189,
      height: 28,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="189" height="28" fill="none" viewBox="0 0 189 28"><circle cx="14" cy="14" r="14" fill="#150c0c"/><circle cx="17" cy="11" r="3" fill="#fff" fill-opacity=".9"/><circle cx="175" cy="14" r="14" fill="#150c0c"/><circle cx="179" cy="11" r="3" fill="#fff" fill-opacity=".9"/></svg>"##,
          ],
          slots: [],
        )
      ]
    )
  ]
}
