// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

extension KyuteTheme {
  static let eyebrowsItems: [ItemDescriptor] = [
    ItemDescriptor(
      key: "thick1",
      layer: 21,
      position: ItemPosition(xAbs: 0, xRatio: 0.25, yAbs: 0, yRatio: 0.44),
      width: 238,
      height: 23,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="238" height="23" fill="none" viewBox="0 0 238 23"><path fill=""#,
            #"" d="M176.319 4.126C200-1 217.381 5.21 230.369 11.387c6.23 2.964 9.811 10.432.841 7.603-12.71-4.01-32.71-5.99-49.007-1.801-5.884 1.512-15.703-10.937-5.884-13.063M61.37 4.126C37.69-1 20.308 5.21 7.32 11.387c-6.23 2.964-9.81 10.432-.84 7.603 12.71-4.01 32.71-5.99 49.006-1.801C61.37 18.7 71.19 6.252 61.37 4.126"/></svg>"#,
          ],
          slots: [.themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "thick2",
      layer: 21,
      position: ItemPosition(xAbs: 0, xRatio: 0.255, yAbs: 0, yRatio: 0.44),
      width: 236,
      height: 25,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="236" height="25" fill="none" viewBox="0 0 236 25"><path fill=""#,
            #"" d="M175.317 15.582c-4.763-2.926-4.738-8.947 1.002-11.456 23.61-5.965 41.062 1.083 54.05 13.261 1.178 1.104 2.496 2.252 3.736 3.339 1.762 2.663-.393 4.483-2.895 4.264-14.657-10.317-28.734-10.043-36.791-9.744-4.337.16-9.134 1.774-12.216 1.943-3.53.193-6.012-1.07-6.886-1.607M60.929 15.582c4.763-2.926 4.738-8.947-1.003-11.456-23.61-5.965-41.062 1.083-54.05 13.261C4.7 18.491 3.38 19.64 2.141 20.726c-1.763 2.663.392 4.483 2.895 4.264 14.656-10.317 28.734-10.043 36.79-9.744 4.338.16 9.135 1.774 12.216 1.943 3.53.193 6.012-1.07 6.886-1.607"/></svg>"#,
          ],
          slots: [.themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "thickSad",
      layer: 21,
      position: ItemPosition(xAbs: 0, xRatio: 0.24, yAbs: 0, yRatio: 0.42),
      width: 252,
      height: 46,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="252" height="46" fill="none" viewBox="0 0 252 46"><path fill=""#,
            #"" d="M183.83 18.844c-4.211-4.616-2.4-11.638 4.465-13.122 26.942-1.017 43.461 11.606 53.699 29.094.928 1.586 1.994 3.258 2.993 4.838 1.09 3.554-1.747 5.135-4.35 4.249-12.569-15.735-27.661-18.96-36.34-20.641-4.672-.904-10.265-.23-13.601-.809-3.821-.663-6.093-2.762-6.866-3.61M67.937 18.844c4.21-4.616 2.4-11.638-4.465-13.122-26.943-1.017-43.461 11.606-53.7 29.094-.928 1.586-1.993 3.258-2.992 4.838-1.09 3.554 1.747 5.135 4.35 4.249 12.57-15.735 27.66-18.96 36.34-20.641 4.672-.904 10.265-.23 13.6-.809 3.822-.663 6.094-2.762 6.867-3.61"/></svg>"#,
          ],
          slots: [.themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "thin",
      layer: 21,
      position: ItemPosition(xAbs: 0, xRatio: 0.27, yAbs: 0, yRatio: 0.44),
      width: 224,
      height: 16,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="224" height="16" fill="none" viewBox="0 0 224 16"><path stroke="#150c0c" stroke-linecap="round" stroke-linejoin="round" stroke-width="5" d="M169 8.5c27.307-14 52 5 52 5M55 8.5c-27.307-14-52 5-52 5"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "thinCurly",
      layer: 21,
      position: ItemPosition(xAbs: 0, xRatio: 0.26, yAbs: 0, yRatio: 0.44),
      width: 230,
      height: 14,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="230" height="14" fill="none" viewBox="0 0 230 14"><path stroke="#150c0c" stroke-linecap="round" stroke-linejoin="round" stroke-width="5" d="M167 10.5c34-20.5 36.5 6 60 0M63 10.5c-34-20.5-36.5 6-60 0"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "thinWide",
      layer: 21,
      position: ItemPosition(xAbs: 0, xRatio: 0.27, yAbs: 0, yRatio: 0.44),
      width: 223,
      height: 15,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="223" height="15" fill="none" viewBox="0 0 223 15"><path stroke="#150c0c" stroke-linecap="round" stroke-linejoin="round" stroke-width="6" d="M156 11.5c31.5-18.5 64 0 64 0M67 11.5c-31.5-18.5-64 0-64 0"/></svg>"##,
          ],
          slots: [],
        )
      ]
    )
  ]
}
