// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

extension KyuteTheme {
  static let earsItems: [ItemDescriptor] = [
    ItemDescriptor(
      key: "standard",
      layer: 5,
      position: ItemPosition(xAbs: 0, xRatio: 0.1875, yAbs: 0, yRatio: 0.47),
      width: 303,
      height: 48,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="303" height="48" fill="none" viewBox="0 0 303 48"><path fill=""#,
            ##"" stroke="#150c0c" stroke-width="8" d="M285 4c3.429 0 6.839 1.844 9.528 5.43S299 18.155 299 24s-1.782 10.984-4.472 14.57C291.839 42.156 288.429 44 285 44s-6.839-1.844-9.528-5.43S271 29.845 271 24s1.782-10.984 4.472-14.57C278.161 5.844 281.571 4 285 4ZM18 4c3.43 0 6.84 1.844 9.528 5.43C30.218 13.016 32 18.155 32 24s-1.782 10.984-4.472 14.57C24.84 42.156 21.43 44 18 44s-6.84-1.844-9.528-5.43C5.782 34.984 4 29.845 4 24S5.782 13.016 8.472 9.43C11.16 5.844 14.57 4 18 4Z"/></svg>"##,
          ],
          slots: [.themeColor],
        )
      ]
    )
  ]
}
