// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

extension KyuteTheme {
  static let mouthItems: [ItemDescriptor] = [
    ItemDescriptor(
      key: "lips1",
      layer: 70,
      position: ItemPosition(xAbs: 0, xRatio: 0.405, yAbs: 0, yRatio: 0.62),
      width: 82,
      height: 38,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="82" height="38" fill="none" viewBox="0 0 82 38"><path fill="#efbbbb" stroke="#150c0c" stroke-width="6" d="M51.783 3.338c.077.059.165.138.256.24 3.188 3.578 7.471 6.336 11.568 8.565 2.067 1.124 4.14 2.141 6.06 3.07 1.945.94 3.692 1.772 5.216 2.568l.013.007c-.421.284-1.016.589-1.782.863-3.274 1.174-5.65 2.967-7.675 4.838-.99.916-1.931 1.884-2.81 2.775-.9.911-1.762 1.77-2.692 2.589-3.496 3.074-8.303 5.912-18.937 5.912-10.544 0-15.35-2.874-18.844-5.983-.93-.827-1.789-1.695-2.683-2.612-.874-.896-1.81-1.87-2.79-2.787-2.002-1.875-4.352-3.672-7.585-4.827-.843-.302-1.533-.665-2.032-1.02a5 5 0 0 1-.236-.18c1.47-.731 3.184-1.463 5.127-2.296 1.925-.824 4.038-1.732 6.147-2.768 4.188-2.057 8.625-4.74 11.909-8.651q.108-.128.206-.21c1.253.615 2.682 1.653 4.463 2.857.89.602 1.872 1.242 2.835 1.733C38.418 8.48 39.658 9 41 9c1.388 0 2.644-.556 3.546-1.04.956-.514 1.93-1.182 2.798-1.794 1.773-1.248 3.18-2.28 4.44-2.828Z"/><path stroke="#150c0c" stroke-linecap="round" stroke-width="6" d="M8 18c17.105 4.333 47.895 4.333 65 0"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "lips2",
      layer: 70,
      position: ItemPosition(xAbs: 0, xRatio: 0.405, yAbs: 0, yRatio: 0.62),
      width: 82,
      height: 40,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="82" height="40" fill="none" viewBox="0 0 82 40"><path fill="#efbbbb" stroke="#150c0c" stroke-width="6" d="M51.8 3.343c.088.064.189.154.295.268 3.474 3.747 8.196 6.106 12.57 7.8 2.208.856 4.406 1.57 6.39 2.201 1.868.596 3.494 1.104 4.878 1.61-.305.329-.74.7-1.3 1.061-2.756 1.775-5.246 4.069-7.604 6.343-2.418 2.333-4.687 4.634-7.228 6.765-4.964 4.162-10.63 7.374-18.801 7.374-8.235 0-14.108-3.176-19.208-7.298-2.596-2.099-4.934-4.393-7.345-6.698-2.358-2.255-4.808-4.542-7.437-6.342a7 7 0 0 1-1.336-1.177 4 4 0 0 1-.287-.374c1.242-.464 2.783-.893 4.635-1.386 1.989-.529 4.283-1.119 6.587-1.866 4.581-1.485 9.667-3.726 13.351-7.951a2 2 0 0 1 .252-.246c1.255.614 2.686 1.655 4.47 2.861.89.602 1.872 1.242 2.835 1.733C38.418 8.48 39.658 9 41 9c1.388 0 2.644-.556 3.546-1.04.956-.514 1.93-1.182 2.798-1.794 1.775-1.25 3.184-2.283 4.445-2.831z"/><path stroke="#150c0c" stroke-linecap="round" stroke-width="6" d="M7 16.5c17.105 8.333 48.395 8.333 65.5 0"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "lipsSmile",
      layer: 70,
      position: ItemPosition(xAbs: 0, xRatio: 0.405, yAbs: 0, yRatio: 0.62),
      width: 82,
      height: 28,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="82" height="28" fill="none" viewBox="0 0 82 28"><ellipse cx="41.001" cy="14" fill="#f1b8b8" rx="26" ry="14"/><path stroke="#150c0c" stroke-linecap="round" stroke-width="6" d="M3 8.507c20 6 56 6 76 0"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "open",
      layer: 70,
      position: ItemPosition(xAbs: 0, xRatio: 0.405, yAbs: 0, yRatio: 0.62),
      width: 79,
      height: 52,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="79" height="52" fill="none" viewBox="0 0 79 52"><path fill="#f9ecec" stroke="#150c0c" stroke-width="8" d="M39.932 4.001c12.909.035 25.388 1.282 33.465 3.464 1.057.286 1.509 1.01 1.551 1.567.566 7.443-3.569 17.236-10.746 25.38C57.045 42.533 47.76 48 39.138 48c-8.304 0-17.306-6.083-24.402-14.808-3.467-4.263-6.291-8.94-8.174-13.362-1.912-4.487-2.726-8.405-2.535-11.234.008-.112.046-.248.223-.433.2-.208.554-.442 1.046-.577C14.159 5.146 27.024 3.966 39.932 4Z"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "openDimples",
      layer: 70,
      position: ItemPosition(xAbs: 0, xRatio: 0.37, yAbs: 0, yRatio: 0.62),
      width: 118,
      height: 34,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="118" height="34" fill="none" viewBox="0 0 118 34"><path fill="#f9ecec" stroke="#150c0c" stroke-width="6" d="M58.975 11.23c10.824 0 21.596.405 29.622 1.204 4.035.401 7.256.89 9.414 1.443q.527.135.92.26c-.527.722-1.374 1.6-2.57 2.588-2.404 1.983-5.882 4.142-9.974 6.144C78.152 26.9 68.051 30 60.21 30c-7.865 0-18.604-3.115-27.486-7.166-4.412-2.012-8.207-4.184-10.845-6.186-1.27-.964-2.185-1.825-2.77-2.54q.362-.111.83-.231c2.157-.552 5.378-1.042 9.413-1.443 8.026-.799 18.8-1.203 29.623-1.203Z"/><path stroke="#150c0c" stroke-width="2" d="M115.498 19.976s-6.798-2.028-10.821-6.71S100.877 1 100.877 1M1.97 19.976s6.797-2.028 10.82-6.71S16.59 1 16.59 1"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "smile1",
      layer: 70,
      position: ItemPosition(xAbs: 0, xRatio: 0.405, yAbs: 0, yRatio: 0.64),
      width: 82,
      height: 15,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="82" height="15" fill="none" viewBox="0 0 82 15"><path stroke="#150c0c" stroke-linecap="round" stroke-width="6" d="M3 3.507c20 10 56 10 76 0"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "smile2",
      layer: 70,
      position: ItemPosition(xAbs: 0, xRatio: 0.4, yAbs: 0, yRatio: 0.64),
      width: 86,
      height: 14,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="86" height="14" fill="none" viewBox="0 0 86 14"><path stroke="#d96767" stroke-linecap="round" stroke-width="8" d="M5 4.507c20 6 56 6 76 0"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "smileOpen",
      layer: 70,
      position: ItemPosition(xAbs: 0, xRatio: 0.37, yAbs: 0, yRatio: 0.62),
      width: 114,
      height: 42,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="114" height="42" fill="none" viewBox="0 0 114 42"><path fill="#f9ecec" stroke="#150c0c" stroke-width="8" d="M56.613 4c13.14 0 26.223.498 36.343 1.481 5.074.494 9.298 1.099 12.375 1.795 1.545.35 2.687.698 3.459 1.016.226.093.389.171.503.23.008.127.003.326-.049.624-.149.847-.629 2.103-1.637 3.721-2.003 3.216-5.624 7.114-10.55 10.906-9.859 7.59-24.09 14.113-38.831 14.113-14.774 0-29.848-6.548-40.559-14.199-5.347-3.819-9.376-7.75-11.668-11.007-1.156-1.643-1.725-2.91-1.922-3.751a3 3 0 0 1-.074-.442q.16-.081.434-.195c.772-.318 1.914-.666 3.46-1.016 3.076-.696 7.3-1.301 12.375-1.795C30.392 4.498 43.474 4 56.613 4Z"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "smirk",
      layer: 70,
      position: ItemPosition(xAbs: 0, xRatio: 0.43, yAbs: 0, yRatio: 0.64),
      width: 64,
      height: 18,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="64" height="18" fill="none" viewBox="0 0 64 18"><path stroke="#150c0c" stroke-linecap="round" stroke-width="6" d="M3 14.5C24 14.5 43.5 11 60.5 3"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "wideOpen",
      layer: 70,
      position: ItemPosition(xAbs: 0, xRatio: 0.385, yAbs: 0, yRatio: 0.62),
      width: 98,
      height: 56,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="98" height="56" fill="none" viewBox="0 0 98 56"><path fill="#f9ecec" stroke="#150c0c" stroke-width="8" d="M50.3 4.003c17.677.072 34.193 4.295 43.333 11.695.726 2.55.398 5.743-1.254 9.456-1.836 4.125-5.16 8.522-9.624 12.577C73.785 45.883 60.963 52 48.55 52c-12.214 0-24.772-6.994-33.62-15.737-4.39-4.338-7.651-8.901-9.428-12.89-1.59-3.57-1.72-6.016-1.283-7.459C15.067 8.024 32.61 3.93 50.3 4.003Z"/></svg>"##,
          ],
          slots: [],
        )
      ]
    )
  ]
}
