// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

extension MicahTheme {
  static let eyebrowsItems: [ItemDescriptor] = [
    ItemDescriptor(
      key: "down",
      layer: 25,
      position: ItemPosition(xAbs: 0, xRatio: 0.34, yAbs: 0, yRatio: 0.4),
      width: 149,
      height: 48,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="149" height="48" fill="none" viewBox="0 0 149 48"><path stroke=""#,
            #"" stroke-linecap="round" stroke-width="4" d="M27 26.5c6.167 2.5 21.1 3 31.5-15M94 4c5.167 5.333 18.1 12.8 28.5 0"/></svg>"#,
          ],
          slots: [.themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "eyelashesDown",
      layer: 25,
      position: ItemPosition(xAbs: 0, xRatio: 0.34, yAbs: 0, yRatio: 0.4),
      width: 149,
      height: 51,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="149" height="51" fill="none" viewBox="0 0 149 51"><path stroke=""#,
            #"" stroke-linecap="round" stroke-width="4" d="M27 28.633c6.167 2.5 21.1 3 31.5-15M94 6.133c5.167 5.333 18.1 12.8 28.5 0M37.148 28.59 31 23.165M116.219 11.576l1.785-8.004M45.598 24.947l-4.047-7.132M108.142 11.15l.938-8.146M52.674 19.333l-2.201-7.9M99.993 10.164 99.217 2"/></svg>"#,
          ],
          slots: [.themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "eyelashesUp",
      layer: 25,
      position: ItemPosition(xAbs: 0, xRatio: 0.34, yAbs: 0, yRatio: 0.4),
      width: 149,
      height: 51,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="149" height="51" fill="none" viewBox="0 0 149 51"><path stroke=""#,
            #"" stroke-linecap="round" stroke-width="4" d="M99 13.214c5.667-2.666 19-5.1 27 6.5M23.58 38.521c2.07-5.91 9.681-17.125 23.562-14.699M26.074 32.458l-6.148-5.427M122.961 14.157l6.148-5.427M32.523 26.814l-4.046-7.132M115.512 10.514l4.047-7.133M40.6 23.2l-2.202-7.9M106.436 9.9l2.201-7.9"/></svg>"#,
          ],
          slots: [.themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "up",
      layer: 25,
      position: ItemPosition(xAbs: 0, xRatio: 0.33, yAbs: 0, yRatio: 0.4),
      width: 149,
      height: 48,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="149" height="48" fill="none" viewBox="0 0 149 48"><path stroke=""#,
            #"" stroke-linecap="round" stroke-width="4" d="M99 10.214c5.667-2.666 19-5.1 27 6.5M23.58 35.521c2.07-5.91 9.681-17.125 23.562-14.699"/></svg>"#,
          ],
          slots: [.themeColor],
        )
      ]
    )
  ]
}
