// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

extension MicahTheme {
  static let noseItems: [ItemDescriptor] = [
    ItemDescriptor(
      key: "curve",
      layer: 21,
      position: ItemPosition(xAbs: 0, xRatio: 0.5, yAbs: 0, yRatio: 0.52),
      width: 32,
      height: 40,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="32" height="40" fill="none" viewBox="0 0 32 40"><path stroke="#171921" stroke-width="4" d="M16.5 7c-.333 3.833 0 12.2 4 15 5 3.5-.5 12-10.5 10"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "pointed",
      layer: 21,
      position: ItemPosition(xAbs: 0, xRatio: 0.5, yAbs: 0, yRatio: 0.52),
      width: 32,
      height: 40,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="32" height="40" fill="none" viewBox="0 0 32 40"><path stroke="#171921" stroke-width="4" d="M16.5 3c0 14 7 25 7 25S20 34 10 32"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "round",
      layer: 21,
      position: ItemPosition(xAbs: 0, xRatio: 0.5, yAbs: 0, yRatio: 0.52),
      width: 32,
      height: 40,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="32" height="40" fill="none" viewBox="0 0 32 40"><path stroke="#000" stroke-width="4" d="M12.307 12.34c5.446-1.24 14.377.62 12.417 10.543-1.743 8.82-11.11 9.303-13.724 6.822"/></svg>"##,
          ],
          slots: [],
        )
      ]
    )
  ]
}
