// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

extension MicahTheme {
  static let eyesItems: [ItemDescriptor] = [
    ItemDescriptor(
      key: "eyeshadow",
      layer: 20,
      position: ItemPosition(xAbs: 0, xRatio: 0.41, yAbs: 0, yRatio: 0.45),
      width: 96,
      height: 49,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="96" height="49" fill="none" viewBox="0 0 96 49"><circle cx="15.24" cy="20.63" r="12" fill="#d2eff3" transform="rotate(-6.276 15.24 20.63)"/><ellipse cx="16.53" cy="29.793" fill="#000" rx="9" ry="13.5" transform="rotate(-6.776 16.53 29.793)"/><circle cx="79.019" cy="12.001" r="12" fill="#d2eff3" transform="rotate(-6.276 79.02 12.001)"/><ellipse cx="80.531" cy="19.793" fill="#000" rx="9" ry="13.5" transform="rotate(-6.276 80.531 19.793)"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "round",
      layer: 20,
      position: ItemPosition(xAbs: 0, xRatio: 0.41, yAbs: 0, yRatio: 0.45),
      width: 96,
      height: 48,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="96" height="48" fill="none" viewBox="0 0 96 48"><ellipse cx="16.117" cy="28.927" fill="#000" rx="9" ry="10" transform="rotate(-6.776 16.117 28.927)"/><ellipse cx="80.149" cy="18.923" fill="#000" rx="9" ry="10" transform="rotate(-6.276 80.149 18.923)"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "smiling",
      layer: 20,
      position: ItemPosition(xAbs: 0, xRatio: 0.42, yAbs: 0, yRatio: 0.45),
      width: 96,
      height: 48,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="96" height="48" fill="none" viewBox="0 0 96 48"><path fill="#171921" fill-rule="evenodd" d="M5.287 34.073c.114.813 1.147.994 1.722.408 2.465-2.516 6.255-4.365 10.654-4.887 2.595-.309 5.091-.12 7.316.472.754.2 1.495-.437 1.232-1.17-1.666-4.646-6.366-7.7-11.475-7.093-5.942.706-10.186 6.095-9.48 12.036zM69.385 24.073c.113.813 1.146.994 1.721.409 2.443-2.486 6.192-4.312 10.542-4.829 2.565-.304 5.032-.118 7.232.464.754.2 1.495-.437 1.23-1.171-1.654-4.594-6.306-7.611-11.362-7.01-5.886.699-10.09 6.037-9.39 11.923q.012.107.027.213" clip-rule="evenodd"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "standard",
      layer: 20,
      position: ItemPosition(xAbs: 0, xRatio: 0.41, yAbs: 0, yRatio: 0.45),
      width: 96,
      height: 48,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="96" height="48" fill="none" viewBox="0 0 96 48"><ellipse cx="16.53" cy="29.402" fill="#000" rx="9" ry="13.5" transform="rotate(-6.776 16.53 29.402)"/><ellipse cx="80.531" cy="19.402" fill="#000" rx="9" ry="13.5" transform="rotate(-6.276 80.531 19.402)"/></svg>"##,
          ],
          slots: [],
        )
      ]
    )
  ]
}
