// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

extension MicahTheme {
  static let accessoriesItems: [ItemDescriptor] = [
    ItemDescriptor(
      key: "studEarRing",
      layer: 41,
      position: ItemPosition(xAbs: 0, xRatio: 0.26, yAbs: 0, yRatio: 0.62),
      width: 48,
      height: 50,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="48" height="50" fill="none" viewBox="0 0 48 50"><circle cx="25" cy="4" r="4" fill=""#,
            ##""/><circle cx="26" cy="3" r="1" fill="#ffedef"/></svg>"##,
          ],
          slots: [.themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "hoopEarRing",
      layer: 41,
      position: ItemPosition(xAbs: 0, xRatio: 0.265, yAbs: 0, yRatio: 0.62),
      width: 52,
      height: 52,
      fragments: [
        Fragment(
          segments: [
            #"<svg xmlns="http://www.w3.org/2000/svg" width="52" height="52" fill="none" viewBox="0 0 52 52"><path stroke=""#,
            #"" stroke-width="4" d="M26 2c13.255 0 24 10.745 24 24S39.255 50 26 50 2 39.255 2 26c0-6.391 3.5-11.5 6.572-16.5L9.5 8"/></svg>"#,
          ],
          slots: [.themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "none",
      layer: 0,
      position: ItemPosition(xAbs: 0, xRatio: 0, yAbs: 0, yRatio: 0),
      width: 0,
      height: 0,
      fragments: []
    )
  ]
}
