// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

extension MicahTheme {
  static let glassesItems: [ItemDescriptor] = [
    ItemDescriptor(
      key: "round",
      layer: 35,
      position: ItemPosition(xAbs: 0, xRatio: 0.32, yAbs: 0, yRatio: 0.42),
      width: 151,
      height: 65,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="151" height="65" fill="none" viewBox="0 0 151 65"><circle cx="122.861" cy="28" r="26" stroke="#000" stroke-width="4"/><circle cx="55.861" cy="37" r="26" stroke="#000" stroke-width="4"/><path stroke="#000" stroke-width="4" d="M97.861 35a8 8 0 1 0-16 0M30.361 39l-30 5.5"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "square",
      layer: 35,
      position: ItemPosition(xAbs: 0, xRatio: 0.3, yAbs: 0, yRatio: 0.4),
      width: 160,
      height: 74,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="160" height="74" fill="none" viewBox="0 0 160 74"><path stroke="#000" stroke-linecap="round" stroke-width="4" d="M36.5 42.5 2 49.125"/><path stroke="#000" stroke-width="4" d="m37.472 18.534 38.716-5.44a6 6 0 0 1 6.777 5.106l5.567 39.61a6 6 0 0 1-5.107 6.777l-34.473 4.845a6 6 0 0 1-6.653-4.478l-9.81-39.014a6 6 0 0 1 4.983-7.406ZM147.919 3.22l-38.716 5.44a6 6 0 0 0-5.107 6.778l5.567 39.61a6 6 0 0 0 6.777 5.107l34.472-4.845a6 6 0 0 0 5.162-6.139l-1.323-40.207a6 6 0 0 0-6.832-5.744ZM85.5 37.125l22-3.5"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "none",
      layer: 0,
      position: ItemPosition(xAbs: 0, xRatio: 0, yAbs: 0, yRatio: 0),
      width: 0,
      height: 0,
      fragments: []
    )
  ]
}
