// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

extension MicahTheme {
  static let mouthItems: [ItemDescriptor] = [
    ItemDescriptor(
      key: "frown",
      layer: 32,
      position: ItemPosition(xAbs: 0, xRatio: 0.45, yAbs: 0, yRatio: 0.62),
      width: 77,
      height: 64,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="77" height="64" fill="none" viewBox="0 0 77 64"><path stroke="#000" stroke-width="4" d="M1.855 41c3.211-7.957 15.107-24.767 37.007-28.348s33.12 8.455 35.994 14.92"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "laughing",
      layer: 32,
      position: ItemPosition(xAbs: 0, xRatio: 0.46, yAbs: 0, yRatio: 0.6),
      width: 72,
      height: 64,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="72" height="64" fill="none" viewBox="0 0 72 64"><path fill="#171921" stroke="#171921" stroke-width="4" d="M2.043 21.665C1.71 19.65 3.43 17.993 5.36 18.232c4.744.59 21.134 2.397 31.956.908 9.865-1.357 23.854-6.656 28.083-8.322l.168-.061c1.753-.573 3.742.57 3.907 2.574A34.001 34.001 0 0 1 14.68 42.934 34 34 0 0 1 2.043 21.665Z"/><mask id="a0" width="65" height="37" x="3" y="12" maskUnits="userSpaceOnUse"><path fill="#fff" d="M67.346 12.193A32 32 0 1 1 3.83 20.05z"/></mask><g mask="url(#a0)"><circle cx="40.075" cy="52.315" r="21.5" fill="#fc909f" transform="rotate(-7.053 40.075 52.315)"/></g></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "nervous",
      layer: 32,
      position: ItemPosition(xAbs: 0, xRatio: 0.45, yAbs: 0, yRatio: 0.6),
      width: 79,
      height: 64,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="79" height="64" fill="none" viewBox="0 0 79 64"><rect width="70" height="24" x="3.684" y="17.471" fill="#000" rx="4" transform="rotate(-4 3.684 17.47)"/><path fill="#fff" fill-rule="evenodd" d="M67.257 13.025 9.939 17.033l1.84 7.005a6 6 0 0 0 6.222 4.46 6 6 0 0 0-5.54 5.284l-.847 7.193 57.317-4.008-1.84-7.005a6 6 0 0 0-6.222-4.46 6 6 0 0 0 5.54-5.284z" clip-rule="evenodd"/><path stroke="#000" stroke-width="4" d="M68.515 11.649c3.584-.77 7.063 1.8 7.32 5.485l1.02 14.57c.257 3.686-2.83 6.714-6.487 6.45-7.084-.51-20.6-1.28-30.195-.609-9.595.672-22.873 3.315-29.817 4.806-3.584.77-7.063-1.8-7.321-5.485l-1.019-14.57-.014-.344c-.05-3.528 2.959-6.362 6.5-6.107 7.085.51 20.6 1.28 30.196.61 9.595-.671 22.873-3.315 29.816-4.806Z"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "pucker",
      layer: 32,
      position: ItemPosition(xAbs: 0, xRatio: 0.47, yAbs: 0, yRatio: 0.6),
      width: 64,
      height: 64,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" fill="none" viewBox="0 0 64 64"><path stroke="#000" stroke-width="4" d="M26 16.697c4.167-2.334 21-5.3 21 1.5 0 8.5-11.5 8-11.5 8s13.045-3.162 10.5 6c-2.5 9-9.5 5.5-11.5 4.5"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "sad",
      layer: 32,
      position: ItemPosition(xAbs: 0, xRatio: 0.47, yAbs: 0, yRatio: 0.6),
      width: 64,
      height: 64,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" fill="none" viewBox="0 0 64 64"><path stroke="#000" stroke-width="4" d="M13 46c1.715-7.957 8.07-24.767 19.77-28.348S50.466 26.107 52 32.572"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "smile",
      layer: 32,
      position: ItemPosition(xAbs: 0, xRatio: 0.47, yAbs: 0, yRatio: 0.6),
      width: 67,
      height: 64,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="67" height="64" fill="none" viewBox="0 0 67 64"><path stroke="#000" stroke-width="4" d="M1.979 17.5c2.5 17 31 25 57 5.5"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "smirk",
      layer: 32,
      position: ItemPosition(xAbs: 0, xRatio: 0.47, yAbs: 0, yRatio: 0.6),
      width: 64,
      height: 64,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" fill="none" viewBox="0 0 64 64"><path stroke="#000" stroke-width="4" d="M10 24.165c4.941 6.447 12.428 13.589 23.977 11.96s16.687-9.595 15.172-16.047"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "surprised",
      layer: 32,
      position: ItemPosition(xAbs: 0, xRatio: 0.47, yAbs: 0, yRatio: 0.6),
      width: 64,
      height: 64,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="64" height="64" fill="none" viewBox="0 0 64 64"><path fill="#000" stroke="#000" stroke-width="3.591" d="M27.836 9.523c10.837-1.961 20.981 7.03 23.19 19.23 2.207 12.201-4.142 24.177-14.979 26.138s-20.98-7.03-23.189-19.23C10.65 23.46 17 11.484 27.836 9.523Z"/><mask id="a0" width="36" height="43" x="14" y="11" maskUnits="userSpaceOnUse"><ellipse cx="31.942" cy="32.207" fill="#fff" rx="17.598" ry="21.257" transform="rotate(-10.258 31.942 32.207)"/></mask><g mask="url(#a0)"><ellipse cx="35.202" cy="50.219" fill="#fc909f" rx="20.205" ry="18.305" transform="rotate(-10.258 35.202 50.219)"/></g></svg>"##,
          ],
          slots: [],
        )
      ]
    )
  ]
}
