// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

extension MicahTheme {
  static let earsItems: [ItemDescriptor] = [
    ItemDescriptor(
      key: "medium",
      layer: 40,
      position: ItemPosition(xAbs: 0, xRatio: 0.27, yAbs: 0, yRatio: 0.53),
      width: 48,
      height: 52,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="48" height="52" fill="none" viewBox="0 0 48 52"><path stroke="#000" stroke-width="4" d="m37 42.536-.534.575C32.808 47.053 28.003 50 22.524 50c-3.318 0-6.433-.489-8.867-1.872-2.553-1.451-4.205-3.806-4.594-7.074a8 8 0 0 1 .243-3.212c-3.548-3.116-5.688-7.804-6.22-14.176-.544-6.539 1.508-11.784 5.311-15.371C12.16 4.747 17.44 3 23.08 3c4.692 0 9.232 1.254 12.966 3.545L37 7.13z"/><path fill=""##,
            ##"" fill-rule="evenodd" d="M42.972 23.984q.107-.978.108-1.984c0-10.217-9.507-17-20-17s-19 6.5-18 18.5c.556 6.677 2.946 11.072 6.65 13.717-.588 1.024-.845 2.227-.682 3.6.63 5.281 5.138 7.183 11.476 7.183 11.105 0 19.892-14.047 20.448-24.016" clip-rule="evenodd"/><path stroke="#171921" stroke-width="4" d="M27.5 13.5c-4-1.833-12.8-2.8-16 8"/><path stroke="#171921" stroke-width="4" d="M17 14c2.167 1.833 6.3 7.5 5.5 15.5"/></svg>"##,
          ],
          slots: [.themeColor],
        )
      ]
    ),
    ItemDescriptor(
      key: "small",
      layer: 40,
      position: ItemPosition(xAbs: 0, xRatio: 0.28, yAbs: 0, yRatio: 0.54),
      width: 48,
      height: 48,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="48" height="48" fill="none" viewBox="0 0 48 48"><path stroke="#171921" stroke-width="8" d="M30.5 6.176A23.8 23.8 0 0 0 23.08 5c-10.493 0-19 6.5-18 18.5 1.042 12.5 8.507 17 19 17q1.753-.002 3.42-.299c1.21-.214 2.381-.54 3.5-.966"/><path fill=""##,
            ##"" d="M31.5 39.036a19.4 19.4 0 0 1-7.42 1.464c-10.493 0-17.958-4.5-19-17-1-12 7.507-18.5 18-18.5 3.138 0 6.187.606 8.92 1.73z"/><path stroke="#171921" stroke-width="4" d="M27.5 13.5c-4-1.833-12.8-2.8-16 8"/><path stroke="#171921" stroke-width="4" d="M17 14c2.167 1.833 6.3 7.5 5.5 15.5"/></svg>"##,
          ],
          slots: [.themeColor],
        )
      ]
    )
  ]
}
