// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

extension VampireSkinTheme {
  static let noseItems: [ItemDescriptor] = [
    ItemDescriptor(
      key: "wide",
      layer: 21,
      position: ItemPosition(xAbs: 0, xRatio: 0.485, yAbs: 0, yRatio: 0.45870000000000005),
      width: 16.8,
      height: 6.533,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="16.8" height="6.533" fill="none" viewBox="0 0 18 7"><path fill="#222031" d="M7.34.082c8.73-.96 12.31 6.87 8.38 6.49-.57-.06-3.31-3.86-9.7-2.56-9.26 7.24-7.06-3.01 1.32-3.93"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "nostrils",
      layer: 21,
      position: ItemPosition(xAbs: 0, xRatio: 0.46820000000000006, yAbs: 0, yRatio: 0.45089999999999997),
      width: 33.6,
      height: 13.007,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="33.6" height="13.007" fill="none" viewBox="0 0 31 12"><path fill="#222031" d="M11.057.142c26.45-1.97 19.99 17.28 15.34 9.73 1.22-7.7-24.03-7.56-22.09.1-4.03 6.62-9.69-7.65 6.75-9.83"/></svg>"##,
          ],
          slots: [],
        )
      ]
    )
  ]
}
