// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

extension VampireSkinTheme {
  static let mouthItems: [ItemDescriptor] = [
    ItemDescriptor(
      key: "fangGrin",
      layer: 20,
      position: ItemPosition(xAbs: 0, xRatio: 0.3950000000000001, yAbs: 0, yRatio: 0.4802),
      width: 117.6,
      height: 56.59,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="117.6" height="56.59" fill="none" viewBox="0 0 133 64"><path fill="#222031" d="M13.675 5.31c30.13 12.93 71.81 14.29 102.86 1.03 9.2-3.94 19.9-15.55 13.82 8.62-8.02 31.93-46.98 60.8-89.19 43.81-16.99-6.83-36.15-26.92-40.18-46.64-4.1-20.04 5.47-9.92 12.69-6.82"/><path fill="#6C273A" d="M3.975 4.38c4.49.53 8.39 4.28 12.32 4.87 3.62 15.32 6.89 30.75 13.87 5.5 1.04-1.18 5.54.89 6.5 1.06 12.33 2.13 28.84 4 42.5 2.78 3.74-.33 22.14-4.33 23.03-3.33 6.57 24.35 9.95 9.42 13.22-4.73 3.51-2.5 8.61-4.66 13.15-6.15-1.11 26.29-23.81 48.27-45.4 54.03C42.045 68.8 5.915 38.63 3.975 4.38"/><path fill="#EBECF3" d="M18.335 10.88c1.37-.49 10.08 2.71 10.08 2.71-.6 4.11-2.84 9.76-4.95 12.94-2.21-4.53-4.13-9.97-5.13-15.65"/><path fill="#FEFEFD" d="M113.415 10.88c-2.59 14.56-5.83 21.89-9.5 2.72z"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "smile",
      layer: 20,
      position: ItemPosition(xAbs: 0, xRatio: 0.39000000000000007, yAbs: 0, yRatio: 0.5122000000000001),
      width: 123.2,
      height: 18.327,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="123.2" height="18.327" fill="none" viewBox="0 0 121 18"><path fill="#222031" d="M118.12.134c3.41-.88 3.2 2.82 1.09 3.99-26.88 18.27-92.17 18.09-118.79-.65-1-1.57-.24-3.18 2.55-2.85 25.85 17.97 89.61 18.22 115.15-.49"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "flat",
      layer: 20,
      position: ItemPosition(xAbs: 0, xRatio: 0.43500000000000005, yAbs: 0, yRatio: 0.5215),
      width: 72.8,
      height: 4.044,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="72.8" height="4.044" fill="none" viewBox="0 0 72 4"><path fill="#222031" d="M1.41.06C1.57 0 70.37-.03 70.54.04c1.27.52 1.28 2.49-.01 3.01-6.8-.52-69.1.75-70.11-.26C-.54 1.83.3.46 1.41.06"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "smirk",
      layer: 20,
      position: ItemPosition(xAbs: 0, xRatio: 0.4222, yAbs: 0, yRatio: 0.4923),
      width: 95.2,
      height: 28.644,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="95.2" height="28.644" fill="none" viewBox="0 0 113 34"><path fill="#222031" d="M111.35 0c4.95 5.16-8.09 12.89-11.8 14.25-3.34 15.95-5.43 30.16-14.46 6.25C61.91 26.69 26.8 28.51.3 24.18L0 22.13C41.21 24.3 92.94 24.67 111.35 0"/><path fill="#EBECF3" d="M97.05 16c-3.92 15.96-3.73 21.46-10.03 3.25 3.5-.75 5.94-2.98 10.03-3.25"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "hiss",
      layer: 20,
      position: ItemPosition(xAbs: 0, xRatio: 0.4518000000000001, yAbs: 0, yRatio: 0.5057),
      width: 56,
      height: 35.538,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="56" height="35.538" fill="none" viewBox="0 0 52 33"><path fill="#222031" d="M27.001 32.783c-34.24.18-33.95-26.26-10.17-31.72 34.68-7.97 52.11 31.5 10.17 31.72"/><path fill="#6C273A" d="M11.341 14.333c3.57-.84 2.92-8.75 5.21-10.15 5.38-1.5 15.53-1.63 19.58.65 2.06 4.93 4.53 19.25 8.84 6.25h1.59c16.55 26.72-58.56 23.82-41.27-.24 1.83-2.76 5.05 9.49 5.66 3.71z"/><path fill="#FEFEFD" d="M10.951 14.552c-3.93-4.94-4.28-6.39 2.13-9.07 1.48.41-1.88 7.17-1.74 8.85z"/><path fill="#EBECF3" d="M38.511 5.522c5.99 4.01 7.07 1.84 3.04 9.3-1.01-.12-3.67-8.22-3.04-9.3"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "laugh",
      layer: 20,
      position: ItemPosition(xAbs: 0, xRatio: 0.40180000000000005, yAbs: 0, yRatio: 0.4825),
      width: 112,
      height: 61.557,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="112" height="61.557" fill="none" viewBox="0 0 131 72"><path fill="#222031" d="M15.352 3.429c31.15 7.8 66.57 8.86 98.73.9 11.07-2.74 17.58-10.61 16.25 6.15-15.59 80.05-111.2 82.09-129.43 3.71-3.44-20.53 3.3-13.56 14.45-10.76"/><path fill="#6C273A" d="m3.332 3.309 14.07 3.5c4.88 13.5 7.41 28.38 14.07 3.63 19.28 2.63 48.84 2.69 67.29.52 6.05 22.12 9.06 12.34 13.15-3.02 4.73-1.18 9.92-3.5 15.57-4-.97 22.92-11.65 37.3-23.34 49.5h-1.93c-16.28-19.72-58.87-21.31-76.87-1.5h-.8c-10.91-11.76-20.91-26.28-21.21-48.63"/><path fill="#CD4A59" d="M100.332 54.029v2.41c-13.05 11.76-36.72 15.98-57.25 7.9-2.24-.88-16.95-8.2-15.81-11.81 16.63-17.58 57.89-16.57 73.06 1.5"/><path fill="#EBECF3" d="M20.332 7.939c.13-.13 9.35 1.34 9.5 2.3-4.91 17.34-6.33 12.4-9.5-2.3M109.272 8.439c.04 1.31.35-.49.65 1.05-4.36 14.18-5.14 17-9.59.54z"/></svg>"##,
          ],
          slots: [],
        )
      ]
    )
  ]
}
