// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

extension VampireSkinTheme {
  static let eyebrowsItems: [ItemDescriptor] = [
    ItemDescriptor(
      key: "stern",
      layer: 22,
      position: ItemPosition(xAbs: 0, xRatio: 0.39320000000000005, yAbs: 0, yRatio: 0.3572000000000001),
      width: 117.6,
      height: 16.355,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="117.6" height="16.355" fill="none" viewBox="0 0 151 21"><path fill="#222031" d="M1.988.071c3.93-1.2 55.14 13.16 56.24 14.25 1.14 1.15 1.87 4.44-.05 5.5-6.03 3.34-53.45-10.83-56.94-13.28-1.42-.99-2.13-5.59.75-6.47M144.737.141c3.3-.29 8.07 1.95 5.13 5.97-1.63 2.22-47.76 16.82-55.73 13.96-3.7-3.01-.8-5.86 1.66-6.94.32-.15 48.94-12.99 48.94-12.99"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "curved",
      layer: 22,
      position: ItemPosition(xAbs: 0, xRatio: 0.39000000000000007, yAbs: 0, yRatio: 0.3471),
      width: 123.2,
      height: 23.308,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="123.2" height="23.308" fill="none" viewBox="0 0 148 28"><path fill="#222031" d="M118.458 8.055c6.72 5.91 23.15 8.46 27.15 13.79.3.41 3.19 5.74.09 5.44-10.99-8.92-32.33-4.78-37.13-19.88-.01-15.44 7.58-1.38 9.89.65M38.568 2.445c.76 20.4-26.45 15.64-37.44 24.87-3.6-2.23 2.51-7.51 3.19-7.98 9.32-6.44 15.06-2.03 27-14.36 1.33-1.37 5.39-8.72 7.25-2.53"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "thin",
      layer: 22,
      position: ItemPosition(xAbs: 0, xRatio: 0.40140000000000003, yAbs: 0, yRatio: 0.366),
      width: 106.4,
      height: 3.97,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="106.4" height="3.97" fill="none" viewBox="0 0 134 5"><path fill="#222031" d="M33.623 4.225c-10.59-.77-21.83-.64-32.17.37-10.46-4.99 39.24-7 32.17-.37M133.393 4.325c-9.46-.43-22.61-.61-32.49-.5-6.23-5.69 38.81-4.62 32.49.5"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "straight",
      layer: 22,
      position: ItemPosition(xAbs: 0, xRatio: 0.39320000000000005, yAbs: 0, yRatio: 0.36810000000000004),
      width: 117.6,
      height: 3.769,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="117.6" height="3.769" fill="none" viewBox="0 0 156 5"><path fill="#222031" d="m.481 0 57.78.26c.33.33.33 3.67 0 4-17.77.41-40.23.41-58 0-.28-.28-.49-3.88.22-4.26M98.721 0l57.04.26c.33.33.33 3.67 0 4-4.67 0-56.04.79-57.44.26-1.01-.39-1.25-3.85.4-4.52"/></svg>"##,
          ],
          slots: [],
        )
      ]
    )
  ]
}
