// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

extension VampireSkinTheme {
  static let eyesItems: [ItemDescriptor] = [
    ItemDescriptor(
      key: "closed",
      layer: 20,
      position: ItemPosition(xAbs: 0, xRatio: 0.39680000000000004, yAbs: 0, yRatio: 0.3984),
      width: 117.6,
      height: 12.165,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="117.6" height="12.165" fill="none" viewBox="0 0 145 15"><path fill="#222031" d="M117.36.317c21.38-2.91 32.85 15.22 25.21 13.93-6.19-7.42-20.99-11.84-32.68-5.78-15.45 16.69-10.6-5.7 7.47-8.15M44.11 13.766c-4.22 2.88-4.16-3.58-12.51-6.61-17.24-6.26-28.85 7.08-28.89 7.09-1.28.22-2.57-.75-2.71-1.49 5.18-16.34 40.41-17.52 44.11 1.01"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "glare",
      layer: 20,
      position: ItemPosition(xAbs: 0, xRatio: 0.36140000000000005, yAbs: 0, yRatio: 0.38430000000000003),
      width: 151.2,
      height: 31.539,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="151.2" height="31.539" fill="none" viewBox="0 0 163 34"><path fill="#222031" d="M159.94 0c2.92 1.48 1.92 8.29 2.26 11.79-1.01 2.48-26.91 4.6-27.19 5.62 8.62 20.82-26.46 22.36-19.75.94l-16.92.66c-2.71-.65-4.41-15.98-.5-15.4 21-.74 42.62-2.05 62.1-3.61M1.71 0l62.42 4.03c3.33 19.77-3.63 14.36-20.09 14.33 6.17 21.42-28.31 20.05-19.98-1.09-.2-1.23-23-2.85-24.06-5.46C.45 8.61-.84 1.6 1.71 0"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "dot",
      layer: 20,
      position: ItemPosition(xAbs: 0, xRatio: 0.41000000000000003, yAbs: 0, yRatio: 0.41130000000000005),
      width: 100.8,
      height: 17.379,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="100.8" height="17.379" fill="none" viewBox="0 0 116 20"><path fill="#222031" d="M112.506 2.323c9.19 7.68-2.39 22.47-12.08 14.76-9.8-7.79 2.38-22.86 12.08-14.76M17.156 4.083c6.88 9.45-6.76 20.76-14.52 12.23-8.84-9.72 6.75-22.91 14.52-12.23"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "wide",
      layer: 20,
      position: ItemPosition(xAbs: 0, xRatio: 0.4065000000000001, yAbs: 0, yRatio: 0.39670000000000005),
      width: 100.8,
      height: 27.684,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="100.8" height="27.684" fill="none" viewBox="0 0 142 39"><path fill="#FEFEFD" d="M138.731 28.762c-3.58 7.37-13.37 14.56-22.69 6.64-1.84-2.34-.04-4.07-.02-3.94 19.39 7.48 13.46-25.75-1.46-12.78-2.79-2.93 3.18-12.44 4.35-13.99 16.05-6.89 22.21 9.05 19.82 24.07"/><path fill="#222031" d="M116.02 31.462c-3.17-2.13-3.759-8.88-1.459-12.78 14.92-12.97 20.849 20.26 1.459 12.78M118.911 4.692c.18-.11.81-2.49 3.82-3.54 15.48-4.94 24.25 16.61 16 27.61 2.39-15.02-3.77-30.96-19.82-24.07"/><path fill="#FEFEFD" d="M24.13 5.622c.98 3.59 4.72 8.1 3.13 12.44-13.22-10.36-20.31 16.46-3.14 14.49v2.98c-8.45 7.87-20.56-1.6-21.02-10.37-.66-14.02 7.32-28.36 21.03-19.54"/><path fill="#222031" d="M27.26 18.063c3.47 5.66 2.29 11.83-3.14 14.49-17.17 1.97-10.08-24.85 3.14-14.49M3.1 25.162s-1.84-.42-1.9-.49c-3.66-4.86.81-26.56 16.71-24.54 2.46.31 8.16 2.6 6.22 5.49-13.71-8.82-21.69 5.52-21.03 19.54"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "droopy",
      layer: 20,
      position: ItemPosition(xAbs: 0, xRatio: 0.38650000000000007, yAbs: 0, yRatio: 0.4014),
      width: 123.2,
      height: 16.318,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="123.2" height="16.318" fill="none" viewBox="0 0 151 20"><path fill="#222031" d="m50.344 6.175-9.03-1.97c4.12 21.64-28.26 20.52-21.02-1.15-2.74-.67-21.79 3.52-20.2-.85 6.04-2.78 56.99-4.28 50.25 3.97M150.154 2.125v2.17l-17.61-1.29c6.35 21.13-24.99 23.29-21.46 1.14-.32-.4-9.64 2.69-10.43 1.39-1.52-7.98 48.59-5.51 49.5-3.41"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "happy",
      layer: 20,
      position: ItemPosition(xAbs: 0, xRatio: 0.41000000000000003, yAbs: 0, yRatio: 0.4006),
      width: 100.8,
      height: 13.244,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="100.8" height="13.244" fill="none" viewBox="0 0 137 18"><path fill="#222031" d="M134.139 15.253c-1.46-.25-14.97-18.16-31.17-1.75-1.04 1.05-2.62 5.33-4.48 2.4-2.52-3.99 7.51-13.07 10.45-14.36 17.21-7.56 34.04 15.2 25.2 13.71M16.489.253c15.07-2.07 23.59 13.66 21 16.25-2.03 2.03-3.71-2.61-4.27-3.15-16.55-16.01-28.64 1.25-31.17 1.9H.259c-2.25-6.64 10.75-14.25 16.23-15"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "lidded",
      layer: 20,
      position: ItemPosition(xAbs: 0, xRatio: 0.39820000000000005, yAbs: 0, yRatio: 0.40620000000000006),
      width: 112,
      height: 14.933,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="112" height="14.933" fill="none" viewBox="0 0 150 20"><path fill="#222031" d="M47.786.683c4.06 4.73-7.26 2.88-10.76 3.25 7.55 20.92-28.13 21.53-20.28.03-3.06-.94-21.57 2.37-15.55-3.28 13.82-.85 32.53-.97 46.59 0M148.026.433c6.05 6.05-11.52 2.55-14.98 3.53 8.18 21.16-28.53 21.07-20.29-.03-3.41-.5-15.45 1.67-11.03-2.95 3.14-.67 45.84-.74 46.3-.55"/></svg>"##,
          ],
          slots: [],
        )
      ]
    ),
    ItemDescriptor(
      key: "arched",
      layer: 20,
      position: ItemPosition(xAbs: 0, xRatio: 0.39320000000000005, yAbs: 0, yRatio: 0.3957),
      width: 117.6,
      height: 20.8,
      fragments: [
        Fragment(
          segments: [
            ##"<svg xmlns="http://www.w3.org/2000/svg" width="117.6" height="20.8" fill="none" viewBox="0 0 147 26"><path fill="#222031" d="M146.675 8.421v2.42c-5.95-2.62-10.34-6.86-18.5-7.11 18.47 20.22-21.02 34.03-17.04 5.61-1.51-.45-8.14 9.36-8.55 5.61 8.25-15.77 30.28-20.56 44.09-6.53M39.825 12.341c-.11-.04-2.24-2.97-3.02-2 1.02 28.24-36.09 11.62-17.05-6.08-6.78-.96-13.61 3.31-17.77 6.58-1.26.28-2.44.11-1.81-1.91 21.65-23.34 49.99 6.84 39.65 3.41"/></svg>"##,
          ],
          slots: [],
        )
      ]
    )
  ]
}
