// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

/// Item identifiers for the orks theme.
public enum Orks {
  public enum Body: String, CaseIterable, Sendable {
    case tunic
    case armor
    case studdedVest
    case furJacket
    case openJacket
    case hoodie
    case wrapTunic
  }

  public enum Eyebrows: String, CaseIterable, Sendable {
    case `default`
    case angry
    case calm
    case confident
    case neutral
  }

  public enum Eyes: String, CaseIterable, Sendable {
    case `default`
    case tired
    case scared
  }

  public enum Hair: String, CaseIterable, Sendable {
    case bun
    case braids
    case sideForelock
    case long
    case braid
    case dreadlocks
    case mohawk
    case short
  }

  public enum Head: String, CaseIterable, Sendable {
    case `default`
    case large
    case sqaure
  }

  public enum Mouth: String, CaseIterable, Sendable {
    case smile
    case hooky
    case openTusks
    case neutral
    case dracula
    case `open`
  }

  public enum Nose: String, CaseIterable, Sendable {
    case `default`
  }
}
