// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

/// Namespace for the orks theme's generated data.
public enum OrksTheme {}

extension AvatuneTheme {
  /// The orks theme, generated from @avatune/orks-theme@1.0.0.
  public static let orks: AvatuneTheme = AvatuneTheme(
    name: "orks",
    style: AvatuneTheme.Style(size: 960, borderRadius: .percent(50)),
    backgroundPalette: [.hex(0xE4D5B7), .hex(0xEDE4D3), .hex(0xF2D9BF), .hex(0xDDE6CC), .hex(0xEBCFCB), .hex(0xD3E1E6)],
    categories: [
      AvatuneTheme.Category(
        category: .body,
        palette: [.hex(0x000000)],
        items: OrksTheme.bodyItems
      ),
      AvatuneTheme.Category(
        category: .eyebrows,
        palette: [.hex(0x3F2C1D), .hex(0x22201C), .hex(0x765332)],
        items: OrksTheme.eyebrowsItems
      ),
      AvatuneTheme.Category(
        category: .eyes,
        palette: [.hex(0x000000)],
        items: OrksTheme.eyesItems
      ),
      AvatuneTheme.Category(
        category: .hair,
        palette: [.hex(0x3F2C1D), .hex(0x22201C), .hex(0x765332)],
        items: OrksTheme.hairItems
      ),
      AvatuneTheme.Category(
        category: .head,
        palette: [.hex(0x789E4B), .hex(0x6E9CAF), .hex(0xB84C4C)],
        items: OrksTheme.headItems
      ),
      AvatuneTheme.Category(
        category: .mouth,
        palette: [.hex(0x000000)],
        items: OrksTheme.mouthItems
      ),
      AvatuneTheme.Category(
        category: .nose,
        palette: [.hex(0x789E4B), .hex(0x6E9CAF), .hex(0xB84C4C)],
        items: OrksTheme.noseItems
      )
    ],
    connectedColors: [ConnectedColor(dependent: .eyebrows, source: .hair), ConnectedColor(dependent: .nose, source: .head)],
    predictorMappings: nil
  )
}
