name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version-file: ".node-version"

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: "package.json"

      - name: Install Dependencies
        # --frozen-lockfile removed due to https://github.com/oven-sh/bun/issues/26973
        run: bun install

      - name: Build Packages
        run: bun run build

      - name: Lint
        run: bun run lint

      - name: Check Format
        run: bun run check

      - name: Type Check
        run: bun run check-types

      - name: Run Tests
        run: bun run test
        env:
          CI: true
