// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

import AvatuneCore

/// Namespace for the miniavs theme's generated data.
public enum MiniavsTheme {}

extension AvatuneTheme {
  /// The miniavs theme, generated from @avatune/miniavs-theme@2.1.1.
  public static let miniavs: AvatuneTheme = AvatuneTheme(
    name: "miniavs",
    style: AvatuneTheme.Style(size: 64, borderRadius: .percent(100)),
    backgroundPalette: [.hex(0x6F6FFB), .hex(0x68DBF2), .hex(0xE4ECF7), .hex(0xFFBAF8), .hex(0xF16063), .hex(0x4C6FFF)],
    categories: [
      AvatuneTheme.Category(
        category: .hair,
        palette: [.hex(0x1B0B47), .hex(0xAD3A20), .hex(0x47280B)],
        items: MiniavsTheme.hairItems
      ),
      AvatuneTheme.Category(
        category: .head,
        palette: [.hex(0x836055), .hex(0xFFCB7E), .hex(0xF5D0C5)],
        items: MiniavsTheme.headItems
      ),
      AvatuneTheme.Category(
        category: .body,
        palette: [.hex(0xE05A33), .hex(0xFF4DD8), .hex(0x3633E0)],
        items: MiniavsTheme.bodyItems
      ),
      AvatuneTheme.Category(
        category: .faceHair,
        palette: [.hex(0x1B0B47), .hex(0x47280B), .hex(0xAD3A20)],
        items: MiniavsTheme.faceHairItems
      ),
      AvatuneTheme.Category(
        category: .faceDetails,
        palette: [.hex(0xFF859B)],
        items: MiniavsTheme.faceDetailsItems
      ),
      AvatuneTheme.Category(
        category: .eyes,
        palette: [.hex(0x1B0B47)],
        items: MiniavsTheme.eyesItems
      ),
      AvatuneTheme.Category(
        category: .glasses,
        palette: [.hex(0x000000)],
        items: MiniavsTheme.glassesItems
      ),
      AvatuneTheme.Category(
        category: .mouth,
        palette: [.hex(0xB03E67)],
        items: MiniavsTheme.mouthItems
      )
    ],
    connectedColors: [ConnectedColor(dependent: .faceHair, source: .hair)],
    predictorMappings: AvatuneTheme.PredictorMappings(
      hair: ["long": ["long", "ponyTail"], "medium": ["elvis", "stylish", "curly"], "short": ["classic1", "classic2", "baldness", "slaughter"]],
      faceHair: ["facial_hair": ["freddy", "horshoe", "pencilThin", "pencilThinBeard"], "none": ["none"]],
      hairColor: ["black": [.hex(0x1B0B47)], "blond": [.hex(0xAD3A20)], "brown": [.hex(0x47280B)], "gray": [.hex(0xAD3A20)]],
      skinTone: ["dark": [.hex(0x836055)], "light": [.hex(0xF5D0C5)], "medium": [.hex(0xFFCB7E)]]
    )
  )
}
