// AUTO-GENERATED by scripts/generate-swift.ts. Do not edit by hand.
// Run `bun run generate:swift` (or `bun run generate`) to refresh.

/// Item identifiers for the miniavs theme.
public enum Miniavs {
  public enum Hair: String, CaseIterable, Sendable {
    case baldness
    case classic1
    case classic2
    case curly
    case elvis
    case long
    case ponyTail
    case slaughter
    case stylish
  }

  public enum Head: String, CaseIterable, Sendable {
    case standard
    case thin
    case wide
  }

  public enum Body: String, CaseIterable, Sendable {
    case standard
    case golf
  }

  public enum FaceHair: String, CaseIterable, Sendable {
    case freddy
    case horshoe
    case pencilThin
    case pencilThinBeard
    case `none`
  }

  public enum FaceDetails: String, CaseIterable, Sendable {
    case standard
    case `none`
  }

  public enum Eyes: String, CaseIterable, Sendable {
    case standard
    case confident
    case happy
  }

  public enum Glasses: String, CaseIterable, Sendable {
    case glasses
    case `none`
  }

  public enum Mouth: String, CaseIterable, Sendable {
    case standard
    case toothless
  }
}
